### ISSUE TITLE
nill-pointer while backing up

### ISSUE THREAD

**Issue by kamudadreieck** [restic/restic#108]
```
./src/go/bin/restic -r /var/run/media/robert/00000000-98ab-4483-97e4-000000000000/_restic2/ backup ~/
Enter Password for Repository: 
scan [/home/robert]
[0:14] 28436 directories, 248000 files, 99.066 GiB
Done in 0:14
loading blobs
[0:19] 1.14%  60.915 MiB/s  1.134 GiB / 99.066 GiB  18300 / 277278 items  ETA 27:26panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x4a8ab4]

goroutine 11 [running]:
github.com/restic/restic.NodeFromFileInfo(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/robert/src/go/src/github.com/restic/restic/node.go:63 +0x84
github.com/restic/restic.(*Archiver).fileWorker(0xc20d642f40, 0xc20d6d7880, 0xc208040fc0, 0xc2080580c0, 0xc208058180)
	/home/robert/src/go/src/github.com/restic/restic/archiver.go:395 +0x2c3
created by github.com/restic/restic.(*Archiver).Snapshot
	/home/robert/src/go/src/github.com/restic/restic/archiver.go:747 +0x9b3
```

I've backupped some other folders before, so there are blobs and trees to load.

The full stacktrace could be viewed here: http://paste.byte.so/raw/19xn2Xbl/resticnill0.txt

**Comment by fd0** [comment]
Thanks for reporting this. I'm looking into the issue.

**Comment by fd0** [comment]
I added more error reporting in the debug log in 3d768e39eabd94b47b34aaebab00678d15cf07a9, turns out a file from the firefox cache vanished between walking the dir and processing the file in the fileworker. The test `test-backup-missing-file.sh` needs to be modified in order to catch this case.
