### ISSUE TITLE
restore panics

### ISSUE THREAD

**Issue by dirk777** [restic/restic#1151]
## Output of `restic version`
restic 0.7.1
compiled with go1.8.3 on darwin/amd64

## How did you start restic exactly? (Include the complete command line)
restic restore 11c28025 -r /Volumes/Backup --target /Users/user/Downloads/

## What backend/server/service did you use?
local storage

## Expected behavior
fulfill restore without panic

## Actual behavior
```
restoring <Snapshot 11c28025 of [/Users/user/Documents] at 2017-08-06 08:42:24.989499082 +0200 CEST by user@Users MacBook> to /Users/user/Downloads/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/pkg/xattr.Set(0xc4202632c0, 0x57, 0xc420bbcea0, 0x19, 0x195dd58, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/xattr/xattr_darwin.go:47 +0x20a
restic.Setxattr(0xc4202632c0, 0x57, 0xc420bbcea0, 0x19, 0x195dd58, 0x0, 0x0, 0x0, 0x0)
	src/restic/node_xattr.go:34 +0x71
restic.Node.restoreExtendedAttributes(0xc420bc6031, 0xb, 0xc420bb7fc8, 0x4, 0x1a4, 0xecdf0a6a0, 0x0, 0x1941220, 0xed117b3e9, 0x0, ...)
	src/restic/node.go:198 +0x103
restic.Node.restoreMetadata(0xc420bc6031, 0xb, 0xc420bb7fc8, 0x4, 0x1a4, 0xecdf0a6a0, 0x0, 0x1941220, 0xed117b3e9, 0x0, ...)
	src/restic/node.go:186 +0x31d
restic.(*Node).CreateAt(0xc42040d2c0, 0x19098c0, 0xc420117700, 0xc4202632c0, 0x57, 0x190dee0, 0xc4201115c0, 0xc420013700, 0x1c, 0xc420266bc0)
	src/restic/node.go:154 +0x344
restic.(*Restorer).restoreNodeTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0xc42040d2c0, 0xc420bba090, 0x2a, 0x7fff5fbffc2a, 0x22, 0xc420013700, 0x0, ...)
	src/restic/restorer.go:91 +0x286
restic.(*Restorer).restoreTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0x7fff5fbffc2a, 0x22, 0xc420bba090, 0x2a, 0x2b8ad8f5b9673bbc, 0xb133a20dd0c60470, 0xf474f3ef3da129d6, ...)
	src/restic/restorer.go:54 +0x83d
restic.(*Restorer).restoreTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0x7fff5fbffc2a, 0x22, 0xc420233240, 0x1d, 0x45251327b69e5d4c, 0xe2c4ae637f30874e, 0x788f2bfa74733458, ...)
	src/restic/restorer.go:66 +0x4f1
restic.(*Restorer).restoreTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0x7fff5fbffc2a, 0x22, 0xc4200e27c0, 0xa, 0x39cf294968fda4a9, 0x33888d0532d33257, 0x28124d3ec00e9ba6, ...)
	src/restic/restorer.go:66 +0x4f1
restic.(*Restorer).restoreTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0x7fff5fbffc2a, 0x22, 0x165ff45, 0x1, 0xcefdf2c34a47223b, 0x6c81432b1e406974, 0xbd7e91089b6dc35c, ...)
	src/restic/restorer.go:66 +0x4f1
restic.(*Restorer).RestoreTo(0xc4204eadb0, 0x19098c0, 0xc420117700, 0x7fff5fbffc2a, 0x22, 0x2178edcfb3c147dc, 0xc4204eadb0)
	src/restic/restorer.go:124 +0x12b
main.runRestore(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff5fbffc2a, 0x22, 0x0, 0x0, ...)
	src/cmds/restic/cmd_restore.go:141 +0x7a6
main.glob..func17(0x193a180, 0xc42011cf00, 0x1, 0x5, 0x0, 0x0)
	src/cmds/restic/cmd_restore.go:23 +0xb5
github.com/spf13/cobra.(*Command).execute(0x193a180, 0xc42011ceb0, 0x5, 0x5, 0x193a180, 0xc42011ceb0)
	src/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1937d60, 0xc4201e6818, 0x1585960, 0xc4201e6840)
	src/github.com/spf13/cobra/command.go:726 +0x339
github.com/spf13/cobra.(*Command).Execute(0x1937d60, 0x25, 0xc42017feb8)
	src/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	src/cmds/restic/main.go:63 +0x268
```

**Comment by fd0** [comment]
Thanks for the report! Hm, this is interesting, the panic occurs in the package we use for extended attributes. I think it's a bug.

**Comment by deviantintegral** [comment]
I was able to replicate this issue years ago, but it looks to be fixed now 🙌 . Not only does a restore of my Downloads directory work, but xattrs look to be preserved (just by running `xattr -l *` in the restored directory). I'm using restic from homebrew, which currently is `restic 0.9.6 compiled with go1.13.4 on darwin/amd64`.

**Comment by rawtaz** [comment]
Well, closing this then, feel free to reopen it if the problem happens again. Thanks for reporting back!
