### ISSUE TITLE
Swift panic: client.PutObject: HTTP Error: 408: 408 Request Time-out

### ISSUE THREAD

**Issue by jayme-github** [restic/restic#1375]
## Output of `restic version`
```
restic 0.7.1
compiled with go1.8.3 on linux/amd64
```

## How did you run restic exactly?
```
export OS_AUTH_URL=https://auth.cloud.ovh.net/v2.0/
export OS_TENANT_ID=xxx
export OS_TENANT_NAME="xxx"
export OS_USERNAME="xxx"
export OS_PASSWORD="xxx"
export OS_REGION_NAME="SBG1"
export RESTIC_REPOSITORY="swift:restic:/"
restic --password-file "$HOME/.restic-password" backup -f \
        --tag "auto" \
        --exclude "stuff" \
        "/foo" \
        "/bar"
```

### Output
```
scan [/foo /bar]
[0:15] 1642 directories, 44327 files, 120.252 GiB
scanned 1642 directories, 44327 files in 0:15
panic: client.PutObject: HTTP Error: 408: 408 Request Time-out

goroutine 70137 [running]:
restic/archiver.(*Archiver).saveChunk(0xc424e00550, 0xc213e0, 0xc42006c338, 0x1620ce, 0x28cbd5, 0x1d044597400000, 0xc43115e000, 0x28cbd5, 0x306000, 0xc420396210, ...)
        src/restic/archiver/archiver.go:165 +0x395
created by restic/archiver.(*Archiver).SaveFile
        src/restic/archiver/archiver.go:239 +0x3a4
```

## What backend/server/service did you use?
Swift 

## Expected behavior
Don't panic.

## Actual behavior
panic

## Steps to reproduce the behavior
Unclear. :-(

## Do you have any idea what may have caused this?
I guess this is caused by connection troubles at my site. Upload is currently very unstable and slow, dropping down to around 5kB/s sometimes (it's like the 90s over here :-)). But request timeouts should probably not lead to panics.

Will run `restic check` when my connection is fixed to see if the repository needs fixes.

**Comment by jayme-github** [comment]
Tonight, same restic call with 0.7.3
```
HTTP Error: 408: 408 Request Time-out
conn.ObjectOpen
github.com/restic/restic/internal/backend/swift.(*beSwift).Load
        src/github.com/restic/restic/internal/backend/swift/swift.go:153
github.com/restic/restic/internal/backend.LoadAll
        src/github.com/restic/restic/internal/backend/utils.go:13
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt
        src/github.com/restic/restic/internal/repository/repository.go:58
github.com/restic/restic/internal/repository.LoadIndexWithDecoder
        src/github.com/restic/restic/internal/repository/index.go:526
github.com/restic/restic/internal/repository.LoadIndex
        src/github.com/restic/restic/internal/repository/repository.go:353
github.com/restic/restic/internal/repository.(*Repository).LoadIndex.func1
        src/github.com/restic/restic/internal/repository/repository.go:321
github.com/restic/restic/internal/repository.ParallelWorkFuncParseID.func1
        src/github.com/restic/restic/internal/repository/parallel.go:74
github.com/restic/restic/internal/repository.FilesInParallel.func1
        src/github.com/restic/restic/internal/repository/parallel.go:39
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
also, the following messages were logged by a library:
2017/10/23 02:00:19 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
2017/10/23 02:00:19 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Time-out\r\nCache-Control: no-cache\r\nConnection: close\r\nContent-Type: text/html\r\n\r\n<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n"; err=<nil>
```

**Comment by fd0** [comment]
That's a known problem with OVH, they're using nginx in front of their Swift cluster, @rledisez explained that a while back in https://github.com/restic/restic/pull/648#issuecomment-259377066

Ideally, the Swift library handles this, but since it doesn't, we've added generic retry code in the latest master branch. Maybe you could try that?

If you don't want to compile your own binary, you can download beta releases here: https://beta.restic.net/?sort=time&order=desc

**Comment by jayme-github** [comment]
I remember the comment about OHV's setup. Just thought there could be a better error handling than panic.

I'm happy to try the current master to see how it behaves in this desperate situation. :-)

**Comment by jayme-github** [comment]
The output of v0.7.3-221 looks like:

```
scan[/foo /bar]
[0:02] 1659 directories, 44429 files, 120.561 GiB
scanned 1659 directories, 44429 files in 0:02
Save(<data/c5e6040a94>) returned error, retrying after 341.987319ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/ce3742e28d>) returned error, retrying after 577.163896ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 454.707679ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/c5e6040a94>) returned error, retrying after 1.080664837s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 567.233009ms: client.PutObject: Timeout when reading or writing data
Save(<data/ce3742e28d>) returned error, retrying after 698.484887ms: client.PutObject: Timeout when reading or writing data
Save(<data/c5e6040a94>) returned error, retrying after 1.224943597s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/ce3742e28d>) returned error, retrying after 594.100955ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/c5e6040a94>) returned error, retrying after 1.544204907s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 660.730272ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/c5e6040a94>) returned error, retrying after 1.303861986s: client.PutObject: Timeout when reading or writing data
Save(<data/c5e6040a94>) returned error, retrying after 1.941734707s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/ce3742e28d>) returned error, retrying after 1.749148343s: client.PutObject: Timeout when reading or writing data
Save(<data/c5e6040a94>) returned error, retrying after 6.821893771s: client.PutObject: Timeout when reading or writing data
Save(<data/b5638f7d81>) returned error, retrying after 1.7634007s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/ce3742e28d>) returned error, retrying after 1.815939997s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 3.397140019s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 3.526515387s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/c5e6040a94>) returned error, retrying after 7.204401891s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/f7e45cdcf6>) returned error, retrying after 357.54035ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/b5638f7d81>) returned error, retrying after 4.829192101s: client.PutObject: Timeout when reading or writing data
Save(<data/ce3742e28d>) returned error, retrying after 5.63943381s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/0a657da329>) returned error, retrying after 715.002171ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/c5e6040a94>) returned error, retrying after 13.191005305s: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/490804fc4c>) returned error, retrying after 383.575453ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/9586d5187e>) returned error, retrying after 642.154069ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/ca0136925d>) returned error, retrying after 546.962213ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/a73e0271f7>) returned error, retrying after 666.353298ms: client.PutObject: Timeout when reading or writing data
Save(<data/9c80ee8395>) returned error, retrying after 384.592615ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/e231d4cc5e>) returned error, retrying after 664.230757ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/27b923faa1>) returned error, retrying after 573.382227ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/42d3136b53>) returned error, retrying after 614.810534ms: client.PutObject: HTTP Error: 408: 408 Request Timeout
Save(<data/f7e45cdcf6>) returned error, retrying after 913.765827ms: client.PutObject: HTTP Error: 408: 408 Request Timeout

error while saving data to the repo: HTTP Error: 408: 408 Request Timeout
client.PutObject
github.com/restic/restic/internal/backend/swift.(*beSwift).Save
        src/github.com/restic/restic/internal/backend/swift/swift.go:193
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        src/github.com/restic/restic/internal/backend/backend_retry.go:68
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        src/github.com/restic/restic/internal/backend/backend_retry.go:43
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        src/github.com/restic/restic/internal/backend/backend_retry.go:69
github.com/restic/restic/internal/cache.(*Backend).Save
        src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:250
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:634
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197
panic: client.PutObject: HTTP Error: 408: 408 Request Timeout

goroutine 3320 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc425da7d10, 0xe05480, 0xc4200123b8, 0x8af5b2, 0x1d585e, 0x14ba850b000000, 0xc429db4000, 0x1d585e, 0x1ea000, 0xc42064def0, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x412
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x38c
```

**Comment by fd0** [comment]
Hmm, that's odd.

**Comment by breml** [comment]
I observe the same problem with hubic (OVH). I use the a version of restic I built on my own, which is based on commit https://github.com/restic/restic/commit/0247fe01c0a98df4d9d23331e57ef6b7a6c3333d (3 days old) which includes the hubic backend from https://github.com/ifedorenko/restic/commit/3e1a766d9afc6d7933dddf8230b978a7fec183b0.

```
restic 0.8.0 (v0.8.0-81-g3e1a766)
compiled with go1.9 on linux/amd64
```

I get the following errors:

```
error while saving data to the repo: Timeout when reading or writing data
client.PutObject
github.com/restic/restic/internal/backend/swift.(*beSwift).Save
        src/github.com/restic/restic/internal/backend/swift/swift.go:189
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        src/github.com/restic/restic/internal/backend/backend_retry.go:71
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        src/github.com/restic/restic/internal/backend/backend_retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        src/github.com/restic/restic/internal/backend/backend_retry.go:65
github.com/restic/restic/internal/cache.(*Backend).Save
        src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:253
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:618
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:106
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:171
runtime.goexit
        /home/lubr/.gvm/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337
panic: client.PutObject: Timeout when reading or writing data

goroutine 10274 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc420103800, 0xe417a0, 0xc420057300, 0x0, 0x2d2cdf, 0x54fece9d00000, 0xc42f2ae000, 0x2d2cdf, 0x3c0000, 0xc42008e370, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:176 +0x41b
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:250 +0x3d0
```

Before this panic I also get quite some of the above mentioned error messages like `Timeout when reading or writing data` and `HTTP Error: 408: 408 Request Timeout`, sometimes even `HTTP Error: 503: 503 Service Unavailable`.

**Comment by fd0** [comment]
@breml Does restic retry the backend requests?

**Comment by breml** [comment]
After the error messages like `Timeout when reading or writing data`, `HTTP Error: 408: 408 Request Timeout` and `HTTP Error: 503: 503 Service Unavailable` it looks like restic is retrying the backend requests, because the progress moves forward. But then later, restic fails with the above mentioned panic. In general the output of restic in my case looks the same as in https://github.com/restic/restic/issues/1375#issuecomment-340385183.

**Comment by fd0** [comment]
From my point of view it looks like a backend problem. We can retry in restic (we already do that), and we could retry some more, but in general I don't have any idea on how to improve the situation. Any ideas?

**Comment by breml** [comment]
For me, to fail with a panic in general looks like a bad solution. I agree, that if there is a problem with the backend, there is not much for restic to do other to quit. But this should be done in a controlled manner with a proper error message and not with a panic.

Additionally I have the following ideas:

* Maybe the count (or the time) for the retries could be configurable via a command line flag
* Maybe there is a way for restic to keep the state of the backup (what has already been backuped and where did the last run fail) such that restic could try to continue at the last position, which was known to be correct (transmitted successfully).

**Comment by fd0** [comment]
> For me, to fail with a panic in general looks like a bad solution. I agree, that if there is a problem with the backend, there is not much for restic to do other to quit. But this should be done in a controlled manner with a proper error message and not with a panic.

For the record: I agree. It's not strictly a `panic()` (that'd look slightly different), but it's not a good user experience. I'll take care of that in #1494.

> Maybe there is a way for restic to keep the state of the backup (what has already been backuped and where did the last run fail) such that restic could try to continue at the last position, which was known to be correct (transmitted successfully).

We have that, but the state is held in the repo. When the connection to the backend fails, the state cannot be updated any more. I have plans to add local state (in the cache directory), keep some kind of "transaction log" that lists the pack files that have been uploaded successfully.

**Comment by breml** [comment]
@fd0 thanks for the feedback, this sounds promising. nevertheless due to the slow upload speed of hubic I decided to use backblaze b2. there i do not observe any such problems.

**Comment by fd0** [comment]
I'm closing this issue for now, it is a backend issue. The "panic" will be taken care of in #1494. Please feel free to add further comments. Thanks!
