### ISSUE TITLE
write /tmp/restic-temp-pack-399360320: no space left on device

### ISSUE THREAD

**Issue by feutl** [restic/restic#1440]
I am using restic on a QNAP and while started my initial backup of around 3 TB of data to an USB connected HDD it failed with the following message

```
# restic -r /share/ColdBackup/ backup /share/Backup/
enter password for repository:
scan [/share/Backup/]
scanned 838804 directories, 5090211 files in 26:24
[2:21:49] 4.93%  15.638 MiB/s  129.964 GiB / 2.575 TiB  887479 / 5929015 items  0 errors  ETA 45:36:06
error while saving data to the repo: write /tmp/restic-temp-pack-399360320: no space left on device
Write
github.com/restic/restic/internal/pack.(*Packer).Add
        src/github.com/restic/restic/internal/pack/pack.go:51
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:189
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:529
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: Write: write /tmp/restic-temp-pack-399360320: no space left on device

goroutine 850837 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc4218548c0, 0xdff020, 0xc420014108, 0x1aa295a8, 0x80000, 0x0, 0xc4385dc000, 0x80000, 0x80000, 0xc42008c370, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x41b
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d0
```

Is there a way to specify a different /tmp/ location or make a cleanup more often. The /tmp/ drive on a QNAP NAS is around 32 or 64 MB only, because it is kept in RAM.

**Comment by fd0** [comment]
Yes, and it's documented in the manual: http://restic.readthedocs.io/en/latest/manual_rest.html?highlight=TMPDIR#temporary-files

Since this is a question (which has been answered) I'm closing this issue for now. Please feel free to add further comments.
