### ISSUE TITLE
Panic during Save

### ISSUE THREAD

**Issue by akalin** [restic/restic#1500]
## Output of `restic version`

```
restic 0.8.0
compiled with go1.9 on freebsd/amd64
```

## How did you run restic exactly?

I ran a script which basically does:

```
export B2_ACCOUNT_ID=...
export B2_ACCOUNT_KEY=...
export RESTIC_PASSWORD_FILE=...
export RESTIC_REPOSITORY=b2:...:...
exec ./restic_0.8.0_freebsd_amd64 backup /mnt/archives
```

Here's the output:

```
password is correct
using parent snapshot 1a7e9287
scan [/mnt/archives]
scanned 1526 directories, 176854 files in 0:17
^R2:28:20] 58.78%  94.978 MiB/s  825.489 GiB / 1.371 TiB  104249... ETA 1:44:01
    [43:39:14] 69.08%  6.321 MiB/s  970.075 GiB / 1.371 TiB  12275... ETA 19:32:^R
   [43:39:14] 69.08%  6.321 MiB/s  970.077 GiB / 1.371 TiB  12275... ETA 19:32:3^R3:39:14] 69.08%  6.321 MiB/s  970.082 GiB / 1.371 TiB  12275... ETA 19:32:37
  [43:39:17] 69.08%  6.321 MiB/s  970.082 GiB / 1.371 TiB  12275... ETA 19:32:37[55:41:00] 72.29%  5.186 MiB/s  1015.265 GiB / 1.371 TiB  1285... ETA 21:20:28
error while saving data to the repo: b2_upload_file: 405:
Close
github.com/restic/restic/internal/backend/b2.(*b2Backend).Save
        src/github.com/restic/restic/internal/backend/b2/b2.go:214
github.com/restic/restic/internal/backend.(*RetryBackend).Save.func1
        src/github.com/restic/restic/internal/backend/backend_retry.go:68
github.com/restic/restic/vendor/github.com/cenkalti/backoff.RetryNotify
        src/github.com/restic/restic/vendor/github.com/cenkalti/backoff/retry.go:37
github.com/restic/restic/internal/backend.(*RetryBackend).retry
        src/github.com/restic/restic/internal/backend/backend_retry.go:36
github.com/restic/restic/internal/backend.(*RetryBackend).Save
        src/github.com/restic/restic/internal/backend/backend_retry.go:62
github.com/restic/restic/internal/cache.(*Backend).Save
        src/github.com/restic/restic/internal/cache/backend.go:55
github.com/restic/restic/internal/repository.(*Repository).savePacker
        src/github.com/restic/restic/internal/repository/packer_manager.go:107
github.com/restic/restic/internal/repository.(*Repository).SaveAndEncrypt
        src/github.com/restic/restic/internal/repository/repository.go:253
github.com/restic/restic/internal/repository.(*Repository).SaveBlob
        src/github.com/restic/restic/internal/repository/repository.go:618
github.com/restic/restic/internal/archiver.(*Archiver).Save
        src/github.com/restic/restic/internal/archiver/archiver.go:104
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk
        src/github.com/restic/restic/internal/archiver/archiver.go:161
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2337
panic: Close: b2_upload_file: 405:

goroutine 997056 [running]:
github.com/restic/restic/internal/archiver.(*Archiver).saveChunk(0xc42008a0f0, 0xe3e9c0, 0xc420080058, 0x302c29, 0x39633b, 0x1eec368bc00000, 0xc4484b8000, 0x39633b, 0x3c4000, 0xc428f649a0, ...)
        src/github.com/restic/restic/internal/archiver/archiver.go:166 +0x41b
created by github.com/restic/restic/internal/archiver.(*Archiver).SaveFile
        src/github.com/restic/restic/internal/archiver/archiver.go:240 +0x3d0

```

## What backend/server/service did you use to store the repository?

Backblaze's B2.

## Expected behavior

No panic.

## Actual behavior

Panic, as described above.

## Steps to reproduce the behavior

Not sure if there's an easy repro, probably triggered by B2 connection drops. Previous connection drops have just terminated restic normally, though.

## Do you have any idea what may have caused this?

B2 connection flakiness.

## Do you have an idea how to solve the issue?

No.

## Did restic help you or made you happy in any way?

Restic is great otherwise! I'm glad it exists, and thank you for your hard work. :)

**Comment by fd0** [comment]
Thanks for taking the time to report this! Errors are not yet handled sufficiently in 0.8.0, and backblaze sometimes just closes the connection or so. We're working on it.

Upgrade to 0.8.1, and restic will retry the requests (but still panic if the request did not succeed after some time). I'm going to close this issue for now (we're aware of the issue), please leave feedback whether it works with 0.8.1!
