### ISSUE TITLE
Crashes when locks directory is missing

### ISSUE THREAD

**Issue by alphapapa** [restic/restic#1532]
When the `locks/` directory is missing from a repository, Restic crashes instead of creating the directory.  This may happen if stale lockfiles exist and the user deletes the directory to clear them.
```
restic 0.8.1
compiled with go1.9 on linux/amd64
```

```
password is correct
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x74ff2f]

goroutine 13 [running]:
github.com/restic/restic/internal/backend/local.(*Local).List.func1.1(0xc42001a420, 0x29, 0x0, 0x0, 0xe319e0, 0xc42007d7a0, 0x0, 0x29)
        src/github.com/restic/restic/internal/backend/local/local.go:257 +0x6f
path/filepath.Walk(0xc42001a420, 0x29, 0xc420140040, 0xc42002d701, 0xc420140040)
        /usr/local/go/src/path/filepath/path.go:401 +0x76
github.com/restic/restic/internal/fs.Walk(0xc42001a420, 0x29, 0xc420140040, 0xc42001a420, 0x29)
        src/github.com/restic/restic/internal/fs/file.go:113 +0x3f
github.com/restic/restic/internal/backend/local.(*Local).List.func1(0xc42013e4e0, 0xc42019eb40, 0xae793f, 0x4, 0xe387a0, 0xc420012168)
        src/github.com/restic/restic/internal/backend/local/local.go:256 +0x141
created by github.com/restic/restic/internal/backend/local.(*Local).List
        src/github.com/restic/restic/internal/backend/local/local.go:252 +0x111
```

Thanks.

**Comment by fd0** [comment]
This has just yesterday been resolved in https://github.com/restic/restic/pull/1529, so I'm closing this issue :)

**Comment by fd0** [comment]
Ah, FYI, you should not remove the lock files manually, but rather use `restic unlock` on the repo to remove stale lock files.

**Comment by alphapapa** [comment]
Thanks.
