### ISSUE TITLE
backup crashes with "invalid memory address or nil dereference"

### ISSUE THREAD

**Issue by timri** [restic/restic#1755]
## Output of `restic version`
restic 0.8.3 (v0.8.3-201-g4e343250-dirty) compiled with go1.10.1 on windows/amd64
(panic occured at current master (26757ae2e53e17b75f98c9bc9c74d343ea226b6d), I used "git bisect" to find the responsible commit,
restic was (cross-)compiled using a golang-docker-container:

```
$ winpty docker run -it --rm -v $PWD:/src -w="/src" golang go run build.go --goos windows --goarch amd64 -v
build: detected Go version Go 1.10.1
build: adding build-tag release
build: build tags: [release]
build: create GOPATH at /tmp/restic-build-209405661
build: copy contents of /src to /tmp/restic-build-209405661/github.com/restic/restic
build: copy contents of /src/vendor to /tmp/restic-build-209405661/github.com/restic/restic/vendor
build: git version is v0.8.3-201-g4e343250-dirty
build: version from file 'VERSION' is "0.8.3", version from git "v0.8.3-201-g4e343250-dirty"
build: ldflags: -s -w -X "main.version=0.8.3 (v0.8.3-201-g4e343250-dirty)"
build: Go version is at least 1.10, using new syntax for -gcflags
build: go [build -asmflags all=-trimpath=/tmp/restic-build-209405661 -gcflags all=-trimpath=/tmp/restic-build-209405661 -tags release -ldflags -s -w -X "main.version=0.8.3 (v0.8.3-201-g4e343250-dirty)" -o /src/
restic.exe github.com/restic/restic/cmd/restic]
build: remove /tmp/restic-build-209405661
```

## How did you run restic exactly?
from cygwin:
```
Tim@Tim-PC MINGW64 /d/vagrant/restic ((4e34325...)|BISECTING)
$ winpty ./restic --verbose=5 --exclude-file=d:/restic/excludes.txt backup "c:/Users/Tim/AppData/Local/Google/Chrome/User Data/Default" -f
open repository
repository 8f256a7b opened successfully, password is correct
lock repository
load index files
start scan
start backup
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_0, saved in 0.016s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_1, saved in 0.014s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_2, saved in 0.015s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/index, saved in 0.010s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Index, saved in 0.005s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Index-journal, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_3, saved in 0.015s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Bookmarks, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Bookmarks.bak, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Cookies-journal, saved in 0.000s (0 B added)
error: OpenFile: open \\?\c:\Users\Tim\AppData\Local\Google\Chrome\User Data\Default\Current Session: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
error: OpenFile: open \\?\c:\Users\Tim\AppData\Local\Google\Chrome\User Data\Default\Current Tabs: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/000003.log, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/CURRENT, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/LOG, saved in 0.002s (0 B added)

                                                                  panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x76f453]

goroutine 86 [running]:
github.com/restic/restic/internal/archiver.(*TreeSaver).save(0xc04211b680, 0xb94800, 0xc048c96000, 0xc0420214a0, 0x53, 0xc0421b68c0, 0xc047a5d500, 0x6, 0x6, 0x0, ...)
        src/github.com/restic/restic/internal/archiver/tree_saver.go:107 +0x3b3
github.com/restic/restic/internal/archiver.(*TreeSaver).worker(0xc04211b680, 0xb94800, 0xc048c96000, 0xc04211b698, 0xc042020240)
        src/github.com/restic/restic/internal/archiver/tree_saver.go:150 +0x117
created by github.com/restic/restic/internal/archiver.NewTreeSaver
        src/github.com/restic/restic/internal/archiver/tree_saver.go:65 +0x109

Tim@Tim-PC MINGW64 /d/vagrant/restic ((4e34325...)|BISECTING)
$ git bisect bad
4e34325035d23df6ec302eb50159d863dc887db2 is the first bad commit
commit 4e34325035d23df6ec302eb50159d863dc887db2
Author: Alexander Neumann <alexander@bumpern.de>
Date:   Mon Apr 30 15:13:03 2018 +0200

    archiver: Process dirs concurrently

:040000 040000 95da3927af9e9878676a15cfc9f8b070ce460ddd 2cf6e7670eb2416351cad604d43a8aece724fad1 M      internal
$ env
HOMEPATH=\Users\Tim
HOSTNAME=Tim-PC
SHELL=/usr/bin/bash
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
COMPOSE_CONVERT_WINDOWS_PATHS=true
WINDIR=C:\Windows
TMPDIR=/tmp
RESTIC_PASSWORD=xxxx
OS=Windows_NT
USERNAME=Tim
RESTIC_REPOSITORY=f:/Backup/restic
PROCESSOR_LEVEL=6
PWD=/d/vagrant/restic
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\Tim
PROCESSOR_ARCHITECTURE=AMD64
TMP=/tmp
$ cat /d/restic/excludes.txt
Temp
tmp
*.tmp
Documents/Eigene Bilder
Documents/Eigene Musik
Documents/Eigene Videos
Google/Chrome/User Data/*/Cache
```

(the problem occurred often at different files, but always in the Chrome-Profile. I first found it when backing up the whole folder "C:/Users/Tim")

## What backend/server/service did you use to store the repository?
Local disk (USB3)

## Expected behavior
restic does a snapshot

## Actual behavior

restic panics
```
$ winpty ./restic --verbose=5 --exclude-file=d:/restic/excludes.txt backup "c:/Users/Tim/AppData/Local/Google/Chrome/User Data/Default"
open repository
repository 8f256a7b opened successfully, password is correct
lock repository
load index files
start scan
start backup
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_1, saved in 0.013s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_0, saved in 0.013s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_2, saved in 0.016s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/data_3, saved in 0.008s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Index, saved in 0.002s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Index-journal, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Application Cache/Cache/index, saved in 0.008s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Bookmarks, saved in 0.000s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Bookmarks.bak, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Cookies-journal, saved in 0.000s (0 B added)
error: OpenFile: open \\?\c:\Users\Tim\AppData\Local\Google\Chrome\User Data\Default\Current Session: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
error: OpenFile: open \\?\c:\Users\Tim\AppData\Local\Google\Chrome\User Data\Default\Current Tabs: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/000003.log, saved in 0.001s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/CURRENT, saved in 0.000s (0 B added)
new       /c/Users/Tim/AppData/Local/Google/Chrome/User Data/Default/Download Service/EntryDB/LOG, saved in 0.000s (0 B added)
[0:01] 69.58%  10 files 8.857 MiB, total 61 files 12.729 MiB, 1 errors
                                                                  panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x76f453]

goroutine 98 [running]:
github.com/restic/restic/internal/archiver.(*TreeSaver).save(0xc044454c90, 0xb94800, 0xc047d3d940, 0xc04537c1e0, 0x53, 0xc0421be280, 0xc044cd5500, 0x6, 0x6, 0x3332663066363264, ...)
        src/github.com/restic/restic/internal/archiver/tree_saver.go:107 +0x3b3
github.com/restic/restic/internal/archiver.(*TreeSaver).worker(0xc044454c90, 0xb94800, 0xc047d3d940, 0xc044454ca8, 0xc0420209c0)
        src/github.com/restic/restic/internal/archiver/tree_saver.go:150 +0x117
created by github.com/restic/restic/internal/archiver.NewTreeSaver
        src/github.com/restic/restic/internal/archiver/tree_saver.go:65 +0x109
```

## Steps to reproduce the behavior

I am unsure, how to reproduce this, when backing up my whole user-profile, it ran for quite some time.
I repeated the backup excluding the google-chrome profile, which worked without problems:
```
Tim@Tim-PC MINGW64 /d/vagrant/restic ((4e34325...)|BISECTING)
$ winpty ./restic --verbose=5 --exclude-file=d:/restic/excludes.txt backup "c:/Users/Tim"  --exclude "Google/Chrome/User Data"
[....]
new       /c/Users/, saved in 629.780s (0 B added, 298 B metadata)
new       /c/, saved in 629.780s (0 B added, 299 B metadata)
processed 57.013 GiB in 10:33

Files:       272336 new,     0 changed,     0 unmodified
Dirs:            2 new,     0 changed,     0 unmodified
Data Blobs:   1027 new
Tree Blobs:      3 new
Added:      643.353 MiB

snapshot 02b1e913 saved
$
```
## Do you have any idea what may have caused this?

According to git bisect, commit 4e34325035d23df6ec302eb50159d863dc887db2
together with my chrome-profile (while chrome is running, so most files are locked)
(I will retry that after exiting chrome, but I am currently writing this report in chrome ;-) )
## Did restic help you or made you happy in any way?

I am currently evaluating restic for my backups, so far it looks like a great project,
I actually tried the current master to have rclone-support (without manually starting rclone serve)
(and the --verbose option ;-) )

**Comment by fd0** [comment]
Hey, thanks a lot for the comprehensive report! I'll have a look later.

**Comment by fd0** [comment]
Would you mind testing if it still occurs with the following patch?

```diff
diff --git a/internal/archiver/tree_saver.go b/internal/archiver/tree_saver.go
index 6428c628..db04dfe8 100644
--- a/internal/archiver/tree_saver.go
+++ b/internal/archiver/tree_saver.go
@@ -104,7 +104,7 @@ func (s *TreeSaver) save(ctx context.Context, snPath string, node *restic.Node,
 
                // return the error if it wasn't ignored
                if fn.err != nil {
-                       debug.Log("err for %v: %v", fn.node.Name, fn.err)
+                       debug.Log("err for %v: %v", fn.snPath, fn.err)
                        fn.err = s.errFn(fn.target, fn.fi, fn.err)
                        if fn.err == nil {
                                // ignore error
```

You can also just remove line 107 from `tree_saver.go`, which is just a debug call...

**Comment by askielboe** [comment]
Had the same issue on Windows and can confirm that changing the debug log, as per the diff above, solves the problem for me. Thanks!

**Comment by fbkopp** [comment]
Same issue and diff above solved the problem.

**Comment by timri** [comment]
The diff solved my problem, too. (As did closing chrome, for completeness)
