### ISSUE TITLE
Backup with trailing slash and --one-file-system does not complete

### ISSUE THREAD

**Issue by moritzdietz** [restic/restic#1775]
## Output of `restic version`
```
moritz@ ☁️  vps in ~
$ ./restic version
debug enabled
restic 0.8.3 (v0.8.3-243-gfcfa6f03) compiled with go1.10.2 on linux/amd64
moritz@ ☁️  vps in ~
$
```
## How did you run restic exactly?

```
moritz@ ☁️  vps in ~
$ ./restic \
→     -r b2:restic-vps-01:/ \
→     -p /home/moritz/.restic/passphrase \
→     backup /home/moritz/ \
→     --exclude /home/moritz/.restic* \
→     --one-file-system \
→     --tag 'systemd /home/moritz' \
→     -o b2.connections=20
```

## What backend/server/service did you use to store the repository?
B2 - the B2 environment variables are set and are working.

## Expected behavior
restic backs up the directory `/home/moritz/` with the exclusion of `/home/moritz/.restic*`.

## Actual behavior
After running the command above the only output you get is this
```
moritz@ ☁️  vps in ~
$ ./restic \
→     -r b2:restic-vps-01:/ \
→     -p /home/moritz/.restic/passphrase \
→     backup /home/moritz/ \
→     --exclude /home/moritz/.restic* \
→     --one-file-system \
→     --tag 'systemd /home/moritz' \
→     -o b2.connections=20
debug log file /tmp/restic-debug.log
debug enabled
repository 75013bf5 opened successfully, password is correct
```
Then it sits there idling and when you check the CPU usage you can see it spike and use 100% (on this VPS I am running restic on).

As per https://restic.readthedocs.io/en/latest/040_backup.html#including-and-excluding-files
`A trailing / is ignored, a leading / anchors the pattern at the root directory. This means, /bin matches /bin/bash but does not match /usr/bin/restic.`
This seems to be a regression.

debug.log (I can provide the full file if needed):
```
[...]
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/d5c68a77a9>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id d681fd930d7f3e48fd9e603b3a788d77d5abe4daab39e6ba02ff3d8d0c93e17b
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/d681fd930d>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/d681fd930d>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id df502ed865bf2d4b375c84aae8b5b960025b573d24e78ba6374359a6eb4bc171
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/df502ed865>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/df502ed865>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id e29526487b4979ac7a74904ef14ab444aa2f54fa3240d88848be932c6b903702
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/e29526487b>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/e29526487b>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id e2e50b35a5167918bf85bfc2c0dac3e59575dce3b34e4984b751d64adde4b543
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/e2e50b35a5>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/e2e50b35a5>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id e3bfbc22f6d1074569f44657d8a00f31e16eb8cf01c8c14451c94f1bf315d88f
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/e3bfbc22f6>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/e3bfbc22f6>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id e7a13d23d547f8333e42fca68faebf9372a97a0b9bc0f0a45085fdbc9450806a
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/e7a13d23d5>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/e7a13d23d5>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id ec42394d3cc8aebf1d39706a7e42e57a268b3eb1b2a71f93d25c46e6a709f225
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/ec42394d3c>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/ec42394d3c>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id f0351447be9613a44d752f10674f40640d9cb1f27e0d61b67ecccc4983a52906
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/f0351447be>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/f0351447be>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id f31b3533522b61c720c20574eacaa75103e7377e5436b1a7201fcfcd238275a4
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/f31b353352>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/f31b353352>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id f3c3e9122d68ba203049be7448dc00e1cc1649123232300cd4154c3a80a440f0
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/f3c3e9122d>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/f3c3e9122d>
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id f4d307ca825fddaa02d53e42ddc397c091185268824dc1ab7ab1042681688d1b
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/f4d307ca82>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/f4d307ca82>
2018/05/11 20:03:22 archiver/archiver.go:649    archiver.resolveRelativeTargets 1       targets before resolving: [/home/moritz/]
2018/05/11 20:03:22 archiver/archiver.go:670    archiver.resolveRelativeTargets 1       targets after resolving: [/home/moritz]
2018/05/11 20:03:22 archiver/tree.go:233        archiver.NewTree        1       targets: [/home/moritz]
2018/05/11 20:03:22 archiver/tree.go:252        archiver.NewTree        1       result:
/home, root "/", meta "/home"
    /moritz, src "/home/moritz"

2018/05/11 20:03:22 archiver/file_saver.go:72   archiver.NewFileSaver   1       new file saver with 2 file workers and 1 blob workers
2018/05/11 20:03:22 archiver/archiver.go:744    archiver.(*Archiver).Snapshot   1       starting snapshot
2018/05/11 20:03:22 archiver/archiver.go:689    archiver.(*Archiver).loadParentTree     1       load parent snapshot 60170643b7f6e7abaf6f4e4f0715142d99da8247aa491a92af113cda4962964a
2018/05/11 20:03:22 repository/repository.go:73 repository.(*Repository).LoadAndDecrypt 1       load snapshot with id 60170643b7f6e7abaf6f4e4f0715142d99da8247aa491a92af113cda4962964a
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<snapshot/60170643b7>, 0, 0) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <snapshot/60170643b7>
2018/05/11 20:03:22 archiver/archiver.go:701    archiver.(*Archiver).loadParentTree     1       load parent tree 1f5f540dc66250c867232fed77af54aeef3842b3630bd3865f1484ad759f3e8f
2018/05/11 20:03:22 repository/repository.go:650        repository.(*Repository).LoadTree       1       load tree 1f5f540dc66250c867232fed77af54aeef3842b3630bd3865f1484ad759f3e8f
2018/05/11 20:03:22 repository/repository.go:657        repository.(*Repository).LoadTree       1       size is 370, create buffer
2018/05/11 20:03:22 repository/repository.go:119        repository.(*Repository).loadBlob       1       load tree with id 1f5f540dc66250c867232fed77af54aeef3842b3630bd3865f1484ad759f3e8f (buf len 370, cap 402)
2018/05/11 20:03:22 repository/repository.go:133        repository.(*Repository).loadBlob       1       blob tree/1f5f540dc66250c867232fed77af54aeef3842b3630bd3865f1484ad759f3e8f found: <Blob (tree) 1f5f540d, offset 1650098, length 402>
2018/05/11 20:03:22 restic/readerat.go:27       restic.ReadAt   1       ReadAt(<data/495e77c62d>) at 1650098, len 402
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<data/495e77c62d>, 402, 1650098) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <data/495e77c62d>
2018/05/11 20:03:22 restic/readerat.go:38       restic.ReadAt   1       ReadAt(<data/495e77c62d>) ReadFull returned 402 bytes
2018/05/11 20:03:22 archiver/archiver.go:474    archiver.(*Archiver).SaveTree   1       / (1 nodes), parent Tree<1 nodes>
2018/05/11 20:03:22 repository/repository.go:650        repository.(*Repository).LoadTree       1       load tree e0989ac2e2b5ea9d9ee33c5777ff2a44910d132c3afb212fa17b297b1f02f127
2018/05/11 20:03:22 repository/repository.go:657        repository.(*Repository).LoadTree       1       size is 381, create buffer
2018/05/11 20:03:22 repository/repository.go:119        repository.(*Repository).loadBlob       1       load tree with id e0989ac2e2b5ea9d9ee33c5777ff2a44910d132c3afb212fa17b297b1f02f127 (buf len 381, cap 413)
2018/05/11 20:03:22 repository/repository.go:133        repository.(*Repository).loadBlob       1       blob tree/e0989ac2e2b5ea9d9ee33c5777ff2a44910d132c3afb212fa17b297b1f02f127 found: <Blob (tree) e0989ac2, offset 1649685, length 413>
2018/05/11 20:03:22 restic/readerat.go:27       restic.ReadAt   1       ReadAt(<data/495e77c62d>) at 1649685, len 413
2018/05/11 20:03:22 cache/backend.go:158        cache.(*Backend).Load   1       Load(<data/495e77c62d>, 413, 1649685) from cache
2018/05/11 20:03:22 cache/file.go:44    cache.(*Cache).Load     1       Load from cache: <data/495e77c62d>
2018/05/11 20:03:22 restic/readerat.go:38       restic.ReadAt   1       ReadAt(<data/495e77c62d>) ReadFull returned 413 bytes
2018/05/11 20:03:22 archiver/archiver.go:474    archiver.(*Archiver).SaveTree   1       /home (1 nodes), parent Tree<1 nodes>
2018/05/11 20:03:22 archiver/archiver.go:307    archiver.(*Archiver).Save       1       /home/moritz target "/home/moritz", previous drwxr-----  1000  1000      0 2018-05-11 19:54:43.617639355 +0200 CEST moritz
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /home/moritz
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /home
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
2018/05/11 20:03:22 restic/exclude.go:226       main.rejectByDevice.func1       1       item /home/moritz, test dir /
[...]
```
strace of the command:
![image](https://user-images.githubusercontent.com/7935536/39940457-a2fcf978-5559-11e8-8224-c03b9b9883b6.png)

## Steps to reproduce the behavior

Running:
```
moritz@ ☁️  vps in ~
$ ./restic \
→     -r b2:restic-vps-01:/ \
→     -p /home/moritz/.restic/passphrase \
→     backup /home/moritz/ \
→     --exclude /home/moritz/.restic* \
→     --one-file-system \
→     --tag 'systemd /home/moritz' \
→     -o b2.connections=20
```
will cause the error.

Running:
```
moritz@ ☁️  vps in ~
$ ./restic \
→     -r b2:restic-vps-01:/ \
→     -p /home/moritz/.restic/passphrase \
→     backup /home/moritz \
→     --exclude /home/moritz/.restic* \
→     --one-file-system \
→     --tag 'systemd /home/moritz' \
→     -o b2.connections=20
```
will work just fine.

**Comment by fd0** [comment]
I can reproduce it.

**Comment by McKael** [comment]
I'm afraid this breaks some backups:

```
% restic backup --one-file-system --verbose /
debug log file /tmp/restic-debug.log
debug enabled
open repository
repository 8e5f6b31 opened successfully, password is correct
lock repository
load index files
start scan on [/]
start backup on [/]
panic: item /, device id 2082 not found, allowedDevs: map[/:2082]

goroutine 34 [running]:
main.rejectByDevice.func1(0x7fff9cace2bd, 0x1, 0xc58960, 0xc4202e0000, 0xc58960)
        src/github.com/restic/restic/cmd/restic/exclude.go:250 +0x677
main.runBackup.func3(0x7fff9cace2bd, 0x1, 0xc58960, 0xc4202e0000, 0xc4202e0000)
        src/github.com/restic/restic/cmd/restic/cmd_backup.go:398 +0x88
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc42015f3b0, 0xc568c0, 0xc42006b1c0, 0x0, 0x0, 0x0, 0x0, 0x7fff9cace2bd, 0x1, 0xbf4bb8, .
..)
        src/github.com/restic/restic/internal/archiver/scanner.go:81 +0x25e
github.com/restic/restic/internal/archiver.(*Scanner).Scan(0xc42015f3b0, 0xc568c0, 0xc42006b1c0, 0xc4200617b0, 0x1, 0x1, 0x0, 0x0)
        src/github.com/restic/restic/internal/archiver/scanner.go:51 +0x168
main.runBackup.func4(0x0, 0x0)
        src/github.com/restic/restic/cmd/restic/cmd_backup.go:431 +0x9a
github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc42001cbe0, 0xc42026a280)
        src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by github.com/restic/restic/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
        src/github.com/restic/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb9
```

I'll add do a small PR.

**Comment by fd0** [comment]
Thanks for the feedback!
