### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by HaleTom** [restic/restic#2374]
Output of `restic version`
--------------------------
`restic 0.9.5 compiled with go1.12.4 on windows/386`

How did you run restic exactly?
-------------------------------
```
C:\Users\Jenny>restic restore -H Athena latest  -t c:\restore-dates -vv
repository 86b7fabe opened successfully, password is correct
restoring <Snapshot b459f7df of [C:\Users\Jnani\00 Travelling] at 2019-08-05 14:04:27.2669245 +0700 +07 by ATHENA\Jnani@Athena> to c:\restore-dates
signal interrupt received, cleaning up
panic: send on closed channel

goroutine 102 [running]:
github.com/restic/restic/internal/restorer.(*fileRestorer).restoreFiles.func2()
        /restic/internal/restorer/filerestorer.go:155 +0xcd
created by github.com/restic/restic/internal/restorer.(*fileRestorer).restoreFiles
        /restic/internal/restorer/filerestorer.go:160 +0x1af

C:\Users\Jenny>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
B2

Expected behavior
-----------------
No errors after `cleaning up`.

Actual behavior
---------------
Errors as above

Steps to reproduce the behavior
-------------------------------

Press ^C during restore

Do you have any idea what may have caused this?
-----------------------------------------------
No, sorry

Do you have an idea how to solve the issue?
-------------------------------------------

No, sorry

Did restic help you or made you happy in any way?
-------------------------------------------------
Yes!  My backup disk failed and it has saved my digital life!

**Comment by HaleTom** [comment]
Update:

Got the same on Linux v0.9.5:

```
restic -v restore b459f7df -t /run/media/ravi/Sandisk-128GB/restore/
repository 86b7fabe opened successfully, password is correct
restoring <Snapshot b459f7df of [C:\Users\Jnani\00 Travelling] at 2019-08-05 14:04:27.2669245 +0700 +07 by ATHENA\Jnani@Athena> to /run/media/ravi/Sandisk-128GB/restore/
    signal interrupt received, cleaning up
panic: send on closed channel

goroutine 89 [running]:
github.com/restic/restic/internal/restorer.(*fileRestorer).restoreFiles.func2()
        src/github.com/restic/restic/internal/restorer/filerestorer.go:155 +0x115
created by github.com/restic/restic/internal/restorer.(*fileRestorer).restoreFiles
        src/github.com/restic/restic/internal/restorer/filerestorer.go:160 +0x20e
```

**Comment by HaleTom** [comment]
Additional `context canceled` output (again from Windows):

```
C:\Users\Jenny>restic restore -H Athena latest  --target "\\?\C:\restore-dates" -vv
repository 86b7fabe opened successfully, password is correct
restoring <Snapshot b459f7df of [C:\Users\Jnani\00 Travelling] at 2019-08-05 14:04:27.2669245 +0700 +07 by ATHENA\Jnani@Athena> to \\?\C:\restore-dates
signal interrupt received, cleaning up
ignoring error for \C\Users\Jnani\00 Travelling\2017-10-06 Kuala Lumpur\IMG_9075.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\2017-10-06 Kuala Lumpur\IMG_9076.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\2017-10-06 Kuala Lumpur\IMG_9077.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\2017-10-06 Kuala Lumpur\IMG_9079.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\2017-10-06 Kuala Lumpur\IMG_9074.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\0000 Phone photos - PLEASE FILE ME\Photos from old Jennypuss\Jenny's\2012-02-09\186.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\0000 Phone photos - PLEASE FILE ME\Photos from old Jennypuss\Jenny's\2012-02-09\188.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\0000 Phone photos - PLEASE FILE ME\Photos from old Jennypuss\Jenny's\2012-02-09\189.JPG: context canceled
ignoring error for \C\Users\Jnani\00 Travelling\0000 Phone photos - PLEASE FILE ME\Photos from old Jennypuss\Jenny's\2012-02-09\190.JPG: context canceled
```

**Comment by MichaelEischer** [comment]
@HaleTom The restorer code has been changed in restic 0.10.0, the problematic channel no longer exists. Could you test whether the problem still exists?

**Comment by MichaelEischer** [comment]
Closing this as there has been no feedback.
