### ISSUE TITLE
Trying to back up 4+ TB to S3, got a crash

### ISSUE THREAD

**Issue by larroy** [restic/restic#2387]
Output of `restic version`
--------------------------
restic 0.9.5 compiled with go1.12.4 on linux/amd64

How did you run restic exactly?
-------------------------------
time /root/restic backup --verbose -r s3:s3.amazonaws.com/xxxxx/restic_backup jenkins 2>&1 | tee /root/jenkins_backup.log

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

S3

Expected behavior
-----------------

Run to completion

Actual behavior
---------------
```
net/http.(*persistConn).writeLoop(0xc0e67a0000)                                                                                                                                     [38/1809]
        /usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn                                                                                                                                   
        /usr/local/go/src/net/http/transport.go:1358 +0xb0d  
               
goroutine 341749 [sleep]:     
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x33844730)
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/minio/minio-go.Client.newRetryTimer.func2(0xc16711e8a0, 0x1, 0xc16711e840, 0xc15b824a50)
        /restic/vendor/github.com/minio/minio-go/retry.go:82 +0x84         
created by github.com/minio/minio-go.Client.newRetryTimer                                                                                                                  
        /restic/vendor/github.com/minio/minio-go/retry.go:72 +0x156
                              
goroutine 341746 [sleep]:
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
time.Sleep(0x3a8dd321)   
        /usr/local/go/src/runtime/time.go:105 +0x159
github.com/minio/minio-go.Client.newRetryTimer.func2(0xc11af41920, 0x1, 0xc11af418c0, 0xc116f471d0)
        /restic/vendor/github.com/minio/minio-go/retry.go:82 +0x84
created by github.com/minio/minio-go.Client.newRetryTimer
        /restic/vendor/github.com/minio/minio-go/retry.go:72 +0x156
                                    
goroutine 341396 [IO wait]:                                                                                                                                                              
internal/poll.runtime_pollWait(0x7fad10ba0e90, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc031676898, 0x72, 0x1000, 0x104c, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc031676880, 0xc06d31cc00, 0x104c, 0x104c, 0x0, 0x0, 0x0)                                                                                                                  /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b                                                                                                         
net.(*netFD).Read(0xc031676880, 0xc06d31cc00, 0x104c, 0x104c, 0x203069, 0x0, 0xc000000030)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc075b4f548, 0xc06d31cc00, 0x104c, 0x104c, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc1a7a8b3a0, 0xc06d31cc00, 0x104c, 0x104c, 0x1, 0xa, 0xc17913e938)
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0acb00258, 0xf6cb00, 0xc1a7a8b3a0, 0x4099f5, 0xd0c9e0, 0xdf80a0)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0acb00000, 0xf6e180, 0xc075b4f548, 0x5, 0xc075b4f548, 0x203069)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0acb00000, 0xe6c200, 0xc0acb00138, 0xc17913edd0)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0acb00000, 0xc0acd56000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc0aca44000, 0xc0acd56000, 0x1000, 0x1000, 0x456160, 0xc17913ee88, 0x2)
        /usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0ac7d94a0)
        /usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0ac7d94a0, 0x1, 0x2, 0x0, 0x0, 0xc0523e9000, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0aca44000)
        /usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 341727 [select]:
net/http.(*persistConn).writeLoop(0xc000374c60)
        /usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1358 +0xb0d
```

Steps to reproduce the behavior
-------------------------------

I tried to backup a big volume, left it running overnight from EC2 to S3, came back in the morning and the program exited.

Do you have any idea what may have caused this?
-----------------------------------------------

No

Do you have an idea how to solve the issue?
-------------------------------------------

I restarted the backup and see, I hope I won't lose data or the previous backup.

Did restic help you or made you happy in any way?
-------------------------------------------------

I think this is a great program, I started using restic coming from an rsync background and I love it. The documentation is clear and I understand what is doing. Also seems well behaved and solid. Thanks so much for doing this!

**Comment by mholt** [comment]
The output is truncated; it seems you've "tailed" it, but the most useful information is at the beginning. What is the full output?

**Comment by larroy** [comment]
Looks like I have overwritten the log

I will see if it happens again.

Earliest I have is this:

```

        /restic/internal/archiver/tree_saver.go:63 +0x7e                                                                                                                          [1829/1829]
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0004c8230, 0xc000315b90)                                                                                          
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b                                                                                           
created by gopkg.in/tomb%2ev2.(*Tomb).Go                                                                                                            
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb7                                                                                           
                                                                                                                                                    
goroutine 330 [select]:                                                                                                               
github.com/restic/restic/internal/archiver.(*TreeSaver).worker(0xc00000de80, 0xf84780, 0xc00012e100, 0xc00003d800, 0xc00012e100, 0x0)               
        /restic/internal/archiver/tree_saver.go:152 +0x1a5                                                                                          
github.com/restic/restic/internal/archiver.NewTreeSaver.func1(0x0, 0x0)                                                                             
        /restic/internal/archiver/tree_saver.go:63 +0x7e                                                                             
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0004c8230, 0xc000315bc0)                                                                                          
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b                                                                                           
created by gopkg.in/tomb%2ev2.(*Tomb).Go                                                                                                            
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb7                                                                                           
                                                                                                                                                   
goroutine 331 [select]:                                                                                                                       
github.com/restic/restic/internal/archiver.(*TreeSaver).worker(0xc00000de80, 0xf84780, 0xc00012e100, 0xc00003d800, 0xc00012e100, 0x547aaf7324d65397)                        
        /restic/internal/archiver/tree_saver.go:152 +0x1a5                                                                                          
github.com/restic/restic/internal/archiver.NewTreeSaver.func1(0x1258e47d68fb0a3a, 0x8cd8856823985898)                                               
        /restic/internal/archiver/tree_saver.go:63 +0x7e                                                                             
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0004c8230, 0xc000315bf0)                                                                                          
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b                                                                                         
created by gopkg.in/tomb%2ev2.(*Tomb).Go                                                                                                           
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb7                                                                                           
                                                                                                                                                    
goroutine 332 [select]:                                                                                                                             
github.com/restic/restic/internal/archiver.(*TreeSaver).worker(0xc00000de80, 0xf84780, 0xc00012e100, 0xc00003d800, 0xc00012e100, 0x0)                                      
        /restic/internal/archiver/tree_saver.go:152 +0x1a5                                                                                          
github.com/restic/restic/internal/archiver.NewTreeSaver.func1(0x0, 0x0)                                                                             
        /restic/internal/archiver/tree_saver.go:63 +0x7e                                                                             
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0004c8230, 0xc000315c20)                                                                                          
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b                                                                                     
created by gopkg.in/tomb%2ev2.(*Tomb).Go                                                                                                            
        /restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xb7  

...
```

**Comment by larroy** [comment]
I rerun again and didn't have the crash.

**Comment by larroy** [comment]
I found the crash again. Looks like it's out of memory, thus my problem. Shall we close?

```

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xc0d786, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc050000000, 0x8000000, 0x11e41d8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x11ca7a0, 0x8000000, 0x4000221586, 0x7ffdb0726db8)
        /usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x11ca7a0, 0x3ae9, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x11ca7a0, 0x3ae9, 0x11e41e8, 0x20301300000000)
        /usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x11ca7a0, 0x3ae9, 0x410101, 0x7f7b63d8d000)
        /usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x11ca7a0, 0x3ae9, 0x7ffdb0010101, 0x415ef5)
        /usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x75d012d, 0x450101, 0x7f7b6a0416c0)
        /usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x455aa9)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229
```
