### ISSUE TITLE
Repo corruption (?) beginning with "fatal error: s.freeindex > s.nelems"

### ISSUE THREAD

**Issue by cdzombak** [restic/restic#2567]
Output of `restic version`
--------------------------
```
restic version
restic 0.9.6 compiled with go1.13.4 on linux/amd64
```

How did you run restic exactly?
-------------------------------

environment variables:
```
export AWS_ACCESS_KEY_ID=xxx
export AWS_SECRET_ACCESS_KEY=xxx
export RESTIC_PASSWORD=xxx
export RESTIC_REPOSITORY="s3:s3.wasabisys.com/dzombak.backup.xxx/restic"
```

Initial run which crashed was run via cron:
```
/usr/bin/flock -n /tmp/root-backup.lock ionice -c2 -n7 nice -n19 /root/backup.sh
```

The relevant portion of `backup.sh`:
```
restic backup /etc
```

Output (captured from cronjob email):
```
fatal error: s.freeindex > s.nelems

goroutine 3 [running]:
runtime.throw(0xdd8d1a, 0x16)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc000051628 sp=0xc0000515f8 pc=0x42df12
runtime.(*mspan).nextFreeIndex(0x7f12169b5fd8, 0x0)
	/usr/local/go/src/runtime/mbitmap.go:202 +0x173 fp=0xc000051660 sp=0xc000051628 pc=0x4140b3
runtime.(*mspan).sweep(0x7f12169b5fd8, 0xc000070000, 0x455200)
	/usr/local/go/src/runtime/mgcsweep.go:332 +0x45f fp=0xc000051740 sp=0xc000051660 pc=0x422e0f
runtime.sweepone(0xe0fbb0)
	/usr/local/go/src/runtime/mgcsweep.go:136 +0x285 fp=0xc0000517a8 sp=0xc000051740 pc=0x422745
runtime.bgsweep(0xc000070000)
	/usr/local/go/src/runtime/mgcsweep.go:73 +0xba fp=0xc0000517d8 sp=0xc0000517a8 pc=0x42240a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000517e0 sp=0xc0000517d8 pc=0x45b2c1
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:210 +0x5c

goroutine 1 [runnable]:
github.com/restic/restic/internal/restic.IDSet.Insert(...)
	/restic/internal/restic/idset.go:26
github.com/restic/restic/internal/repository.(*Index).Packs(0xc0001c0880, 0x0)
	/restic/internal/repository/index.go:251 +0x1b8
github.com/restic/restic/internal/repository.(*Repository).PrepareCache(0xc0001d20e0, 0xc0001ad020, 0x0, 0xc0001ad020)
	/restic/internal/repository/repository.go:511 +0x205
github.com/restic/restic/internal/repository.(*Repository).LoadIndex(0xc0001d20e0, 0xf20fe0, 0xc0001b9280, 0x0, 0x0)
	/restic/internal/repository/repository.go:486 +0x304
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/restic/cmd/restic/cmd_backup.go:490 +0x7ba
main.glob..func2(0x14ab4e0, 0xc000307980, 0x1, 0x1, 0x0, 0x0)
	/restic/cmd/restic/cmd_backup.go:63 +0x1bf
github.com/spf13/cobra.(*Command).execute(0x14ab4e0, 0xc000307940, 0x1, 0x1, 0x14ab4e0, 0xc000307940)
	/restic/vendor/github.com/spf13/cobra/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x14adfa0, 0xc0002f5eb0, 0x42d511, 0xe0fd98)
	/restic/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/restic/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/restic/cmd/restic/main.go:86 +0x3f

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 7 [chan receive]:
github.com/restic/restic/internal/restic.init.0.func1.1()
	/restic/internal/restic/lock.go:257 +0xb3
created by github.com/restic/restic/internal/restic.init.0.func1
	/restic/internal/restic/lock.go:254 +0x35

goroutine 9 [chan receive]:
github.com/restic/restic/internal/restic.init.2.func1(0xc000082120)
	/restic/internal/restic/progress_unix.go:17 +0x63
created by github.com/restic/restic/internal/restic.init.2
	/restic/internal/restic/progress_unix.go:16 +0xab

goroutine 18 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0001d4690)
	/restic/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/restic/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 19 [chan receive]:
main.CleanupHandler(0xc00020e6c0)
	/restic/cmd/restic/cleanup.go:62 +0x5d
created by main.init.0
	/restic/cmd/restic/cleanup.go:24 +0x67

goroutine 20 [select]:
github.com/restic/restic/internal/ui/termstatus.(*Terminal).runWithoutStatus(0xc000118f00, 0xf20fe0, 0xc00007ca40)
	/restic/internal/ui/termstatus/status.go:191 +0x11b
github.com/restic/restic/internal/ui/termstatus.(*Terminal).Run(0xc000118f00, 0xf20fe0, 0xc00007ca40)
	/restic/internal/ui/termstatus/status.go:87 +0xaa
main.glob..func2.1(0x0, 0x0)
	/restic/cmd/restic/cmd_backup.go:61 +0x6d
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0001d4730, 0xc0001bf500)
	/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc7

goroutine 68 [IO wait]:
internal/poll.runtime_pollWait(0x7f12189fa1a8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0001c4798, 0x72, 0x12000, 0x1204c, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0001c4780, 0xc000292000, 0x1204c, 0x1204c, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0001c4780, 0xc000292000, 0x1204c, 0x1204c, 0x203000, 0x7f12189fdc08, 0x0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000596190, 0xc000292000, 0x1204c, 0x1204c, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
crypto/tls.(*atLeastReader).Read(0xc0004bca20, 0xc000292000, 0x1204c, 0x1204c, 0x2000, 0x8, 0xc0005258a0)
	/usr/local/go/src/crypto/tls/conn.go:780 +0x60
bytes.(*Buffer).ReadFrom(0xc000102258, 0xf0c1c0, 0xc0004bca20, 0x409da5, 0xcb4e80, 0xd9b880)
	/usr/local/go/src/bytes/buffer.go:204 +0xb4
crypto/tls.(*Conn).readFromUntil(0xc000102000, 0xf0d4a0, 0xc000596190, 0x5, 0xc000596190, 0x457f40)
	/usr/local/go/src/crypto/tls/conn.go:802 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000102000, 0x0, 0x0, 0x3)
	/usr/local/go/src/crypto/tls/conn.go:609 +0x124
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:577
crypto/tls.(*Conn).Read(0xc000102000, 0xc00050c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1255 +0x161
net/http.(*persistConn).Read(0xc0005e8ea0, 0xc00050c000, 0x1000, 0x1000, 0xc00020e900, 0xc000525c20, 0x404d15)
	/usr/local/go/src/net/http/transport.go:1752 +0x75
bufio.(*Reader).fill(0xc000119c20)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc000119c20, 0x1, 0x0, 0x0, 0x1, 0xc000082d00, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0005e8ea0)
	/usr/local/go/src/net/http/transport.go:1905 +0x1d6
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1574 +0xafe

goroutine 69 [select]:
net/http.(*persistConn).writeLoop(0xc0005e8ea0)
	/usr/local/go/src/net/http/transport.go:2204 +0x123
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1575 +0xb23

goroutine 52 [select]:
github.com/restic/restic/internal/ui.(*Backup).Run(0xc0001d1860, 0xf20fe0, 0xc0001c2540, 0x0, 0x0)
	/restic/internal/ui/backup.go:93 +0x2e0
main.runBackup.func2(0x0, 0x0)
	/restic/cmd/restic/cmd_backup.go:464 +0x84
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0001d4780, 0xc00018d740)
	/restic/vendor/gopkg.in/tomb.v2/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	/restic/vendor/gopkg.in/tomb.v2/tomb.go:159 +0xc7

goroutine 25 [select]:
main.refreshLocks(0x14b8e00, 0xc0000829c0)
	/restic/cmd/restic/lock.go:72 +0x205
created by main.lockRepository
	/restic/cmd/restic/lock.go:49 +0x2ed
```

Ran the following to try to check and fix the repository:
```
# restic unlock --remove-all
repository a41fafe4 opened successfully, password is correct


# /usr/bin/flock -n /tmp/root-backup.lock ionice -c2 -n7 nice -n19 restic check
using temporary cache in /tmp/restic-check-cache-170959135
repository a41fafe4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-170959135
create exclusive lock for repository
load indexes
Load(<index/0865d9b819>, 0, 0) returned error, retrying after 462.318748ms: Copy: unexpected EOF
Load(<index/212d9dda15>, 0, 0) returned error, retrying after 593.411537ms: Copy: unexpected EOF
Load(<index/49f3f6ecf1>, 0, 0) returned error, retrying after 298.484759ms: Copy: unexpected EOF
Load(<index/4bf012c897>, 0, 0) returned error, retrying after 656.819981ms: Copy: unexpected EOF
Load(<index/8f5bd5b89f>, 0, 0) returned error, retrying after 409.029087ms: Copy: unexpected EOF
check all packs
check snapshots, trees and blobs
Load(<data/aa27d7f124>, 0, 0) returned error, retrying after 681.245719ms: Copy: unexpected EOF
Load(<data/2f453f1f31>, 0, 0) returned error, retrying after 396.557122ms: Copy: unexpected EOF
Load(<data/6ff083d66a>, 0, 0) returned error, retrying after 353.291331ms: Copy: unexpected EOF
Load(<data/c6427d2214>, 0, 0) returned error, retrying after 682.667507ms: Copy: unexpected EOF
Load(<data/7d44b62d03>, 0, 0) returned error, retrying after 264.151541ms: Copy: unexpected EOF
Load(<data/2d73b56f3e>, 0, 0) returned error, retrying after 690.271562ms: Copy: unexpected EOF
Load(<data/6ca5b84a37>, 0, 0) returned error, retrying after 298.727309ms: Copy: unexpected EOF
Load(<data/58c4e25c87>, 0, 0) returned error, retrying after 361.144708ms: Copy: unexpected EOF
Load(<data/39d6137e3a>, 0, 0) returned error, retrying after 590.539156ms: Copy: unexpected EOF
Load(<data/16d4a72b67>, 0, 0) returned error, retrying after 650.527522ms: Copy: unexpected EOF
Load(<data/ff8a40c37a>, 0, 0) returned error, retrying after 591.326744ms: Copy: unexpected EOF
Load(<data/145053a17b>, 0, 0) returned error, retrying after 295.418637ms: Copy: unexpected EOF
Load(<data/1df8726079>, 0, 0) returned error, retrying after 496.570999ms: Copy: unexpected EOF
Load(<data/a934e5106c>, 0, 0) returned error, retrying after 605.453598ms: Copy: unexpected EOF
Load(<data/0d26f4fb3b>, 0, 0) returned error, retrying after 531.889798ms: Copy: unexpected EOF
Load(<data/f04789c4d8>, 0, 0) returned error, retrying after 627.911754ms: Copy: unexpected EOF
Load(<data/3c824cc64f>, 0, 0) returned error, retrying after 572.269891ms: Copy: unexpected EOF
Load(<data/0f5d920b22>, 0, 0) returned error, retrying after 292.760253ms: Copy: unexpected EOF
Load(<data/f0e34d3292>, 0, 0) returned error, retrying after 434.846422ms: Copy: unexpected EOF
Load(<data/cc1f83fa09>, 0, 0) returned error, retrying after 390.665147ms: Copy: unexpected EOF
Load(<data/16ea48782d>, 0, 0) returned error, retrying after 562.547514ms: Copy: unexpected EOF
error for tree d09949ac:
  tree d09949ac: file "IMG_1075.MOV" blob 0 size could not be found
  tree d09949ac, blob f2583fbb: not found in index
Fatal: repository contains errors


# /usr/bin/flock -n /tmp/root-backup.lock ionice -c2 -n7 nice -n19 restic prune
repository a41fafe4 opened successfully, password is correct
counting files in repo
building new index for repo
[1:37:56] 100.00%  461145 / 461145 packs
repository contains 461145 packs (3127572 blobs) with 2.173 TiB
processed 3127572 blobs: 0 duplicate blobs, 0 B duplicate
load all snapshots
find data that is still in use for 133 snapshots
[6:05] 100.00%  133 / 133 snapshots
Fatal: number of used blobs is larger than number of available blobs!
Please report this error (along with the output of the 'prune' run) at
https://github.com/restic/restic/issues/new
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
[Wasabi](https://wasabi.com), which I note has had ongoing availability issues the past several days per https://status.wasabi.com

![Screen Shot 2020-02-05 at 5 50 10 PM](https://user-images.githubusercontent.com/102904/73890435-f9d75600-483f-11ea-8f81-646fd2dbbf6b.png)

Expected behavior
-----------------

I expect Restic to backup data resiliently in the face of unreliable remote storage without corrupting its repository.

Actual behavior
---------------

Restic crashed when backing up with `fatal error: s.freeindex > s.nelems`. Subsequently `restic check` returns `Fatal: repository contains errors` and `restic prune` reports `Fatal: number of used blobs is larger than number of available blobs!`

Steps to reproduce the behavior
-------------------------------

Unsure how to reproduce this one, sorry.

Do you have any idea what may have caused this?
-----------------------------------------------

Maybe Wasabi's ongoing unavailability issues?

I would note this is a large backup; in total this repo contains ~2.5TB of backup data.

Do you have an idea how to solve the issue?
-------------------------------------------

¯\\\_(ツ)\_\/¯

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Not really. I already ran into some corruption issue with restic 0.9.5, blew the backup repo away entirely, and started over with restic 0.9.6. I'm _not_ looking forward to uploading 2.5TB of data from my home with restic for a third time.

**Comment by MichaelEischer** [comment]
The backup run crashed somewhere in the go garbage collector, which should not be possible from within the restic code. At the time restic was just loading files from the index (look for `github.com/restic/restic/internal/repository.(*Repository).LoadIndex` in the backtraces). This therefore can't be the source for the check and prune errors.

It's quite likely that there's a problem with the index. You can run `restic rebuild-index` to rebuild the index from scratch. After that the missing blobs should show up. In case they don't and you still have the affected files stored locally, you can use `restic backup --force` to run a full rescan of the backup set and let restic reupload the missing parts.

**Comment by cdzombak** [comment]
> It's quite likely that there's a problem with the index. You can run `restic rebuild-index` to rebuild the index from scratch. After that the missing blobs should show up. In case they don't and you still have the affected files stored locally, you can use `restic backup --force` to run a full rescan of the backup set and let restic reupload the missing parts.

Thank you for the advice, @MichaelEischer. Unfortunately, `rebuild-index` and `backup --force` have failed to correct the issue; `check` still reports errors:

```
# restic rebuild-index
repository a41fafe4 opened successfully, password is correct
counting files in repo
[1:27:28] 100.00%  461145 / 461145 packs
finding old index files
saved new indexes as [1556f878 78fb396e 66956d4e 2c8fb2e4 78da9d1f 31d77c12 152b1719 4c658113 6beb0784 62b604ad 4881ec64 02cb6779 73eebfc4 6909e5ec 3e86cc61 4f3d2731 397b5905 2427c80c f888b4c0 59e213c9 08336533 ea6a8afc f93456bc 99002702 3a0bfe71 d5194500 d698acc2 e9a9892b e09c12c6 790701b6 2ba0f8b8 9e87c2e1 af296d6b e1fa68fb c541e599 4c71d0bf 69cf15f0 e73eeb76 d01a2694 9d0d2bec 36a91bfe b5ea6bcb 0d4d9429 898f94ee 8ebcd2f2 61981621 c4d04d09 6c7f4eaa ce77d6cc b74761b0 c07adf20 f3f87b6a 7ae12f0a 597e9af2 c72829da e5d0bcd4 337dd60f 7808dcad d20338ea a624586d 27731d56 1aaea65f 881ef19e 8da850d9 595d5c10 39f201e0 de9ed4a1 2a22c487 c19dbc57 26d412b7 1f800894 06db99af 30a9ebf3 aad892a1 23675844 19ac0db1 a80af3c4 c06b80d9 73ff0b28 e081de6e 4f016ad2 2a278b29 030839d0 f67d0811 f127bf73 1f40f297 0b23493d 21137909 eb3c286c 808841c3 1a107214 84641b6e 60171274 a837b196 925e5522 af7f5a02 84339feb b655346c d7be112d 0b1911af 9d282ef7 3e6436e6 7b779ffa fa6f6f15 8657b949 b850a64c 29b5a6e3 d880c09e 6d6dd4b6 65230f16 fe6fb6eb 35827583 efb0dbe0 4c0b75bd 8ec463a1 348cc3ff 16bf30f3 f974b723 b1ee4c77 885108a8 cdcb868c 9534a973 f0c07f55 acf042a1 a5a369d4 b2b73763 19e44bba 0e91a2c7 e8896c5d e41ad14e 1e60ddbf fc4f5d52 f57bd681 c7f0b619 e3febfe8 2dfb4c94 5590f260 989676d0 6dba0f88 5f0a3976 0eccabd2 32eb5dfe 95b0ec3e 32beba29 dbdcea05 8362fe7c 9cb30d3e 9051b9ea 8899af41 aacbe882 d2a1032d 4c1e3441 029eb6ec abc05ca9]
remove 274 old index files


root@goliath:~# restic check
using temporary cache in /tmp/restic-check-cache-286490063
repository a41fafe4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-286490063
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree 96711905:
  decrypting blob 96711905853e80541b3fa1b2dda25fe7213809fffa61b08286df13d76e52652f failed: ciphertext verification failed
error for tree d09949ac:
  tree d09949ac: file "IMG_1075.MOV" blob 0 size could not be found
  tree d09949ac, blob f2583fbb: not found in index
Fatal: repository contains errors


# restic backup --force /sharedfolders/xxa
repository a41fafe4 opened successfully, password is correct

Files:       812048 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 2.345 GiB

processed 812048 files, 562.955 GiB in 1:38:32
snapshot 7c20b79c saved


root@goliath:~# restic backup --force /home/cdzombak --exclude .cache --exclude .local
repository a41fafe4 opened successfully, password is correct

Files:        2266 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 19.248 KiB

processed 2266 files, 122.713 MiB in 0:11
snapshot 530feb88 saved


# restic backup --force /sharedfolders/xxb
repository a41fafe4 opened successfully, password is correct

Files:       674522 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 19.703 MiB

processed 674522 files, 926.943 GiB in 1:51:40
snapshot 244710ac saved


# restic backup --force /sharedfolders/xxc --exclude "yyy/lost+found" --exclude "zzz"
repository a41fafe4 opened successfully, password is correct

Files:       14221 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 33.320 MiB

processed 14221 files, 920.785 GiB in 1:22:06
snapshot d85915eb saved


# restic backup --force /root --exclude .cache --exclude .local
repository a41fafe4 opened successfully, password is correct

Files:          19 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 8.025 KiB

processed 19 files, 27.085 KiB in 0:07
snapshot 9c7e492f saved


# restic backup --force /etc
repository a41fafe4 opened successfully, password is correct

Files:         757 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Added to the repo: 37.895 KiB

processed 757 files, 4.350 MiB in 0:08
snapshot 04223fc6 saved


# restic backup --force /usr/local
repository a41fafe4 opened successfully, password is correct

Files:          90 new,     0 changed,     0 unmodified
Dirs:            1 new,     0 changed,     0 unmodified
Added to the repo: 733 B

processed 90 files, 20.580 MiB in 0:08
snapshot f96d1098 saved


# restic backup --force /srv/dev-disk-by-label-storage/plex-data --exclude "Library/Application Support/Plex Media Server/Logs" --exclude "Library/Application Support/Plex Media Server/Cache"
repository a41fafe4 opened successfully, password is correct

Files:       61489 new,     0 changed,     0 unmodified
Dirs:            2 new,     0 changed,     0 unmodified
Added to the repo: 214.365 MiB

processed 61489 files, 19.070 GiB in 7:12
snapshot aaa3f226 saved


# restic check
using temporary cache in /tmp/restic-check-cache-241677061
repository a41fafe4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-241677061
create exclusive lock for repository
load indexes
check all packs
pack f3e607f5: not referenced in any index
1 additional files were found in the repo, which likely contain duplicate data.
You can run `restic prune` to correct this.
check snapshots, trees and blobs
error for tree b1d1c4bb:
  decrypting blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 failed: ciphertext verification failed
error for tree 723ed3dc:
  tree 723ed3dc6795080a9863908ae562934cce5ce02608aeb1fb80610c39945cb33c not found in repository
error for tree d09949ac:
  tree d09949ac: file "IMG_1075.MOV" blob 0 size could not be found
  tree d09949ac, blob f2583fbb: not found in index
Fatal: repository contains errors


# restic rebuild-index
repository a41fafe4 opened successfully, password is correct
counting files in repo
[1:34:39] 100.00%  461782 / 461782 packs
finding old index files
saved new indexes as [9fab15f0 e7411255 b1b70a70 573c492d 60290c94 e2079cf9 f6110958 f3d444d4 0130979c b5072050 242c585b 32ddf6eb aa8b891a 4424265a 571d34fa a86ecae1 8bd024c2 5e21f0fc 07eb00bf 58283cc1 e4e1d377 6342aeb7 21c2fc86 82b55184 1c708805 d7c193dd 85758198 5e2c8b3a d7122322 b27db2d3 c769f8d7 c1eaa2ab ed8d8d5a bef708eb 8d1d1e7e e6f76a17 ded371b5 b5027248 123b20b2 94bb3bad e2f7e0be 17d73ceb 56578e31 c056a8fd 331da1e5 04a0b9dc 2c626473 9031e2b6 bf680bc5 f865a419 2e646b03 b07666da c9e61fad ae51d04d 5d9609ff 7769f310 2977f27b d70b8cbb 625f5983 41041e87 94302fd0 ae00b5d5 b533905f 2e91cd30 77f160a9 19a56d85 741bf3d9 a2db6c00 b6fbdcc6 862c2319 4dc3ac91 44fcccc0 d1afea12 baa0fd54 81215d73 90138a23 353c7c91 45f83472 9133cb4c d7f6cc0c c157906b 1d6f889d 74d9b1fe 9554cbe4 23cdfc15 d4eb67a2 5e23b743 4f277a92 8cfb62ef 1ca8810a ab7bed9e fad31453 94618a4f 1e732dda c13ec0c9 5ba42b42 2f757745 c8978bad 237b7f44 2a743326 a137f1f6 0f15cfcb d110194f 2597e9be bf44c29f c420765a 107dcff6 08d8890c 3825caa9 5e5d286b 2e17b226 917a4ce3 004a6e63 c42fa991 0b346da8 40dbd730 f8d30c44 5618cc3a 82049912 240b9150 2386c95c 7233beb0 f6a5ef52 5eb6a0ae f4b2a1bb 73e703de 31a1ad75 9b0f9915 89f69ff6 b4d81604 531254b1 1d9ee40e e17692c0 35202b93 8e42ccfe 9125b959 67bff945 055fbc82 e5a18879 5cd2c848 6dde9d6f ea8b4caa 21b1f387 331e8d6b be8c5ca8 238cd49b 8dc1b754 4a605178 7ea33b7a f39887bd ef29e0cc ea18e901 50f62e0a f2ec06af]
remove 187 old index files


# restic check
using temporary cache in /tmp/restic-check-cache-437690235
repository a41fafe4 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-437690235
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
error for tree d09949ac:
  tree d09949ac: file "IMG_1075.MOV" blob 0 size could not be found
  tree d09949ac, blob f2583fbb: not found in index
Fatal: repository contains errors
```

**Comment by MichaelEischer** [comment]
Does "IMG_1075.MOV" exist somewhere in the backed up directories?

I've spotted a few errors that are rather worrying:
```
pack f3e607f5: not referenced in any index
```
and
```
error for tree b1d1c4bb:
  decrypting blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 failed: ciphertext verification failed
error for tree 723ed3dc:
  tree 723ed3dc6795080a9863908ae562934cce5ce02608aeb1fb80610c39945cb33c not found in repository
```

None of these errors should be triggered by successful backup runs and they also shouldn't vanish on a second check run. Please run `restic cat blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 | shasum -a 256` and check that the (hopefully) reported checksum matches. 

Packs that are not referenced in any index are normally only possible if a backup run was interrupted, but that is not the case in posted the log. So either an index file mysteriously disappeared (which could explain the tree <...> not found error) or something else if wrong.

A 'ciphertext verification failed' error is frequently caused by RAM problems. You might want to consider running memtest to rule out memory problems as the error source.

**Comment by cdzombak** [comment]
> Does "IMG_1075.MOV" exist somewhere in the backed up directories?

It does, and I've confirmed it is readable and does not appear to be corrupted.
 
> Please run `restic cat blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 | shasum -a 256` and check that the (hopefully) reported checksum matches.

The checksum does match.

> A 'ciphertext verification failed' error is frequently caused by RAM problems. You might want to consider running memtest to rule out memory problems as the error source.

24 hours of memtest86 found 2 bit errors, in 8 GiB of memory. New RAM has been ordered and I'm going to hold off on this until I've installed it. Once it's installed, I assume I should try the same `check` / `rebuild-index` / `check` / `backup --force` process?

**Comment by MichaelEischer** [comment]
I'm still a bit confused about the missing blob. This looks like either "IMG_1075.MOV" has changed on disk which, however, should trigger a lot more warnings about trees with missing blobs or the memory issues caused the tree itself to become corrupted. You can use `restic find --tree d09949ac` to locate the snapshot(s) that reference this tree. My current assumption would be that only a single snapshot should reference this tree. In that case you could simply delete the affected snapshot.

Then I would recommend to run `restic check --read-data` to verify the content of every pack file. If I understand the wasabi website correctly, downloading the whole backup shouldn't incur costs. In case any packfile is broken please move the pack file somewhere outside the data folder, but make sure to keep it until you can ensure that the pack file just contains data that is still available locally.

Afterwards run `rebuild-index`, `check`, `backup --force`.

**Comment by fd0** [comment]
>  hours of memtest86 found 2 bit errors, in 8 GiB of memory. New RAM has been ordered and I'm going to hold off on this until I've installed it.

I must say that this is what I expected. Panics in the Go Garbage Collector are never a good sign. Glad you caught it early! If I remember correctly that's the seventh(?) instance in which restic accidentally uncovered hardware issues.

> > Please run restic cat blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 | shasum -a 256 and check that the (hopefully) reported checksum matches.

> The checksum does match.

Unfortunately that's not enough. It looks like the blob in question was corrupted during or right after encryption, so the signature does not match but the (outer) hash matches. There's nothing we can do here but to throw away the blob (or the pack).

Maybe it would be best to consider the backup untrustworthy and start over? :)

**Comment by cdzombak** [comment]
> Glad you caught it early! If I remember correctly that's the seventh(?) instance in which restic accidentally uncovered hardware issues.

I'm glad too 😄 New memory arrives today. I'll install it this weekend or next week, memtest it, and then proceed.

> It looks like the blob in question was corrupted during or right after encryption, so the signature does not match but the (outer) hash matches. There's nothing we can do here but to throw away the blob (or the pack).

As a relative newbie to restic, can you clarify how I should do that?

Thanks for the help!

**Comment by MichaelEischer** [comment]
> > > Please run restic cat blob b1d1c4bb4ab251bd8743d30539cd9d87621ee8e1c0d787b30813316ba3068039 | shasum -a 256 and check that the (hopefully) reported checksum matches.
> 
> > The checksum does match.
> 
> Unfortunately that's not enough. It looks like the blob in question was corrupted during or right after encryption, so the signature does not match but the (outer) hash matches. There's nothing we can do here but to throw away the blob (or the pack).

@fd0 My assumption would be that the verification of this blob temporarily failed during one check run, but succeeded the second time? If the blob were already damaged on disk, then the error shouldn't disappear when rerunning check (at least this seems to be very unlikely to me). This rather looks like a transient memory error to me.

Regarding the missing data blob `f2583fbb`, you can use `restic find --blob f2583fbb` to find the snapshot that references it. Afterwards just delete the snapshot using `restic forget <snapshot-id>`.

**Comment by fd0** [comment]
> @fd0 My assumption would be that the verification of this blob temporarily failed during one check run, but succeeded the second time? If the blob were already damaged on disk, then the error shouldn't disappear when rerunning check (at least this seems to be very unlikely to me). This rather looks like a transient memory error to me.

You're right, that explains the behavior much better than a corruption happening at backup. Good catch!

**Comment by cdzombak** [comment]
I've removed snapshots that reference the missing blob, and after a few rounds of `rebuild-index`, `check`, and `backup --force` things seem to be in order.

> Then I would recommend to run `restic check --read-data` to verify the content of every pack file. If I understand the wasabi website correctly, downloading the whole backup shouldn't incur costs.

Unfortunately, I'm on the older Wasabi pricing plan, which is cheaper per TiB stored but has an egress charge. Not on the site anymore, but [this article](https://searchstorage.techtarget.com/news/252438039/Wasabi-Technologies-eliminates-cloud-storage-egress-fees) seems to cover the change. I'm also on Comcast, who impose a 1 TiB data cap where I live :/

Thanks for the help, everyone.
