### ISSUE TITLE
botocore.exceptions.SSLError: SSL validation failed for https://xxxxx.xxxxx.xxxxxx.xxxx.net/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

### ISSUE THREAD

**Issue by yadu-boss** [restic/restic#2667]
Hi team,

I am using ubuntu 19.04 version.
and trying to delete bucket from cloudian hyperstore.
 
Below is my python script and error getting when I ran script.
PLease find script, if any changes require let me know.
 

#!/usr/bin/env python
import boto3
from boto3.s3.transfer import S3Transfer
import datetime
#conn = S3Connection(validate_certs=False)
from boto3.session import Session
session = Session(aws_access_key_id='xxxxxxxxxxxxxxxxxxxxxxxx',       aws_secret_access_key='xxxxxxxxxxxxxxxxxxxx',       region_name='region1')
s3 = session.resource('s3')
client = session.client('s3',       endpoint_url='https://xxxxx.xxxxx.xxxxxx.xxxxxxx.net')
client.list_buckets()

 Traceback (most recent call last):
  File "./pravesh", line 10, in <module>
    client.list_buckets()
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/lib/python2.7/dist-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/lib/python2.7/dist-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/lib/python2.7/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.exceptions.SSLError: SSL validation failed for https://xxxxx.xxxxx.xxxx.corpintra.net/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

**Comment by BrendyTeamTest** [comment]
Test comment system

**Comment by rawtaz** [comment]
@yadu-boss From what I can tell, this has nothing to do with restic. Please post/ask in the relevant repository, or if you think it has anything to do with restic, use [the forum](https://forum.restic.net/) (the "Getting help" section).
