### ISSUE TITLE
restic backup hangs forever most of the times

### ISSUE THREAD

**Issue by lorenzbausch** [restic/restic#2834]
Output of `restic version`
--------------------------
`restic 0.9.6 (v0.9.6-249-g2c72924f) compiled with go1.14.3 on linux/amd64` but also happens with `restic 0.9.6 compiled with go1.13.4 on linux/amd64`

How did you run restic exactly?
-------------------------------
```
$ restic --cacert /root/.restic/ca-bundle.pem --cache-dir /home/.cache/restic backup --exclude-caches --one-file-system --exclude /var/log/lastlog -v / /home /var/lib/mysql_binlog
open repository
lock repository
load index files
using parent snapshot a9f3206e
start scan on [/ /home /var/lib/mysql_binlog]
start backup on [/ /home /var/lib/mysql_binlog]
```
No further output. When invoking with `-vv` the scanned/backuped files are printed (`/var` being the last entry), but eventually no further output appears.

Environment:
```
RESTIC_REPOSITORY=s3:https://<redacted>:9000/<redacted>
RESTIC_PASSWORD=<redacted>
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
S3/Minio in a Docker container: `minio/minio:RELEASE.2020-07-13T18-09-56Z` - was using an older version before and updated to the latest version.

Expected behavior
-----------------
Perform a backup and exit with status code `0` after several hours.

Actual behavior
---------------
Backups are started once per day. With only a few exceptions the restic process runs "forever" and I killed it every time once it was running for several days. In the past, backups finished after a few hours.
The odd thing is, `restic snapshots` shows a snapshot was created, but the restic process creating this very snapshot still hasn't finished.
When the process seems to have stalled, `strace` shows the following (excerpt):
<details>
  <summary>strace -e trace=file -f -p $(pidof restic)</summary>

```
$ strace -e trace=file -f -p $(pidof restic)
strace: Process 1820 attached with 19 threads
[pid  1829] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1832] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1828] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1991] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1830] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1992] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid 32217] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1830] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid 17224] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
[pid  1826] --- SIGURG {si_signo=SIGURG, si_code=SI_TKILL, si_pid=1820, si_uid=0} ---
...
```
</details>

<details>
  <summary>strace -f -p $(pidof restic)</summary>

```
$ strace -f -p $(pidof restic)
strace: Process 1820 attached with 19 threads
[pid 32217] futex(0xc00048ebc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 17224] futex(0xc000101d48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  3202] futex(0xc000100f48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1992] futex(0xc00048e148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1990] futex(0xc0001012c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1834] futex(0xc0001004c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1833] futex(0xc00048e848, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1832] futex(0xc000202148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1830] futex(0xc0001824c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1829] futex(0xc0000ee148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1828] futex(0xc000182148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1827] futex(0x1479978, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1825] futex(0x1479a80, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1824] futex(0xc00006e4c8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] restart_syscall(<... resuming interrupted restart_syscall ...> <unfinished ...>
[pid  1820] futex(0x144f628, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 0, NULL, 660846458731897) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... restart_syscall resumed>) = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000}, NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=998351272} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 4400, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4217995752368244) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=999120646} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 9976, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4193702090911558) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] <... futex resumed>)        = 0
[pid  1826] <... futex resumed>)        = 1
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=0, tv_nsec=815346751} <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 9979, NULL, 0) = 0
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 4429449491030384) = 0
[pid  1835] epoll_pwait(3,  <unfinished ...>
[pid  1823] <... futex resumed>)        = -1 ETIMEDOUT (Connection timed out)
[pid  1823] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1826] <... futex resumed>)        = 0
[pid  1823] <... futex resumed>)        = 1
[pid  1826] futex(0xc00006f648, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] <... futex resumed>)        = 1
[pid  1991] <... futex resumed>)        = 0
[pid  1991] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] <... nanosleep resumed>NULL) = 0
[pid  1991] futex(0xc00048ebc8, FUTEX_WAKE_PRIVATE, 1) = 1
[pid 32217] <... futex resumed>)        = 0
[pid 32217] futex(0xc00048ebc8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1991] write(6, "\27\3\3\0\23\315\370\367w\211\302\"\265\25L%\32315\350\262\24\314\266", 24 <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1991] <... write resumed>)        = 24
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1991] epoll_ctl(3, EPOLL_CTL_DEL, 6, 0xc0000a06ac <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1991] <... epoll_ctl resumed>)    = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] close(6)                    = 0
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1835] <... epoll_pwait resumed>[], 128, 769, NULL, 0) = 0
[pid  1991] futex(0xc000100148, FUTEX_WAKE_PRIVATE, 1) = 1
[pid  1826] <... futex resumed>)        = 0
[pid  1826] nanosleep({tv_sec=0, tv_nsec=3000},  <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1991] futex(0xc00006f648, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1826] <... nanosleep resumed>NULL) = 0
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
[pid  1826] futex(0xc000100148, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid  1823] <... nanosleep resumed>NULL) = 0
[pid  1823] futex(0x144eb78, FUTEX_WAIT_PRIVATE, 0, {tv_sec=9, tv_nsec=179382066} <unfinished ...>
[pid  1835] epoll_pwait(3, [], 128, 0, NULL, 2516917869055365) = 0
[pid  1835] epoll_pwait(3, 
```
</details>

Steps to reproduce the behavior
-------------------------------
As far as I can tell the issue is not reliable reproducible. It appears with 0.9.6 and recent beta builds.
I've also run a debug build of restic (`restic 0.9.6 compiled with go1.14 on linux/amd64`) and while this build takes significantly longer to perform a backup and fills the `DEBUG_LOG` file, it worked every single time (or maybe I just haven't tried often enough?).

Do you have any idea what may have caused this?
-----------------------------------------------
No, but since we've deployed restic on hundreds of machines with basically identical configuration I suspect this single machine is the root cause. Unfortunately I have no clue what this might be and to the best of my knowledge the machine in question also does not differ significantly from others.

Do you have an idea how to solve the issue?
-------------------------------------------
Well, no. What I've tried so far:
- rebooted machine and fsck'ed all filesystems (ext4, xfs) 
- tried different restic builds and a debug build of version 0.9.6
- backed up to a new repository

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
restic really has proven itself over time and I'm looking forward for future improvements. Thank you everyone who is contributing lately and keeps the project alive!

**Comment by rawtaz** [comment]
Thanks a lot for such a thorough report!

- Is there any version where you could *not* reproduce the problem at all? Did you try 0.9.5?

- When you say debug, did you [do this](https://restic.readthedocs.io/en/latest/090_participating.html#debugging) and what did the last stuff in the debug log yield in that case? I'm hoping there's something in there that at least tells us the very last thing restic did before things stalled. It's interesting you say that it did create a snapshot.

- Did you try another type of repository (e.g. a local disk)? I'm asking because it would be nice to rule out/in the backend being involved.

**Comment by lorenzbausch** [comment]
Thank you @rawtaz for your quick reply :+1: 
I'm puzzled. I tried 0.9.5 and this version worked like a charm. So I spent the last couple of days with `git bisect` and created restic builds with commits between 0.9.5 and 0.9.6 to reproduce the error, but to no avail. At this point I tend even more to believe this not at all caused by restic itself.
I'm closing this for now since I'm running out of ideas. Maybe the problem re-occurs and I can do further troubleshooting.
Thank you again for your assistance!

**Comment by lorenzbausch** [comment]
It happened again after the update to 0.10.0. Updated the binary, started a backup and it goes forever / stalls.
I observed network traffic between the backing up machine and the MinIO server and restic scanned all files (seen with strace). After all files were scanned the process and its threads are basically stalled, the strace output is the same as provided in my initial report.
On normal backup runs restic would output several lines `uploading intermediate index [..]`, but those are missing. No output after `start backup on [/ /home /var/lib/mysql_binlog]`.

Could anybody familiar with the restic internals think of a constellation which might lead to such behaviour?

It basically looks like a deadlock to me, will try to reproduce with a debug build next.

**Comment by MichaelEischer** [comment]
> `uploading intermediate index [..]`

The intermediate index uploading was rewritten and this message no longer exists. You could send restic a `SIGABRT` signal in which case Go aborts the program execution and prints a stack trace.

**Comment by lorenzbausch** [comment]
@MichaelEischer thank you for the hint about the removed message, that explains a lot :)

I sent `kill -6` to the restic process and this is the output:

<details>
<summary>restic strack strace</summary>

```
SIGABRT: abort
PC=0x46ce81 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x158c588, 0x80, 0x0, 0x0, 0x0, 0x46b001, 0xc0003b1080, 0xc03f633970, 0x7fffeafcc790, 0x40beff, ...)
        /usr/local/go/src/runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x158c588, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x158c588)
        /usr/local/go/src/runtime/lock_futex.go:159 +0x9f
runtime.stopm()
        /usr/local/go/src/runtime/proc.go:1910 +0xc5
runtime.exitsyscall0(0xc0003b1080)
        /usr/local/go/src/runtime/proc.go:3401 +0x11d
runtime.mcall(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [chan receive, 6324 minutes]:
gopkg.in/tomb%2ev2.(*Tomb).Wait(0xc0001bc050, 0x0, 0x0)
        /home/build/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:126 +0x4a
main.runBackup(0x0, 0x0, 0x0, 0xc0003a8960, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /restic/cmd/restic/cmd_backup.go:616 +0x1156
main.glob..func2(0x1579c60, 0xc0000980d0, 0x4, 0xd, 0x0, 0x0)
        /restic/cmd/restic/cmd_backup.go:70 +0x1ba
github.com/spf13/cobra.(*Command).execute(0x1579c60, 0xc0001adee0, 0xd, 0xd, 0x1579c60, 0xc0001adee0)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x157ce40, 0xc0003a8870, 0x2, 0x8)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /restic/cmd/restic/main.go:86 +0x3f

goroutine 6 [chan receive, 6401 minutes]:
github.com/restic/restic/internal/restic.init.0.func1.1()
        /restic/internal/restic/lock.go:258 +0xb3
created by github.com/restic/restic/internal/restic.init.0.func1
        /restic/internal/restic/lock.go:255 +0x35

goroutine 17 [syscall, 6401 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:150 +0x45

goroutine 18 [chan receive, 6401 minutes]:
github.com/restic/restic/internal/restic.init.2.func1(0xc00008c300)
        /restic/internal/restic/progress_unix.go:17 +0x65
created by github.com/restic/restic/internal/restic.init.2
        /restic/internal/restic/progress_unix.go:16 +0xab

goroutine 12 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0002b0080)
        /home/build/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x105
created by go.opencensus.io/stats/view.init.0
        /home/build/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68

goroutine 13 [chan receive, 6401 minutes]:
main.CleanupHandler(0xc000114300)
        /restic/cmd/restic/cleanup.go:59 +0x4c
created by main.init.0
        /restic/cmd/restic/cleanup.go:21 +0x67

goroutine 23 [select, 6324 minutes]:
github.com/restic/restic/internal/ui/termstatus.(*Terminal).runWithoutStatus(0xc000194660, 0x103ef00, 0xc0001b6000)
        /restic/internal/ui/termstatus/status.go:181 +0x11b
github.com/restic/restic/internal/ui/termstatus.(*Terminal).Run(0xc000194660, 0x103ef00, 0xc0001b6000)
        /restic/internal/ui/termstatus/status.go:89 +0xac
main.glob..func2.1(0x438405, 0x1522dc0)
        /restic/cmd/restic/cmd_backup.go:68 +0x6d
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0001bc000, 0xc00044c4a0)
        /home/build/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x38
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/build/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xbc

goroutine 16 [select]:
main.refreshLocks(0x158a8a0, 0xc000044840)
        /restic/cmd/restic/lock.go:70 +0x1c5
created by main.lockRepository
        /restic/cmd/restic/lock.go:47 +0x26c

goroutine 30 [select, 6324 minutes]:
github.com/restic/restic/internal/ui.(*Backup).ReportTotal(0xc000099ad0, 0xc045abbf10, 0x6c, 0x14a7a17, 0x31c49b, 0x17fc5, 0x420c76160ee)
        /restic/internal/ui/backup.go:343 +0xf7
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a7a17, 0x31c49b, 0x17fc5, 0x420c76160ee, 0xc045abbf10, 0x6c, 0x14a7a17, ...)
        /restic/internal/archiver/scanner.go:107 +0x1f0
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a7a17, 0x31c49a, 0x17fc5, 0x420c76160ee, 0xc045abbd50, 0x63, 0x14a7a14, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a7a14, 0x31c499, 0x17fc5, 0x420c7613322, 0xc07da9b080, 0x5f, 0x0, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a79d8, 0x31c493, 0x17fc5, 0x420c75b88c7, 0xc07dc1b980, 0x58, 0x0, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a79d8, 0x31c493, 0x17fc5, 0x420c75b88c7, 0xc068d05200, 0x52, 0x14a79d8, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a79d8, 0x31c493, 0x17fc5, 0x420c75b88c7, 0xc0641a7540, 0x4c, 0x0, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a78e5, 0x31c462, 0x17fc5, 0x420c74858f6, 0xc08ba61f40, 0x48, 0x14a78e5, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a78e5, 0x31c462, 0x17fc5, 0x420c74858f6, 0xc06655cb40, 0x42, 0x14a78cf, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a78cf, 0x31c45c, 0x17fc5, 0x420c7478406, 0xc05ff9f9c0, 0x3c, 0x14a72ff, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a72ff, 0x31c36c, 0x17fc5, 0x420c55e20ff, 0xc0474db2c0, 0x33, 0x14a6c73, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x14a6c73, 0x31c1ca, 0x17fc5, 0x420c39ae78a, 0xc069d46fc0, 0x26, 0x149b6a9, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x149b6a9, 0x31a7e0, 0x17fc5, 0x420117f4ad5, 0xc049ddef40, 0x19, 0x1482370, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x1482370, 0x31686b, 0x17fc4, 0x417b3041f2a, 0xc048a66870, 0xd, 0x148179e, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0x148179e, 0x3167e3, 0x17fb1, 0x417b266f452, 0x7fffeafccfb9, 0x5, 0x120ee26, ...)
        /restic/internal/archiver/scanner.go:97 +0x4a5
github.com/restic/restic/internal/archiver.(*Scanner).Scan(0xc000133d70, 0x103ef00, 0xc0002b4580, 0xc00009cfc0, 0x4, 0x4, 0xc00011fed0, 0x2)
        /restic/internal/archiver/scanner.go:50 +0x16f
main.runBackup.func5(0xf56790, 0x0)
        /restic/cmd/restic/cmd_backup.go:576 +0x9a
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0001bc050, 0xc009b93800)
        /home/build/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x38
created by gopkg.in/tomb%2ev2.(*Tomb).Go
        /home/build/go/pkg/mod/gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xbc

goroutine 16387 [select]:
net/http.(*persistConn).writeLoop(0xc0000b9200)
        /usr/local/go/src/net/http/transport.go:2340 +0x11c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1709 +0xcdc

goroutine 16386 [IO wait]:
internal/poll.runtime_pollWait(0x7f516825dc50, 0x72, 0x102af80)
        /usr/local/go/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc000196218, 0x72, 0xc0000c6900, 0x801, 0x801)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000196200, 0xc0000c6900, 0x801, 0x801, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc000196200, 0xc0000c6900, 0x801, 0x801, 0x203000, 0x626abb, 0xc00019e160)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000126058, 0xc0000c6900, 0x801, 0x801, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000310020, 0xc0000c6900, 0x801, 0x801, 0x118, 0x7fc, 0xc0003e6668)
        /usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc00019e280, 0x1027a80, 0xc000310020, 0x40b3e5, 0xde7240, 0xed28a0)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc00019e000, 0x1029720, 0xc000126058, 0x5, 0xc000126058, 0x107)
        /usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc00019e000, 0x0, 0x0, 0xc07d071e00)
        /usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc00019e000, 0xc000321000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
net/http.(*persistConn).Read(0xc0000b9200, 0xc000321000, 0x1000, 0x1000, 0xc0003e6eb0, 0x463d20, 0xc0003e6eb0)
        /usr/local/go/src/net/http/transport.go:1887 +0x77
bufio.(*Reader).fill(0xc06e4117a0)
        /usr/local/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).Peek(0xc06e4117a0, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc07d071ce0)
        /usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0000b9200)
        /usr/local/go/src/net/http/transport.go:2040 +0x1a8
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1708 +0xcb7

rax    0xca
rbx    0x158c440
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x158c588
rsi    0x80
rbp    0x7fffeafcc758
rsp    0x7fffeafcc710
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xaee9b5406eee500
r13    0x7222e02500d8785f
r14    0x3ffacbb82c28c98
r15    0x0
rip    0x46ce81
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```
</details>

**Comment by MichaelEischer** [comment]
@lorenzbausch The stacktrace looks like the backup was cancelled / finished(???) after 77 minutes, at which point the scanner goroutine got stuck while trying to update the backup progress. #2963 should fix the problem displayed in the stacktrace.

**Comment by lorenzbausch** [comment]
@MichaelEischer thank you for your time and bringing up a possible fix, I will test a build containing it :+1: 
I have no idea what might cancel or finish restic, we didn't change anything about how we invoke restic for several releases.
