### ISSUE TITLE
Implement Metadata Cache

### ISSUE THREAD

**Issue by scoddy** [restic/restic#29]
Metadata should be cached locally for multiple operations.
- Feature to limit cache size

**Comment by fd0** [comment]
This has already been started.

**Comment by fd0** [comment]
Blob lists for snapshots are now cached in a cache directory. More metadata caching will be added once it's needed.

**Comment by fd0** [comment]
The cache was removed, so this issue is open again.

**Comment by r3dey3** [comment]
Not sure if I should create a new issue for this, but I'm using add-cache branch (I rebased d9d22d6 onto 0ee1650 but I'm guessing that's not the cause).
 If a metadata file cannot be retrieved (eg a snapshot) because of a permissions issue, restic panics but not before caching an invalid file. I was able to recreate the problem using a test repo and changing the ownership of a snapshot file to root after doing a couple of backups.

The error message from the initial failure:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x47dc12]

goroutine 1 [running]:
io.copyBuffer(0xdfd760, 0xc4222960a0, 0x0, 0x0, 0xc42227c000, 0x8000, 0x8000, 0xab0ae0, 0xc422328900, 0xdfd760)
	/usr/local/go/src/io/io.go:392 +0x102
io.Copy(0xdfd760, 0xc4222960a0, 0x0, 0x0, 0xc4222960a0, 0xe010a0, 0xc4222960a0)
	/usr/local/go/src/io/io.go:362 +0x68
github.com/restic/restic/internal/cache.(*Cache).Save(0xc420052ac0, 0xac8477, 0x8, 0xc4223289c0, 0x40, 0x0, 0x0, 0x0, 0x0)
	src/github.com/restic/restic/internal/cache/file.go:97 +0x181
github.com/restic/restic/internal/cache.(*Backend).Load(0xc4200e4620, 0xe04160, 0xc420016120, 0xac8477, 0x8, 0xc4223289c0, 0x40, 0x0, 0x0, 0x6e1aad, ...)
	src/github.com/restic/restic/internal/cache/backend.go:113 +0x50f
github.com/restic/restic/internal/backend.LoadAll(0xe04160, 0xc420016120, 0xe07400, 0xc4200e4620, 0xac8477, 0x8, 0xc4223289c0, 0x40, 0x0, 0x0, ...)
	src/github.com/restic/restic/internal/backend/utils.go:13 +0xda
github.com/restic/restic/internal/repository.(*Repository).LoadAndDecrypt(0xc4201cc380, 0xe04160, 0xc420016120, 0xac8477, 0x8, 0x9be9a8b934f306ec, 0xbfbdb6d281588b0f, 0x3e7bef705bbfbd65, 0x9758b47ce25634fd, 0x410d38, ...)
	src/github.com/restic/restic/internal/repository/repository.go:71 +0x1b8
github.com/restic/restic/internal/repository.(*Repository).LoadJSONUnpacked(0xc4201cc380, 0xe04160, 0xc420016120, 0xac8477, 0x8, 0x9be9a8b934f306ec, 0xbfbdb6d281588b0f, 0x3e7bef705bbfbd65, 0x9758b47ce25634fd, 0xa791e0, ...)
	src/github.com/restic/restic/internal/repository/repository.go:184 +0x86
github.com/restic/restic/internal/restic.LoadSnapshot(0xe04160, 0xc420016120, 0xe08660, 0xc4201cc380, 0x9be9a8b934f306ec, 0xbfbdb6d281588b0f, 0x3e7bef705bbfbd65, 0x9758b47ce25634fd, 0xc4200aa580, 0x0, ...)
	src/github.com/restic/restic/internal/restic/snapshot.go:57 +0x106
github.com/restic/restic/internal/restic.FindLatestSnapshot(0xe04160, 0xc420016120, 0xe08660, 0xc4201cc380, 0xc4201d4010, 0x1, 0x1, 0xc4222e19f8, 0x1, 0x1, ...)
	src/github.com/restic/restic/internal/restic/snapshot_find.go:24 +0x1f4
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:400 +0xdea
main.glob..func3(0xe39320, 0xc420053fe0, 0x1, 0x1, 0x0, 0x0)
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:50 +0x195
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute(0xe39320, 0xc420053fa0, 0x1, 0x1, 0xe39320, 0xc420053fa0)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:649 +0x456
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xe38ea0, 0x429646, 0xaf1aa8, 0xc4201a3de8)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:728 +0x2fe
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute(0xe38ea0, 0x24, 0xc4201a3eb0)
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:687 +0x2b
main.main()
	src/github.com/restic/restic/cmd/restic/main.go:72 +0x1de
```

After fixing the ownership issue and attempting another backup it appears a cache file for the snapshot exists, but it is empty. 
```
Error listing snapshot: load <snapshot/ec06f334b9>: invalid data returned
github.com/restic/restic/internal/restic.FindLatestSnapshot
	src/github.com/restic/restic/internal/restic/snapshot_find.go:26
main.runBackup
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:400
main.glob..func3
	src/github.com/restic/restic/cmd/restic/cmd_backup.go:50
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:649
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:728
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
	src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:687
main.main
	src/github.com/restic/restic/cmd/restic/main.go:72
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2337
```

**Comment by fd0** [comment]
Like I wrote in that branch: "**do not use this code**"

But I'm still glad you did and reported this error. Nice work! :)
