### ISSUE TITLE
Panic in the –-exclude-larger-than filter function

### ISSUE THREAD

**Issue by DRON-666** [restic/restic#2942]
Output of `restic version`
--------------------------
restic 0.10.0 (v0.10.0-0-g40832b2-dirty) compiled with go1.15.2 on windows/amd64
It's custom windows build with VSS and rewrite support, so I decided to write on [forum](https://forum.restic.net/t/panic-in-the-exclude-larger-than-filter-function/3074) first.

How did you run restic exactly?
-------------------------------
restic backup --use-windows-vss **--exclude-larger-than=1g** C:\SomeBigFolder

What backend/server/service did you use to store the repository?
----------------------------------------------------------------
local filesystem repository

Expected behavior
-----------------
restic create snapshot without error

Actual behavior
---------------
~~~
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xce17f6]

goroutine 1 [running]:
main.rejectBySize.func1(0xc008c641e0, 0x3e, 0x0, 0x0, 0xc000b64040)
        **github.com/restic/restic/cmd/restic/exclude.go:305** +0x36
main.runBackup.func4(0xc008c641e0, 0x3e, 0x0, 0x0, 0x0)
        github.com/restic/restic/cmd/restic/cmd_backup.go:550 +0x8f
github.com/restic/restic/internal/archiver.(*Archiver).Save(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc008c6edc0, 0x3e, 0xc000233680, 0x3e, 0x0, 0xc008c6edc0, 0x3e, ...)
        **github.com/restic/restic/internal/archiver/archiver.go:348** +0x23a
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc008c4b3b0, 0x28, 0xc008bf1700, 0x0, 0x0, 0x4a, 0xc008c64190)
        github.com/restic/restic/internal/archiver/archiver.go:551 +0x4d4
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc008c2c820, 0x1d, 0xc008bf16c0, 0x0, 0x5bc, 0x8a877424, 0x0)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc00abee480, 0x15, 0xc00abfc1c0, 0x0, 0x0, 0x0, 0x8)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc0001ad370, 0xd, 0xc00abfc180, 0x0, 0x1b, 0x4, 0x3001e)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc0001ad338, 0x8, 0xc00abfc140, 0x0, 0x0, 0xc00aae4260, 0xc)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc00008cb30, 0x2, 0xc000220b00, 0x0, 0x0, 0x0, 0xc0003d4000)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).SaveTree(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xef2cd6, 0x1, 0xc00003b7c0, 0x0, 0x0, 0x7c0965, 0x1029180)
        github.com/restic/restic/internal/archiver/archiver.go:579 +0xc11
github.com/restic/restic/internal/archiver.(*Archiver).Snapshot.func1(0xc0002307e0, 0x1029180, 0xc000220ac0, 0xc00003b7c0, 0xc0003e42e0, 0x2, 0x2, 0xc00011d6f0, 0x9, 0x0, ...)
        github.com/restic/restic/internal/archiver/archiver.go:774 +0xe5
github.com/restic/restic/internal/archiver.(*Archiver).Snapshot(0xc0002307e0, 0x1029180, 0xc000221240, 0xc000416800, 0x41, 0x80, 0xc0003e42e0, 0x2, 0x2, 0xc00011d6f0, ...)
        github.com/restic/restic/internal/archiver/archiver.go:784 +0x245
main.runBackup(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/restic/restic/cmd/restic/cmd_backup.go:621 +0x1085
main.glob..func2(0x15501e0, 0xc0003f8820, 0x0, 0xa, 0x0, 0x0)
        github.com/restic/restic/cmd/restic/cmd_backup.go:71 +0x1da
github.com/spf13/cobra.(*Command).execute(0x15501e0, 0xc0003f86e0, 0xa, 0xa, 0x15501e0, 0xc0003f86e0)
        github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x1553120, 0xc000332890, 0x2, 0x8)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        github.com/restic/restic/cmd/restic/main.go:86 +0x46
~~~

Steps to reproduce the behavior
-------------------------------
You need some files be scaned, but removed before archiving. In my case it was journal of SQLite database and i can't reproduce this error.

Do you have any idea what may have caused this?
-----------------------------------------------
Absence of nil check in `rejectBySize` function.

Do you have an idea how to solve the issue?
-------------------------------------------
Two ideas:
1. Add check similar to `rejectByDevice`.
2. In `Archiver.Save` check for errors before calling filter.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Yes. Always.

**Comment by YoshieraHuang** [comment]
@rawtaz I will issue a PR to fix this bug soon

**Comment by greatroar** [comment]
So, this issue should be solved now, right?

**Comment by YoshieraHuang** [comment]
> So, this issue should be solved now, right?

Yes, please close it.

**Comment by rawtaz** [comment]
Thanks for the report and contribution! You helped make restic better.
