### ISSUE TITLE
prune --dry-run on ARM fails with segmentation violation

### ISSUE THREAD

**Issue by demlak** [restic/restic#3185]
Hardware:
--------------------------
"cubietruck 2" with 1GB RAM

Output of `restic version`
--------------------------
restic 0.11.0-dev (compiled manually) compiled with go1.15.6 on linux/arm

How did you run restic exactly?
--------------------------

```
# sudo restic_v0.11.0-207-gf7c7c2f7_linux_arm -r repo prune --dry-run
enter password for repository: 
repository 551da140 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 11 snapshots
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11ce8]

goroutine 14 [running]:
runtime/internal/atomic.goLoad64(0x1824294, 0x0, 0x1a6e200)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/restic/restic/internal/ui/progress.(*Counter).get(...)
        /home/beta/restic.git/internal/ui/progress/counter.go:69
github.com/restic/restic/internal/ui/progress.(*Counter).run.func1(0x1824270)
        /home/beta/restic.git/internal/ui/progress/counter.go:75 +0x24
panic(0x88b8b8, 0xf0e838)
        /usr/local/go/src/runtime/panic.go:969 +0x158
runtime/internal/atomic.goLoad64(0x1824294, 0x1af773c, 0x3)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:131 +0x1c
github.com/restic/restic/internal/ui/progress.(*Counter).get(...)
        /home/beta/restic.git/internal/ui/progress/counter.go:69
github.com/restic/restic/internal/ui/progress.(*Counter).run(0x1824270)
        /home/beta/restic.git/internal/ui/progress/counter.go:90 +0x6c
created by github.com/restic/restic/internal/ui/progress.New
        /home/beta/restic.git/internal/ui/progress/counter.go:46 +0x10c
```

What backend/server/service did you use to store the repository?
--------------------------
I used restic rest-server to store the repo

**Comment by fd0** [comment]
@greatroar can you please have a look? I had a quick look at the code but it looks correct. IMHO we should switch to using a mutex instead of using the `atomic` package. Thoughts? :)

**Comment by demlak** [comment]
Maybe related: it is a "cubietruck 2" with 1GB RAM

**Comment by MichaelEischer** [comment]
@demlak Did you see a progress bar initially or did restic crash immediately?

**Comment by MichaelEischer** [comment]
@demlak Can you try to apply the following diff (just move the `value   uint64` line first in the struct)
```diff
diff --git a/internal/ui/progress/counter.go b/internal/ui/progress/counter.go
index a27a3857..d634605e 100644
--- a/internal/ui/progress/counter.go
+++ b/internal/ui/progress/counter.go
@@ -20,12 +20,12 @@ type Func func(value uint64, runtime time.Duration, final bool)
 //
 // The Func is also called when SIGUSR1 (or SIGINFO, on BSD) is received.
 type Counter struct {
+       value   uint64
        report  Func
        start   time.Time
        stopped chan struct{} // Closed by run.
        stop    chan struct{} // Close to stop run.
        tick    *time.Ticker
-       value   uint64
 }
 
 // New starts a new Counter.
```

**Comment by MichaelEischer** [comment]
I've reproduced the crash on my raspberrypi. The previous code snippet fixes the crash.
