### ISSUE TITLE
Segmentation violation during prune

### ISSUE THREAD

**Issue by huyz** [restic/restic#3288]
Output of `restic version`
--------------------------
`restic 0.11.0 compiled with go1.15.6 on darwin/amd64`
(installed via MacPorts)

How did you run restic exactly?
-------------------------------

```shellsession
# env | fgrep RESTIC
RESTIC_REPOSITORY=/ext1/restic-repo
RESTIC_PASSWORD_COMMAND=security find-generic-password -a mac_user -s restic -w /Library/Keychains/System.keychain
# restic prune
repository 12e94841 opened successfully, password is correct
counting files in repo
building new index for repo
[1:30:17] 100.00%  189452 / 189452 packs
incomplete pack file (will be removed): 32c5fceab67582c9de9ec6bada97248b6af54cea1d4240d3ae2e3de4aa3b2abd
incomplete pack file (will be removed): 37bc8f275f8c3f28bc086a71d4983a6fff2f765047617deb4f3f5bf405136885
incomplete pack file (will be removed): 65954e1d891d49dc7bee4f5b4e1a286a74a96d833200cf58504614ae965f6e9f
repository contains 189449 packs (7506776 blobs) with 876.640 GiB
processed 7506776 blobs: 55142 duplicate blobs, 3.966 GiB duplicate
load all snapshots
find data that is still in use for 49 snapshots
[0:00] 0.00%  0 / 49 snapshots
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13905fe]

goroutine 1 [running]:
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0x7af770b98afdc353, 0x8e95e56895f84bfb, 0x4fac16a3914b2fa5, 0x5bbf93d793e1949e, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x1fe
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0xc734330087b05bfb, 0x61ce20bf469ea0c5, 0x6d694b79893d2333, 0x955e3e67b97df579, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0xbaa6c7732516253c, 0xbd6da50438857621, 0xfbd0684de01915fd, 0xd70d8ee55b4c3d32, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0x512fd3b52651c7e9, 0x1f07697e5a47054e, 0x728f7e37296683d6, 0x2c69b7e97a842de6, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0x351ff126865ed536, 0xd3bd12bd6a3e0e60, 0x59c988f45d6b49fd, 0xf021dc526ae5654d, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0xdece2bf2fe6c7330, 0x5cce24f0a352c4fb, 0xb948b37d73a8829c, 0x12b8d74abca2bbe5, 0xc02e1e2fc0, 0x0, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
github.com/restic/restic/internal/restic.FindUsedBlobs(0x1cb2b00, 0xc0004f8380, 0x1c9b460, 0xc000334000, 0x3c6f82534bf71f11, 0x4534ac3f06e8695, 0xb7070b44442a9425, 0x5cf159606a404d74, 0xc02e1e2fc0, 0x13e0519, ...)
	github.com/restic/restic/internal/restic/find.go:31 +0x274
main.getUsedBlobs(0xc000038012, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc00003c018, 0x55, 0x0, 0x0, ...)
	github.com/restic/restic/cmd/restic/cmd_prune.go:276 +0x2d8
main.pruneRepository(0xc000038012, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc00003c018, 0x55, 0x0, 0x0, ...)
	github.com/restic/restic/cmd/restic/cmd_prune.go:158 +0xbb8
main.runPrune(0xc000038012, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc00003c018, 0x55, 0x0, 0x0, ...)
	github.com/restic/restic/cmd/restic/cmd_prune.go:62 +0x18f
main.glob..func19(0x2230be0, 0x226fa58, 0x0, 0x0, 0x0, 0x0)
	github.com/restic/restic/cmd/restic/cmd_prune.go:27 +0x58
github.com/spf13/cobra.(*Command).execute(0x2230be0, 0x226fa58, 0x0, 0x0, 0x2230be0, 0x226fa58)
	github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x2231d60, 0xc0004e67f0, 0x4, 0x10)
	github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	github.com/restic/restic/cmd/restic/main.go:98 +0x3f
```

What backend/server/service did you use to store the repository?
----------------------------------------------------------------

Repo is local (external portable HDD via USB3).  Source files are on internal SSD and external portable SSD.

Expected behavior
-----------------

Prune succeeds without exception.

Actual behavior
---------------

Exception is thrown and I don't know if there still remains stuff to be pruned or not.

Steps to reproduce the behavior
-------------------------------

It all started when my backup started much longer than usual.  My logs would show:

```shellsession
open repository
lock repository
load index files
using parent snapshot d10415de
start scan on [/Users /Library /usr /opt /private/var/root /private/etc]
start backup on [/Users /Library /usr /opt /private/var/root /private/etc]
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 552.330144ms: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 1.080381816s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 1.31013006s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 1.582392691s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 2.340488664s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 4.506218855s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 3.221479586s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 5.608623477s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 7.649837917s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 0, 0) returned error, retrying after 15.394871241s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 507.606314ms: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 985.229971ms: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 803.546856ms: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 1.486109007s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 2.070709754s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 3.67875363s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 4.459624189s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 6.775444383s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 15.10932531s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
Load(<data/18fa61f682>, 2102, 289975) returned error, retrying after 13.811796615s: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
error: tree 41a2758b2d9b834f37b0a4c5d3585e6e9a03e411d94e4262d20d2d12d093ccf2 could not be loaded; the repository could be damaged: open /ext1/restic-repo/data/18/18fa61f682ab9bbbbec24257dc27bea81c1997beaf5300c2b3d138fac550e706: no such file or directory
scan finished in 700.986s: 2838282 files, 269.024 GiB

Files:       2838298 new,     0 changed,     0 unmodified
Dirs:        645908 new,     0 changed,     0 unmodified
Data Blobs:  36289 new
Tree Blobs:  21434 new
Added to the repo: 7.168 GiB

processed 2838298 files, 269.123 GiB in 1:26:48
snapshot 831334f2 saved
Warning: failed to read all source data during backup
my-backup-script: error: while running restic backup /
my-backup-script: exit status 3 ❌
```

The next backup invocation was even worse, with even more such errors and timeouts. So much so that I just interrupted it after 8+ hours.

At this time, my theory as to what started the corruption is that, several times in the past, I've accidentally ejected my portable HDD, which contains the repo, while the backup was running.

So I decided to try `restic rebuild-index`.

That didn't help (and that might have made things worse), ~~as I couldn't `restic mount` without error~~ but I don't remember how I concluded that.

So I ran `restic repair` from https://github.com/restic/restic/pull/2876 , which seemed to work out ok: I'm able to `backup` cleanly now without errors and without timeouts.  I'm also able to do `forget`.

But now, `prune` keeps seg-faulting.  And I don't know how to proceed except wiping out the repo and starting from scratch.

Do you have any idea what may have caused this?
-----------------------------------------------

I'm not sure.  Repo corruption could have started from ejecting target HDD during backups, then further corruption with `rebuild-index`, then possible bugs in `repair` from the yet-unapproved PR.  Finally, `prune` should of course never segfault, so that's clearly a bug there.

Do you have an idea how to solve the issue?
-------------------------------------------

I'm not familiar with Go and why it segfaults.  I thought segfaults were a thing of the past ;)

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

Yeah restic is great.  restic + rclone + cloud storage are a wonderful solution to backups.

**Comment by fd0** [comment]
I think this is already resolved with the completely reworked code for `prune` in 0.12.0 we've released a few days ago, would you mind retrying with that version?

**Comment by huyz** [comment]
0.12.0 worked, thanks!

```
# /usr/local/bin/restic prune
repository 12e94841 opened successfully, password is correct
loading indexes...
loading all snapshots...
finding data that is still in use for 49 snapshots
[2:25] 100.00%  49 / 49 snapshots
searching used packs...
collecting packs for deletion and repacking
[10:50] 100.00%  188743 / 188743 packs processed

to repack:      1850928 blobs / 8.253 GiB
this removes     879433 blobs / 5.749 GiB
to delete:      1600644 blobs / 66.477 GiB
total prune:    2480077 blobs / 72.225 GiB
remaining:      4993429 blobs / 804.151 GiB
unused size after prune: 27.453 GiB (3.41% of remaining size)

deleting unreferenced packs
[0:04] 100.00%  709 / 709 files deleted
repacking packs
[4:48] 71.29%  1363 / 1912 packs repacked
[6:52] 100.00%  1912 / 1912 packs repacked
rebuilding index
[0:27] 100.00%  173310 / 173310 packs processed
deleting obsolete index files
[0:07] 100.00%  119 / 119 files deleted
removing 16012 old packs
[6:36] 100.00%  16012 / 16012 files deleted
done
```

**Comment by fd0** [comment]
Thanks for the feedback!
