### ISSUE TITLE
Panic: check backup without snapshots

### ISSUE THREAD

**Issue by C-Otto** [restic/restic#3296]
I just created a new restic repository but haven't created any snapshot, yet. The check invocation failed:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.selectRandomPacksByPercentage(0xc00007c960, 0x3fc3333333333333, 0x3fc3333333333333)
        /restic/cmd/restic/cmd_check.go:349 +0x4d0                                      
main.runCheck(0xc0003a9900, 0x7fff92507ef8, 0x5, 0xc0003b0000, 0x7fff92507ec6, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
        /restic/cmd/restic/cmd_check.go:299 +0x1206
main.glob..func5(0x16590c0, 0xc00038ea40, 0x0, 0x4, 0x0, 0x0)
        /restic/cmd/restic/cmd_check.go:35 +0xcc
github.com/spf13/cobra.(*Command).execute(0x16590c0, 0xc0003b67e0, 0x4, 0x6, 0x16590c0, 0xc0003b67e0)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x47c                   
github.com/spf13/cobra.(*Command).ExecuteC(0x165bb40, 0xc00037d6c0, 0x2, 0x8)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/build/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /restic/cmd/restic/main.go:98 +0x3f
```

This is with restic 0.12.0 on Linux amd64.

**Comment by aawsome** [comment]
@fgma This seems to be a bug in the `--read-data-subset=x%` part. Do you want to have a look at it?

**Comment by C-Otto** [comment]
Oh, you're right. My invocation is with `-q check --read-data-subset=0.15%`.
