### ISSUE TITLE
panic while writing to Synology SFTP server

### ISSUE THREAD

**Issue by rikvdh** [restic/restic#357]
Hi,

I'm trying to use restic to backup to my Synology server via SFTP. But it fails.
This is what I get:

```
root@srv01 ~ $ restic -r sftp://backup/home/test2 init
enter password for new backend:
enter password again:
created restic backend b52401ce42 at sftp://backup/home/test2

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.
root@srv01 ~ $ restic -r sftp://backup/home/test2 backup go1.5.1.linux-amd64.tar.gz
enter password for repository:
scan [/root/go1.5.1.linux-amd64.tar.gz]
scanned 0 directories, 1 files in 0:00
panic: sftp: renameFile: write |1: broken pipe8 MiB  0 / 1 items  0 errors  ETA 0:01

goroutine 102 [running]:
github.com/restic/restic.(*Archiver).saveChunk(0xc820062b00, 0xc8200129c0, 0xc8200cc0c0, 0xc820076298, 0xc82009a870)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:135 +0x2f9
created by github.com/restic/restic.(*Archiver).SaveFile
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:207 +0x461

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8200104dc)
        /usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*WaitGroup).Wait(0xc8200104d0)
        /usr/local/go/src/sync/waitgroup.go:126 +0xb4
github.com/restic/restic.(*Archiver).Snapshot(0xc820062b00, 0xc8200cc0c0, 0xc820067a80, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:665 +0x8d0
main.CmdBackup.Execute(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb794e0, 0xc820062440, 0x1, 0x4, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/cmd_backup.go:326 +0xf61
main.(*CmdBackup).Execute(0xc820062380, 0xc820062440, 0x1, 0x4, 0x0, 0x0)
        <autogenerated>:12 +0xc9
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820078870, 0xc820078010, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/jessevdk/go-flags/parser.go:278 +0x8e3
github.com/jessevdk/go-flags.(*Parser).Parse(0xc820078870, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/jessevdk/go-flags/parser.go:154 +0x9b
main.main()
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/main.go:26 +0x1bf

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37


goroutine 21 [chan receive]:
github.com/restic/restic.init.1.func1.1()
        /tmp/restic-build-808544303/src/github.com/restic/restic/lock.go:262 +0x16f
created by github.com/restic/restic.init.1.func1
        /tmp/restic-build-808544303/src/github.com/restic/restic/lock.go:265 +0x2b

goroutine 3 [select, locked to thread]:
runtime.gopark(0x9fc338, 0xc820026f28, 0x9235e0, 0x6, 0x44e618, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820026f28, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820026f28)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 22 [chan receive]:
main.CleanupHandler(0xc8200640c0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/cleanup.go:58 +0x7b
created by main.init.1
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/cleanup.go:25 +0x12a

goroutine 8 [select]:
main.refreshLocks(0xb793e0, 0xc8200169c0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/lock.go:69 +0x434
created by main.lockRepository
        /tmp/restic-build-808544303/src/github.com/restic/restic/cmd/restic/lock.go:46 +0x196

goroutine 106 [runnable]:
github.com/pkg/sftp.(*Client).sendRequest(0xc820078aa0, 0x7f3c07bdb908, 0xc821742ec0, 0xc82af894f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:569 +0xd0
github.com/pkg/sftp.(*Client).Lstat(0xc820078aa0, 0xc820064ae0, 0x12, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:267 +0x103
github.com/restic/restic/backend/sftp.(*SFTP).mkdirAll(0xc820093580, 0xc820064ae0, 0x12, 0x1c0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:171 +0x5f
github.com/restic/restic/backend/sftp.(*SFTP).renameFile(0xc820093580, 0xc82007a030, 0x28, 0x921608, 0x4, 0xc82001ba80, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:207 +0x12c
github.com/restic/restic/backend/sftp.(*sftpBlob).Finalize(0xc82007a480, 0x921608, 0x4, 0xc82001ba80, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:252 +0x1fb
github.com/restic/restic/repository.(*Repository).savePacker(0xc820056070, 0xc82000a500, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:262 +0x277
github.com/restic/restic/repository.(*Repository).SaveAndEncrypt(0xc820056070, 0xc820106900, 0xc82041a000, 0x25b085, 0x3ffe00, 0xc821743100, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:346 +0xb9c
github.com/restic/restic/repository.(*Repository).SaveFrom(0xc820056070, 0x2735a68d12653600, 0xc821743100, 0x25b085, 0x7f3c08c19428, 0xc820106900, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:361 +0x3e8
github.com/restic/restic.(*Archiver).Save(0xc820062b00, 0x35a68d1265367600, 0x2118234eec495b27, 0x69077266a5ac3732, 0xe44d3c19fd0e03b6, 0xc82411d73f, 0x25b085, 0x7f3c08c19428, 0xc8
20106900, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:71 +0x41c
github.com/restic/restic.(*Archiver).saveChunk(0xc820062b00, 0xc8288a3ec0, 0xc8200cc0c0, 0xc820076298, 0xc8203743f0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:132 +0x2b1
created by github.com/restic/restic.(*Archiver).SaveFile
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:207 +0x461


goroutine 30 [select]:
github.com/restic/restic.(*Progress).reporter(0xc8200cc0c0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/progress.go:127 +0x20a
created by github.com/restic/restic.(*Progress).Start
        /tmp/restic-build-808544303/src/github.com/restic/restic/progress.go:66 +0x14d

goroutine 50 [chan receive]:
github.com/restic/restic.waitForResults(0xc8200e5400, 0x33, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:147 +0x112
github.com/restic/restic.(*Archiver).SaveFile(0xc820062b00, 0xc8200cc0c0, 0xc8200ba3c0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:211 +0x29e
github.com/restic/restic.(*Archiver).fileWorker(0xc820062b00, 0xc8200104d0, 0xc8200cc0c0, 0xc820064f00, 0xc8200651a0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:282 +0x12a0
created by github.com/restic/restic.(*Archiver).Snapshot
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:653 +0x774

goroutine 51 [chan receive]:
github.com/restic/restic.(*Archiver).dirWorker(0xc820062b00, 0xc8200104d0, 0xc8200cc0c0, 0xc820064f00, 0xc820065200)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:333 +0x69f
created by github.com/restic/restic.(*Archiver).Snapshot
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:654 +0x7cd

goroutine 122 [runnable]:
github.com/pkg/sftp.(*Client).sendRequest(0xc820078aa0, 0x7f3c07bdb908, 0xc823e79ac0, 0xc82ce7b4f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:569 +0xd0
github.com/pkg/sftp.(*Client).Lstat(0xc820078aa0, 0xc820016f00, 0x12, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:267 +0x103
github.com/restic/restic/backend/sftp.(*SFTP).mkdirAll(0xc820093580, 0xc820016f00, 0x12, 0x1c0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:171 +0x5f
github.com/restic/restic/backend/sftp.(*SFTP).renameFile(0xc820093580, 0xc820012150, 0x28, 0x921608, 0x4, 0xc82001ba00, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:207 +0x12c
github.com/restic/restic/backend/sftp.(*sftpBlob).Finalize(0xc820012210, 0x921608, 0x4, 0xc82001ba00, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:252 +0x1fb
github.com/restic/restic/repository.(*Repository).savePacker(0xc820056070, 0xc820078500, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:262 +0x277
github.com/restic/restic/repository.(*Repository).SaveAndEncrypt(0xc820056070, 0xc82007a000, 0xc82b70e000, 0x119ad7, 0x1ffe00, 0xc8242519a0, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:346 +0xb9c
github.com/restic/restic/repository.(*Repository).SaveFrom(0xc820056070, 0x6f10ec3bf5baad00, 0xc8242519a0, 0x119ad7, 0x7f3c08c19428, 0xc82007a060, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:361 +0x3e8
github.com/restic/restic.(*Archiver).Save(0xc820062b00, 0x10ec3bf5baad3a00, 0x8e29d7ef6c8b376f, 0xbb1d7291e5df852f, 0x8ab31a732e7a4fda, 0xc82411d70e, 0x119ad7, 0x7f3c08c19428, 0xc8
2007a060, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:71 +0x41c
github.com/restic/restic.(*Archiver).saveChunk(0xc820062b00, 0xc8288a2b40, 0xc8200cc0c0, 0xc820076298, 0xc8203747e0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:132 +0x2b1
created by github.com/restic/restic.(*Archiver).SaveFile
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:207 +0x461

goroutine 70 [select]:
github.com/restic/restic.(*Archiver).saveIndexes(0xc820062b00, 0xc8200104e0, 0xc820065260)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:564 +0x434
created by github.com/restic/restic.(*Archiver).Snapshot
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:661 +0x880

goroutine 118 [runnable]:
ithub.com/pkg/sftp.(*Client).sendRequest(0xc820078aa0, 0x7f3c07bdb908, 0xc823e79a00, 0xc82413d4f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:569 +0xd0
github.com/pkg/sftp.(*Client).Lstat(0xc820078aa0, 0xc820016b40, 0x12, 0x0, 0x0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:267 +0x103
github.com/restic/restic/backend/sftp.(*SFTP).mkdirAll(0xc820093580, 0xc820016b40, 0x12, 0x1c0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:171 +0x5f
github.com/restic/restic/backend/sftp.(*SFTP).renameFile(0xc820093580, 0xc820012fc0, 0x28, 0x921608, 0x4, 0xc820108900, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:207 +0x12c
github.com/restic/restic/backend/sftp.(*sftpBlob).Finalize(0xc8200136e0, 0x921608, 0x4, 0xc820108900, 0x40, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:252 +0x1fb
github.com/restic/restic/repository.(*Repository).savePacker(0xc820056070, 0xc8200793b0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:262 +0x277
github.com/restic/restic/repository.(*Repository).SaveAndEncrypt(0xc820056070, 0xc8288a2600, 0xc825ad2000, 0x13ee74, 0x1ffe00, 0xc823e78b40, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:346 +0xb9c
github.com/restic/restic/repository.(*Repository).SaveFrom(0xc820056070, 0xe16abb4d255cce00, 0xc823e78b40, 0x13ee74, 0x7f3c08c19428, 0xc8288a2630, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:361 +0x3e8
github.com/restic/restic.(*Archiver).Save(0xc820062b00, 0x6abb4d255ccea000, 0xe2003227d93193e1, 0x371a71bbba30c7db, 0xbcc4655083299893, 0xc82411d7f0, 0x13ee74, 0x7f3c08c19428, 0xc8
288a2630, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:71 +0x41c
github.com/restic/restic.(*Archiver).saveChunk(0xc820062b00, 0xc8288a2600, 0xc8200cc0c0, 0xc820076298, 0xc8203745a0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:132 +0x2b1
created by github.com/restic/restic.(*Archiver).SaveFile
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:207 +0x461

goroutine 120 [runnable]:
github.com/pkg/sftp.(*File).Write(0xc820101dd0, 0xc82424f304, 0x0, 0x4, 0x431268, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/pkg/sftp/client.go:896 +0x3e4
github.com/restic/restic/backend/sftp.(*sftpBlob).Write(0xc820101e00, 0xc82424f300, 0x4, 0x8, 0x8, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/sftp/sftp.go:261 +0x4e
io.(*multiWriter).Write(0xc820092f60, 0xc82424f300, 0x4, 0x8, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/multi.go:43 +0xda
github.com/restic/restic/backend.(*HashingWriter).Write(0xc820101e30, 0xc82424f300, 0x4, 0x8, 0x6a, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/backend/writer.go:63 +0x6a
encoding/binary.Write(0x7f3c07bdcca8, 0xc820101e30, 0x7f3c08c2c0c0, 0xb9e9b8, 0x7cba20, 0xc82424f2f0, 0x0, 0x0)
        /usr/local/go/src/encoding/binary/binary.go:304 +0x22e
github.com/restic/restic/pack.(*Packer).Finalize(0xc8200794f0, 0x43aaad, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/pack/pack.go:151 +0x347
github.com/restic/restic/repository.(*Repository).savePacker(0xc820056070, 0xc8200794f0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:255 +0x152
github.com/restic/restic/repository.(*Repository).SaveAndEncrypt(0xc820056070, 0xc8288a2a00, 0xc821286000, 0x2c2d5a, 0x3ffe00, 0xc823e78d80, 0x0, 0x0, 0x0, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:346 +0xb9c
github.com/restic/restic/repository.(*Repository).SaveFrom(0xc820056070, 0x59c41ac68ea2f100, 0xc823e78d80, 0x2c2d5a, 0x7f3c08c19428, 0xc8288a2ab0, 0x0, 0x0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/repository/repository.go:361 +0x3e8
github.com/restic/restic.(*Archiver).Save(0xc820062b00, 0xc41ac68ea2f13800, 0x796b3f30a905c159, 0x5990da5ce8866218, 0x229190137388f7a3, 0x84, 0x2c2d5a, 0x7f3c08c19428, 0xc8288a2ab0
, 0x0, ...)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:71 +0x41c
github.com/restic/restic.(*Archiver).saveChunk(0xc820062b00, 0xc8288a2a80, 0xc8200cc0c0, 0xc820076298, 0xc8203746c0)
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:132 +0x2b1
created by github.com/restic/restic.(*Archiver).SaveFile
        /tmp/restic-build-808544303/src/github.com/restic/restic/archiver.go:207 +0x461
```

**Comment by rikvdh** [comment]
Ow, i found out that when I add a second slash after the hostname resolves the issue. The use of this extra slash is very odd. Perhaps it is better to use the scp-/rsync-like semi-colon for the URI.

Also crashing restic should never be the result. When I init with an single slash the folders are created correctly, but the config isn't created.

**Comment by xor-gate** [comment]
I think we should conform the sftp URI scheme as the IETF draft here:
https://tools.ietf.org/html/draft-ietf-secsh-scp-sftp-ssh-uri-04#section-4.3

**Comment by fd0** [comment]
Thanks for pointing this out, we need to work on the URL parsing in general, cf #339

**Comment by fd0** [comment]
This is resolved, we now accept the `sftp:host:/path` style backend specifications. I'm closing this issue.
