### ISSUE TITLE
Restic is stuck opening backblaze repository

### ISSUE THREAD

**Issue by howesteve** [restic/restic#3859]
Hello,

So I was running my backup script like I do for years, but about a week ago it started getting stuck. It uses backblaze b2. I had no restic update, no changes in command line, and no known backblaze changes. This is my actual command line as I always used it; I just added "--verbose" in hope of a better error message, but no luck.
It simply freezes on "open repository".
```
howe@gargamel ~ % restic backup --verbose -e __debug_bin -e node_modules -e .pnpm-store -e .cache  \
  ~/Documents \
  /HD1/Music /HD1/Books /HD1/Pictures \
  /mnt/howe_private/ \
  ~/.zshrc ~/.zsh_history \~/.psqlrc ~/.antigen ~/.alacritty.yml \
  ~/.config/micro ~/.config/Notepadqq ~/.config/doublecmd ~/.config/rclone ~/.config/xfce4 \
  /etc/fstab

~/.psqlrc does not exist, skipping
/home/howe/.alacritty.yml does not exist, skipping
/home/howe/.config/rclone does not exist, skipping
open repository
```

Any suggestions, please?

Howe

**Comment by rawtaz** [comment]
Might be the same as in #3796. Please send restic a SIGABRT and upload the log/stack trace somewhere, thanks!

**Comment by howesteve** [comment]
> Might be the same as in #3796. Please send restic a SIGABRT and upload the log/stack trace somewhere, thanks!

Here it goes. Thanks.

```
open repository
SIGABRT: abort
PC=0x558af0f1a401 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex()
	runtime/sys_linux_amd64.s:552 +0x21
runtime.futexsleep(0x10000000000?, 0x0?, 0x4?)
	runtime/os_linux.go:66 +0x36
runtime.notesleep(0x558af2258dc8)
	runtime/lock_futex.go:159 +0x87
runtime.mPark(...)
	runtime/proc.go:1449
runtime.stopm()
	runtime/proc.go:2228 +0x8d
runtime.findrunnable()
	runtime/proc.go:2804 +0x865
runtime.schedule()
	runtime/proc.go:3187 +0x239
runtime.park_m(0xc000103520?)
	runtime/proc.go:3336 +0x14d
runtime.mcall()
	runtime/asm_amd64.s:425 +0x45

goroutine 1 [select]:
github.com/kurin/blazer/b2.withBackoff({0x558af1cb2100, 0xc000282740}, {0x558af1cb54e8, 0xc0002e2120}, 0xc00079e588)
	github.com/kurin/blazer@v0.5.4-0.20211030221322-ba894c124ac6/b2/backend.go:762 +0x131
github.com/kurin/blazer/b2.(*beRoot).authorizeAccount(0x558af0ec13a5?, {0x558af1cb2100?, 0xc000282740?}, {0xc00003404e?, 0x7f433649b5a8?}, {0xc00003a10f?, 0x7f4336499ba0?}, {0xc0002d8280, {0x558af1cac118, 0xc00020d7a0}, ...})
	github.com/kurin/blazer@v0.5.4-0.20211030221322-ba894c124ac6/b2/backend.go:182 +0xed
github.com/kurin/blazer/b2.NewClient({0x558af1cb2100, 0xc000282740}, {0xc00003404e, 0xc}, {0xc00003a10f, 0x2a}, {0xc00045e808, 0x1, 0x1})
	github.com/kurin/blazer@v0.5.4-0.20211030221322-ba894c124ac6/b2/b2.go:71 +0x44e
github.com/restic/restic/internal/backend/b2.newClient({0x558af1cb2100, 0xc000282740}, {{0xc00003404e, 0xc}, {0xc00003a10f, 0x2a}, {0xc00003c0a5, 0x10}, {0x0, 0x0}, ...}, ...)
	github.com/restic/restic/internal/backend/b2/b2.go:37 +0xcd
github.com/restic/restic/internal/backend/b2.Open({0x558af1cb2100?, 0xc000282380?}, {{0xc00003404e, 0xc}, {0xc00003a10f, 0x2a}, {0xc00003c0a5, 0x10}, {0x0, 0x0}, ...}, ...)
	github.com/restic/restic/internal/backend/b2/b2.go:51 +0x137
main.open({_, _}, {{0xc00003c0a2, 0x13}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	github.com/restic/restic/cmd/restic/global.go:710 +0x310
main.OpenRepository({{0xc00003c0a2, 0x13}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
	github.com/restic/restic/cmd/restic/global.go:421 +0x98
main.runBackup({{0x0, 0x0}, 0x0, {0xc00028e880, 0x5, 0x8}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
	github.com/restic/restic/cmd/restic/cmd_backup.go:524 +0x2be
main.glob..func2(0x558af2249220?, {0xc0002e6380, 0x10, 0x1b})
	github.com/restic/restic/cmd/restic/cmd_backup.go:61 +0x15a
github.com/spf13/cobra.(*Command).execute(0x558af2249220, {0xc0002e61c0, 0x1b, 0x1c})
	github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0x558af22480a0)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	github.com/restic/restic/cmd/restic/main.go:98 +0x32

goroutine 4 [chan receive, 1 minutes]:
github.com/restic/restic/internal/restic.init.0.func1.1()
	github.com/restic/restic/internal/restic/lock.go:250 +0x77
created by github.com/restic/restic/internal/restic.init.0.func1
	github.com/restic/restic/internal/restic/lock.go:247 +0x25

goroutine 19 [syscall, 1 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:151 +0x2f
os/signal.loop()
	os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	os/signal/signal.go:151 +0x2a

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000f4700)
	go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x8d

goroutine 7 [chan receive, 1 minutes]:
main.CleanupHandler(0x0?)
	github.com/restic/restic/cmd/restic/cleanup.go:59 +0x39
created by main.init.0
	github.com/restic/restic/cmd/restic/cleanup.go:21 +0x8b

goroutine 49 [select, 1 minutes]:
github.com/restic/restic/internal/ui/termstatus.(*Terminal).run(0xc00020a780, {0x558af1cb2100, 0xc0001a0000})
	github.com/restic/restic/internal/ui/termstatus/status.go:103 +0x125
github.com/restic/restic/internal/ui/termstatus.(*Terminal).Run(0xc0002f2000?, {0x558af1cb2100?, 0xc0001a0000?})
	github.com/restic/restic/internal/ui/termstatus/status.go:92 +0x68
main.glob..func2.1()
	github.com/restic/restic/cmd/restic/cmd_backup.go:59 +0x45
gopkg.in/tomb%2ev2.(*Tomb).run(0xc0002f2000, 0x0?)
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x36
created by gopkg.in/tomb%2ev2.(*Tomb).Go
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xee

rax    0xca
rbx    0x0
rcx    0x558af0f1a403
rdx    0x0
rdi    0x558af2258dc8
rsi    0x80
rbp    0x7fff385a2e50
rsp    0x7fff385a2e08
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x0
r13    0x6
r14    0x558af22586e0
r15    0x0
rip    0x558af0f1a401
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by rawtaz** [comment]
I guess it's the same type of issue, but someone with more experience will have to verify that.

**Comment by MichaelEischer** [comment]
That rather looks like one of the other issues with stuck B2 clients.

Likely either the application key broke for some reason, there is something wrong with the certificates installed at your host or some DNS filter routes B2 to nowhere. Have a look at https://github.com/restic/restic/issues/3824#issuecomment-1186248977 .

Maybe we should think about deprecating or dropping the B2 backend in restic (or maybe someone is interested in rewriting the backend using a different B2 library, maybe https://github.com/kothar/go-backblaze/tree/master).

Backblaze offers a S3 compatible API and the S3 integration in restic actually returns errors if something is wrong. To setup B2 using the S3 API look at https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API . Just make sure to setup lifecycle rules to eventually delete hidden files.
