### ISSUE TITLE
Check Timestamps, efficient backup

### ISSUE THREAD

**Issue by scoddy** [restic/restic#4]
If a user initiates a backup, availability of previous snapshots shall be verified. Based on the snapshot, local verification shall take place wether new backup for a particular file or directory is required.

**Comment by scoddy** [comment]
initial backup: 

```
[25:51] 100.00%  53.847 MiB/s  81.559 GiB / 81.559 GiB  75136 / 75136 items  ETA 90752349:58:33
duration: 25:51, 53.85MiB/s
snapshot fee36b74 saved
```

incremental backup:

```
./restic -r /mnt/usb/backup backup  /home/fd/ fee36b74
Enter Password for Repository: 
found parent snapshot fee36b741ac34ba78f1b291763c0fc50f533ab514ac175ef78e6ae9c31973220
scan /home/fd/
[0:06] 9601 directories, 61866 files, 80.977 GiB
Done in 0:06
load old snapshot
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x49e952]

goroutine 1 [running]:
github.com/restic/restic.Tree.CopyFrom(0xc20c6e3100, 0x11, 0x20, 0xc20b293960, 0xc211bc0780, 0xf, 0x13, 0xc20f4a8f00, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/restic/restic/tree.go:156 +0x732
github.com/restic/restic.Tree.CopyFrom(0xc20dba1400, 0x74, 0x80, 0xc20b293960, 0xc20a8f4000, 0x74, 0x8d, 0xc20f4a8f00, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/restic/restic/tree.go:156 +0x548
github.com/restic/restic.Tree.CopyFrom(0xc20c527a30, 0x1, 0x1, 0xc20b293960, 0xc20b7f8560, 0x1, 0x4, 0xc20f4a8f00, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/restic/restic/tree.go:156 +0x548
main.CmdBackup.Execute(0xc20802e500, 0x2, 0x5, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/restic/restic/cmd/restic/cmd_backup.go:138 +0xa8e
main.(*CmdBackup).Execute(0x7c69c8, 0xc20802e500, 0x2, 0x5, 0x0, 0x0)
	<autogenerated>:2 +0xc7
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc20802e4b0, 0xc20800a010, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/jessevdk/go-flags/parser.go:278 +0x8c1
github.com/jessevdk/go-flags.(*Parser).Parse(0xc20802e4b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/fd/tmp/restic/src/github.com/jessevdk/go-flags/parser.go:154 +0xb1
main.main()
	/home/fd/tmp/restic/src/github.com/restic/restic/cmd/restic/main.go:169 +0x72

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
[1]    17195 exit 2     ./restic -r /mnt/usb/backup backup /home/fd/ fee36b74
```
test not successful
