### ISSUE TITLE
Restic doesn't save extended attributes, in the system namespace, on Linux

### ISSUE THREAD

**Issue by vmlemon** [restic/restic#5111]
Output of `restic version`
--------------------------
restic 0.17.1 compiled with go1.23.1 on linux/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Local file system

Problem description / Steps to reproduce
----------------------------------------

Mount an NTFS file system, containing extended attributes (not the same as NTFS streams), from OS/2, Interix, WSL, or CygWin, using NTFS-3G (I'm using ntfs-3g 2021.8.22, on Ubuntu 22.04), and run a Restic backup, on the mounted volume.

Expected behavior
-----------------

I would expect that _at least_ the ```system.ntfs_ea```, ```system.ntfs_attrib_be```, and ```system.ntfs_times ```, containing data such as the following, is preserved:

```
# file: tmp/2/
system.ntfs_times=0sfmGf1zrUygFsejQEO9TKAcbcNgQ71MoBbHo0BDvUygE=
# file: tmp/2/
system.ntfs_acl=0sAQAEgDAAAABAAAAAAAAAABQAAAACABwAAQAAAAADFAD/AR8AAQEAAAAAAAEAAAAAAQIAAAAAAAUgAAAAIAIAAAECAAAAAAAFIAAAACACAAA=
# file: tmp/2/
system.ntfs_attrib_be=0sAAAAFg==
# file: tmp/2/http!!!www.google.com
system.ntfs_ea=0sMAAAAAAFIAAuVFlQRQDf/wAAAQD9/xYAVW5pZm9ybVJlc291cmNlTG9jYXRvcgAALAAAAAAJGQAuTE9OR05BTUUA/f8VAGh0dHA6Ly93d3cuZ29vZ2xlLmNvbQAkAAAAAAgQAC5TVUJKRUNUAP3/DABWaXNpdCBHb29nbGUAAAAwAAAAAAkeAC5DT01NRU5UUwDf/wAAAQD9/xQAQSBzaG9ydGN1dCB0byBHb29nbGUkAAAAAAsQAC5LRVlQSFJBU0VTAN//AAABAP3/BgBHb29nbGU=
# file: tmp/2/CARDFILE.CRD
system.ntfs_ea=0sIAAAAAAIDwAuU1VCSkVDVAD9/wsATXkgQ2FyZEZpbGUwAAAAAAkdAC5DT01NRU5UUwDf/wAAAQD9/xMAQ29udGFpbnMgb25lIHJlY29yZAA0AAAAAAsdAC5LRVlQSFJBU0VTAN//AAACAP3/BwBXaW5kb3dz/f8IAENhcmRGaWxlAAAA
```

Other extended attributes, for NTFS-3G are documented, at https://github.com/tuxera/ntfs-3g/wiki/Using-Extended-Attributes

Actual behavior
---------------

These attributes don't exist, when browsing the mounted Restic repository:

```
getfattr: Removing leading '/' from absolute path names
# file: tmp/2/
system.ntfs_times=0sfmGf1zrUygFsejQEO9TKAcbcNgQ71MoBbHo0BDvUygE=

root@DESKTOP-6HH5CK9:~# getfattr -n system.ntfs_times /tmp/1/tags/Understand/latest/tmp/2/
/tmp/1/tags/Understand/latest/tmp/2/: system.ntfs_times: No such attribute

root@DESKTOP-6HH5CK9:~# getfattr -n system.ntfs_acl /tmp/2/
getfattr: Removing leading '/' from absolute path names
# file: tmp/2/
system.ntfs_acl=0sAQAEgDAAAABAAAAAAAAAABQAAAACABwAAQAAAAADFAD/AR8AAQEAAAAAAAEAAAAAAQIAAAAAAAUgAAAAIAIAAAECAAAAAAAFIAAAACACAAA=

root@DESKTOP-6HH5CK9:~# getfattr -n system.ntfs_acl /tmp/1/tags/Understand/latest/tmp/2/
/tmp/1/tags/Understand/latest/tmp/2/: system.ntfs_acl: No such attribute

root@DESKTOP-6HH5CK9:~# getfattr -n system.ntfs_ea /tmp/2/CARDFILE.CRD
getfattr: Removing leading '/' from absolute path names
# file: tmp/2/CARDFILE.CRD
system.ntfs_ea=0sIAAAAAAIDwAuU1VCSkVDVAD9/wsATXkgQ2FyZEZpbGUwAAAAAAkdAC5DT01NRU5UUwDf/wAAAQD9/xMAQ29udGFpbnMgb25lIHJlY29yZAA0AAAAAAsdAC5LRVlQSFJBU0VTAN//AAACAP3/BwBXaW5kb3dz/f8IAENhcmRGaWxlAAAA

root@DESKTOP-6HH5CK9:~# getfattr -n system.ntfs_ea /tmp/1/tags/Understand/latest/tmp/2/CARDFILE.CRD
/tmp/1/tags/Understand/latest/tmp/2/CARDFILE.CRD: system.ntfs_ea: No such attribute
```

Do you have any idea what may have caused this?
-----------------------------------------------

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------

**Comment by vmlemon** [comment]
I'm kinda perplexed, by the whole thing, to be fair. 

If I create a new repository, add one of my test files to it, and compare the output of ```getfattr -d```, to ```restic cat tree``, I see this:

```
root@DESKTOP-6HH5CK9:/mnt/e# ~/restic_0.17.1_linux_amd64 cat tree 45be638d:/tmp/1 -r TestRepo/ --insecure-no-password
repository 911fce87 opened (version 2, compression level auto)
found 3 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
[0:00] 100.00%  3 / 3 index files loaded
{"nodes":[{"name":"OPENDOC.OD","type":"file","mode":511,"mtime":"2010-04-04T19:22:47+01:00","atime":"2010-04-04T19:22:47+01:00","ctime":"2010-04-04T22:08:47.140625+01:00","uid":0,"gid":0,"user":"root","group":"root","inode":47,"device_id":64512,"size":16104,"links":1,"content":["39177b01afa03852a7cd94c37853b5ca6dca4ae7450e3892616541257b2e3fcd"]}]}
root@DESKTOP-6HH5CK9:/mnt/e# ~/restic_0.17.1_linux_amd64 cat tree 45be638d:/tmp/1/OPENDOC.OD -r TestRepo/ --insecure-no-
password
repository 911fce87 opened (version 2, compression level auto)
found 3 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
[0:00] 100.00%  3 / 3 index files loaded
path tmp/1/OPENDOC.OD: not a directory
root@DESKTOP-6HH5CK9:/mnt/e# getfattr -d /tmp/1/OPENDOC.OD
```

I can definitely see the pseudo(?) EA, if I do this, though:

```
root@DESKTOP-6HH5CK9:/mnt/e# getfattr -n system.ntfs_ea /tmp/1/OPENDOC.OD
getfattr: Removing leading '/' from absolute path names
# file: tmp/1/OPENDOC.OD
system.ntfs_ea=0sKAAAAAAFGgAuVFlQRQDf/wAAAQD9/xAAT3BlbkRvYyBEb2N1bWVudA==
```

I wonder if Linux, and/or FUSE has some sort of mechanism, for dynamically generating xattrs, on-the-fly, without registering them into some sort of master data structure?

The most information, that I can find, is a post, on a Samba-related mailing list (https://lists.samba.org/archive/samba-technical/2016-March/112751.html), from 2016, suggesting trying to mount a volume with ```-o streams_interface=windows```, or  ```-o user_xattr``` (which seems to be a synonym, for the default mode of operation (```-o streams_interface=xattr```)), which doesn't seem to make a difference, when trying to fish for xattrs, using the technique that Restic, and ```getfattr -d``` use...

I guess the best approach, to working around this, would be adding some sort of ```--always-include-xattr``` option, to explicitly try to include one, or more of them, rather than trying to add a platform/FS-specific hack, into Restic, just to grovel for these xattrs?

**Comment by MichaelEischer** [comment]
> I wonder if Linux, and/or FUSE has some sort of mechanism, for dynamically generating xattrs, on-the-fly, without registering them into some sort of master data structure?

The list and get xattr operations are simply forwarded to the FUSE filesystem. So it's trivial for the fs to hide attributes or make a mess. If the list xattr operation does not return the xattrs, then restic can't see it and back it up.

> I guess the best approach, to working around this, would be adding some sort of `--always-include-xattr` option, to explicitly try to include one, or more named xattrs (from the user's argument), rather than trying to add a platform/FS-specific hack, into Restic, just to grovel for these xattrs?

Letting restic by default blindly try to access random xattrs is out of question. And I'm always rather hesitant to add new options as those tend to pile up and interact in unforseen ways. I also don't recall having seen such an option anywhere.

 Is there really no way to make ntfs-3g simply return those xattrs when restic tries to backup a file?

**Comment by vmlemon** [comment]
That's pretty fair, in terms of adding functionality, to Restic, since the responsibility for exposing the metadata is at another VFS layer level - even if it does mean a lack of data integrity, when backing-up/restoring files. 

For what it's worth, the NTFS-3G wiki has the following to say:

```
A few extended attributes in the system name space are used to give access to NTFS internal data which cannot be accessed through Linux standard methods. They can be accessed with any setting of the option streams_interface.

The program ntfscp.c and the shell command ntfscp.sh, available in [tools.zip](https://jp-andre.pagesperso-orange.fr/tools.zip), demonstrate how files can be copied with their internal data.

Being in the system name space, they are not returned when the extended attribute list is queried, and consequently, not copied by standard file management tools.

(The extended attribute mapping described below only applies since ntfs-3g-2010.5.16AR.1) To get the extended attribute copied by standard tools, ntfs-3g has to be compiled with the ./configure option --enable-xattr-mappings and a mapping to an alternate extended attribute in the user name space has to be defined. The standard file defining the mapping is XattrMapping in the hidden directory .NTFS-3G on the root of the NTFS partition. An alternate location may be defined by the mount option xattrmapping=path where path is either a full path on a previously mounted volume or a path relative to the root of the same NTFS partition.

Doing so, the mapped extended attributes will be copied, for instance by tar with option --xattrs, by cp with option --preserve=xattr, by rsync with option -X, etc.

Please note : having standard tools blindly copy attributes may lead to conflicts (ACLs, symbolic links, OIDs, etc.) or undesired behavior (data compression).

The extended attribute mapping file should have a line per mapped attribute with two fields separated by a colon. The first field is the system name, the second is the user name
```

Without locally/upstream patching it, for every user that wants to use Restic, together with NTFS-3G, or manually hunting down the source to the version that ships with Ubuntu, and rebuilding it, I'm unsure if there's a way to forcing it to always expose the attributes, in a reliable way, for every possible situation (including read-only volumes).

I am kinda sceptical, of the claim of not being possible to access the ```system``` namespace, given that I'm sure that GNU TAR can access SELinux attributes via it, on Linux distributions that default to enabling it, but I've filed a bug with NTFS-3G, to see what they say.

I should probably also see how Paragon's NTFS driver handles xattrs, but I wouldn't be surprised, if it doesn't lack support, if it's anything like their APFS driver, from my experience.

**Comment by vmlemon** [comment]
I haven't tested this, yet - but, it sounds like it *might* be possible to specify a mapping file, containing the following, at mount time (```ntfs-3g -o xattrmapping=/root/ntfs-attrs.txt```), with a fairly recent version of NTFS-3G:

```
system.ntfs_attrib:user.ntfs_attrib
system.ntfs_times:user.ntfs_times
system.ntfs_attrib_be:user.ntfs_attrib_be
system.ntfs_reparse_data:user.ntfs_reparse_data
system.ntfs_acl:user.ntfs_acl
system.ntfs_dos_name:user.ntfs_dos_name
system.ntfs_times:user.ntfs_times 
system.ntfs_times_be:user.ntfs_times_be
system.ntfs_crtime:user.ntfs_crtime
system.ntfs_crtime_be:user.ntfs_crtime_be
system.ntfs_object_id:user.ntfs_object_id
system.ntfs_efsinfo:user.ntfs_efsinfo
system.ntfs_ea:user.ntfs_ea
```
Not ideal, but if it works, I'll report back...

**Comment by vmlemon** [comment]
Aha!

If I mount my disk image, with ```ntfs-3g -o ro -o xattrmapping=/home/tyson/ntfs-attrs.txt /dev/mapper/loop0p1 /tmp/1/``` (i.e. it will not work, with a relative path, to the ```ntfs-attrs.txt```, or "combined style" arguments, to ```-o``` (i.e. ``` -o ro xattrmapping,ntfs-attrs.txt```), it looks like their workaround kinda works, with the caveat of data encoding issues, in the attribute values:

```
root@DESKTOP-6HH5CK9:/home/tyson# xattr -l /tmp/1
user.ntfs_attrib:
0000   36 00 00 00                                        6...

Traceback (most recent call last):
  File "/usr/bin/xattr", line 33, in <module>
    sys.exit(load_entry_point('xattr==0.9.7', 'console_scripts', 'xattr')())
  File "/usr/lib/python3/dist-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 2: invalid start byte
root@DESKTOP-6HH5CK9:/home/tyson# getfattr -d /tmp/1/
getfattr: Removing leading '/' from absolute path names
# file: tmp/1/
user.ntfs_acl=0sAQAEkIwAAACcAAAAAAAAABQAAAACAHgABQAAAAAEGACYAR8AAQIAAAAAAAUgAAAAIAIAAAAEGACIABIAAQIAAAAAAAUgAAAAIAIAAAAEFACIABIAAQEAAAAAAAEAAAAAAAQYAL8BHwABAgAAAAAABSAAAAAgAgAAAAQUAL8BHwABAQAAAAAABRIAAAABAgAAAAAABSAAAAAgAgAAAQIAAAAAAAUgAAAAIAIAAA==
user.ntfs_attrib=0sNgAAAA==
user.ntfs_attrib_be=0sAAAANg==
user.ntfs_crtime=0sFlitXjbTygE=
user.ntfs_crtime_be=0sAcrTNl6tWBY=
/tmp/1/: user.ntfs_dos_name: Operation not permitted
/tmp/1/: user.ntfs_ea: No such attribute
/tmp/1/: user.ntfs_object_id: No such attribute
user.ntfs_times=0sFlitXjbTygGKi2QmQtPKAZiyayZC08oBiotkJkLTygE=
user.ntfs_times_be=0sAcrTNl6tWBYBytNCJmSLigHK00Ima7KYAcrTQiZki4o=
```

Obviously, it doesn't expose them, via the system.* attributes, in a nice way, but I guess it's better than nothing, for trying to back up their contents?

**Comment by vmlemon** [comment]
Looks like Restic will at least try to access the mapped attributes, and will complain about ones that fail through:

```
root@DESKTOP-6HH5CK9:/home/tyson# ~/restic_0.17.1_linux_amd64 -v --insecure-no-password -r /mnt/e/Archive3 backup /tmp/1/
open repository
repository f8b018ac opened (version 2, compression level auto)
found 3 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
using parent snapshot 1f82f9fa
load index files
[0:09] 100.00%  126 / 126 index files loaded
start scan on [/tmp/1/]
start backup on [/tmp/1/]
scan finished in 12.112s: 16 files, 7.249 KiB
can not obtain extended attribute user.ntfs_dos_name for /tmp/1:

Files:          15 new,     1 changed,     0 unmodified
Dirs:            1 new,     2 changed,     0 unmodified
Data Blobs:     14 new
Tree Blobs:      4 new
Added to the repository: 27.771 KiB (7.577 KiB stored)

processed 16 files, 7.249 KiB in 0:13
snapshot 5cced57c saved
```

And, if I mount my repository, it looks like it's preserved the mapped attributes, and their contents:

```
root@DESKTOP-6HH5CK9:/mnt/e# getfattr -d /tmp/1/snapshots/latest/tmp/1/
getfattr: Removing leading '/' from absolute path names
# file: tmp/1/snapshots/latest/tmp/1/
user.ntfs_acl=0sAQAEkIwAAACcAAAAAAAAABQAAAACAHgABQAAAAAEGACYAR8AAQIAAAAAAAUgAAAAIAIAAAAEGACIABIAAQIAAAAAAAUgAAAAIAIAAAAEFACIABIAAQEAAAAAAAEAAAAAAAQYAL8BHwABAgAAAAAABSAAAAAgAgAAAAQUAL8BHwABAQAAAAAABRIAAAABAgAAAAAABSAAAAAgAgAAAQIAAAAAAAUgAAAAIAIAAA==
user.ntfs_attrib=0sNgAAAA==
user.ntfs_attrib_be=0sAAAANg==
user.ntfs_crtime=0sFlitXjbTygE=
user.ntfs_crtime_be=0sAcrTNl6tWBY=
/tmp/1/snapshots/latest/tmp/1/: user.ntfs_ea: No such attribute
/tmp/1/snapshots/latest/tmp/1/: user.ntfs_object_id: No such attribute
user.ntfs_times=0sFlitXjbTygGKi2QmQtPKAZiyayZC08oBiotkJkLTygE=
user.ntfs_times_be=0sAcrTNl6tWBYBytNCJmSLigHK00Ima7KYAcrTQiZki4o=
```
Whilst it'd be nice, if the NTFS-3G folks would fix their code, I guess this could be considered a "documentation bug", in terms of bear traps, that folks will be unaware of, especially considering that NTFS EAs are becoming more prevalent, with the rise of Windows Subsystem for Linux?

**Comment by vmlemon** [comment]
Interestingly, Restic can pull the ```security.selinux``` attributes, when I archive a file, on my Android phone, using the prebuilt ARM64 Linux binaries, under Termux Ubuntu chroot:

![Screenshot_20241110_154145_Termux](https://github.com/user-attachments/assets/106fe61a-ed46-4292-a057-a2cb2ad740b9)

I assume there's a different code path, for exposing SELinux metadata, deep in the wilds of the VFS infrastructure?

**Comment by hgraeber** [comment]
Some thougts...

Restic supports part of the NTFS attributes if used with a windows operating system.

For interoperability  it would be nice to translate NTFS-3Gs user.ntfs_* attributes into the equivalent NTFS attributes supported by restic on the windows.

BTW: The same makes sense for sambas security.NTACL xattr.

**Comment by MichaelEischer** [comment]
> For interoperability it would be nice to translate NTFS-3Gs user.ntfs_* attributes into the equivalent NTFS attributes supported by restic on the windows.

Restic is not meant as a tool to losslessly convert between OS-specific file attributes. That said, if someone cares enough to implement it, then maybe. But only if the changes don't leave a mess behind and do not significantly complicate things.

> user.ntfs_crtime=0sFlitXjbTygE=
> user.ntfs_crtime_be=0sAcrTNl6tWBY=
> [...]
> user.ntfs_times=0sFlitXjbTygGKi2QmQtPKAZiyayZC08oBiotkJkLTygE=
> user.ntfs_times_be=0sAcrTNl6tWBYBytNCJmSLigHK00Ima7KYAcrTQiZki4o=

The `*_be` lines are probably the big endian encoding of the attribute without the suffix. `crtime` and `times` also appear to be potentially redundant.

**Comment by hgraeber** [comment]
> > For interoperability it would be nice to translate NTFS-3Gs user.ntfs_* attributes into the equivalent NTFS attributes supported by restic on the windows.
> 
> Restic is not meant as a tool to losslessly convert between OS-specific file attributes. That said, if someone cares enough to implement it, then maybe. But only if the changes don't leave a mess behind and do not significantly complicate things.

Sure, lossless conversion will not really be possible. But converting the most important things may be helpful. Therefore this suggestion. I will observe and possibly make a pull request.

**Comment by MichaelEischer** [comment]
> Sure, lossless conversion will not really be possible. But converting the most important things may be helpful. Therefore this suggestion. I will observe and possibly make a pull request.

I'm currently a bit cautious about adding new windows-specific features. restic 0.17.0 added xattr and acl support on Windows and required a ton of follow-up bugfixes.

**Comment by vmlemon** [comment]
Interestingly, it looks like reading from the ``security`` namespace works, after running some tests:

```
root@DESKTOP-6HH5CK9:~# touch "Test"
root@DESKTOP-6HH5CK9:~# setcap cap_net_bind_service+ep Test
root@DESKTOP-6HH5CK9:~# xattr -l Test
security.capability:
0000   01 00 00 02 00 04 00 00 00 00 00 00 00 00 00 00    ................
0010   00 00 00 00                                        ....

root@DESKTOP-6HH5CK9:~# ~/restic_0.17.1_linux_amd64 --insecure-no-password -v backup Test -r /mnt/e/Archive3/
open repository
repository f8b018ac opened (version 2, compression level auto)
found 5 old cache directories in /root/.cache/restic, run `restic cache --cleanup` to remove them
no parent snapshot found, will read all files
load index files
[0:14] 100.00%  154 / 154 index files loaded
start scan on [Test]
start backup on [Test]
scan finished in 16.992s: 1 files, 0 B

Files:           1 new,     0 changed,     0 unmodified
Dirs:            0 new,     0 changed,     0 unmodified
Data Blobs:      0 new
Tree Blobs:      1 new
Added to the repository: 370 B (302 B stored)

processed 1 files, 0 B in 0:18
snapshot 505ab81d saved
root@DESKTOP-6HH5CK9:~# ls /tmp/1/snapshots/latest/Test
/tmp/1/snapshots/latest/Test
root@DESKTOP-6HH5CK9:~# xattr -l /tmp/1/snapshots/latest/Test
security.capability:
0000   01 00 00 02 00 04 00 00 00 00 00 00 00 00 00 00    ................
0010   00 00 00 00                                        ....

```

I kinda forgot about the whole Capabilities subsystem, until I stumbled across an [article](https://www.ibm.com/support/pages/apar/IC93963) about Tivoli Storage Manager, and remembered that BedRock Linux uses them, as an internal implementation detail...
