### ISSUE TITLE
restic not working on Windows over SSH accessing remote server over SFTP protocol

### ISSUE THREAD

**Issue by kunago** [restic/restic#5155]
Output of `restic version`
--------------------------
restic 0.17.3 compiled with go1.23.3 on windows/amd64

What backend/service did you use to store the repository?
---------------------------------------------------------
Not quite understand what needs to be filled in here. I am trying to make a backup or run any other command programatically over SSH on a remote repository using sftp protocol.

Problem description / Steps to reproduce
----------------------------------------
The problem was described in detail at the forum, so this will reference this [forum topic](https://forum.restic.net/t/sftp-over-ssh-is-hanging-infinitely/8752).

I need to programatically run restic from server/computer 1 (initiator running cron), on server/computer 2 and then clone the respository to server/computer 3. It's better maintenance-wise to have all cron jobs located on a single server (server 1 in this case). Better than explaining more I will post the steps to reproduce.

1. WORKS: S1 is Windows, S2 is any linux distro, S3 is linux again

```
# passes (1a)
ssh S2_user@S2_host "export RESTIC_REPOSITORY=\"S2_path\" ; export RESTIC_PASSWORD=\"S2_password\" ; restic check"

# passes (1b)
ssh S2_user@S2_host "export RESTIC_REPOSITORY=\"sftp:S3_user@S3_host:S3_repo\" ; export RESTIC_PASSWORD=\"S3_password\" ; restic check"
```

2. DOES NOT WORK: S1 is Windows, S2 is Windows (running **OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2**), S3 is any linux distro

```
# passes (2a)
ssh S2_user@S2_host "set \"RESTIC_REPOSITORY=S2_path\" && set \"RESTIC_PASSWORD=S2_password\" && restic check"

# fails (2b)
ssh S2_user@S2_host "set \"RESTIC_REPOSITORY=sftp:S3_user@S3_host:S3_repo\" && set \"RESTIC_PASSWORD=S3_password\" && restic check"
```

Expected behavior
-----------------
The expected behavior for the second use case is the same as in the first case, meaning that restic command sent to S2 from S1 is properly executed on S3 when run over sftp protocol.

Actual behavior
---------------
Restic never finishes nor does it show any error message. The SSH command on S1 is stuck infinitely. What I tried:

- use both, cmd and powershell syntaxes
- use as little environment variables as possible making use of the --repo parameter to specify repository and --password-file to specify the password to use
- run `ssh -v S3_host -l S3_user -s sftp` on S2 to see whether there would be any error, the command finished at
`
debug1: pledge: fork
`
which seems to be okay
- run the restic command with DEBUG_LOG enabled which shows only the following in the log file on S2:
  ```
  2024/11/26 16:08:53 restic/main.go:137	main.main	1	main []string{"C:\\ProgramData\\scoop\\apps\\restic\\current\\restic.exe", "check"}
  2024/11/26 16:08:53 restic/main.go:138	main.main	1	restic 0.17.3 compiled with go1.23.2 on windows/amd64
  2024/11/26 16:08:53 restic/global.go:583	main.innerOpen	1	parsing location sftp:S3_user@S3_host:S3_repo
  2024/11/26 16:08:53 restic/global.go:578	main.parseConfig	1	opening sftp repository at &sftp.Config{User:"S3_user", Host:"S3_host", Port:"", Path:"S3_repo", Layout:"", Command:"", Args:"", Connections:0x5}
  2024/11/26 16:08:53 sftp/sftp.go:143	sftp.Open	1	open backend with config sftp.Config{User:"S3_user", Host:"S3_host", Port:"", Path:"S3_repo", Layout:"", Command:"", Args:"", Connections:0x5}
  2024/11/26 16:08:53 sftp/sftp.go:61	sftp.startClient	1	start client ssh [S3_host -l S3_user -s sftp]
  ```

- run `sshd -ddd` on the S2 machine running Windows OS to see what was going on, the command gets stuck on the following and it got as far as this including a new cmd.exe window opening with no input or output in it however
  ```
  debug2: fd 5 setting TCP_NODELAY
  debug3: fd 12 is O_NONBLOCK
  debug3: fd 11 is O_NONBLOCK
  debug3: fd 14 is O_NONBLOCK
  debug3: send packet: type 99
  ```

Do you have any idea what may have caused this?
-----------------------------------------------
Looking at the sshd debug log I can see an excessive amount of escaping so that might be an issue. sshd debug log shows this

```
debug3: shell: "c:\\\\windows\\\\system32\\\\cmd.exe"
debug3: shell_option: /c
debug3: exec_command: set "RESTIC_PASSWORD=S3_pass" && set "RESTIC_REPOSITORY=S3_repo" && restic check
debug3: arg escape option: TRUE
debug3: spawn_argv[0]: "c:\\\\windows\\\\system32\\\\cmd.exe" /c "set "RESTIC_PASSWORD=S3_pass" && set "RESTIC_REPOSITORY=S3_repo" && restic check"
debug3: spawning "c:\\\\windows\\\\system32\\\\cmd.exe" /c "set "RESTIC_PASSWORD=S3_pass" && set "RESTIC_REPOSITORY=S3_repo" && restic check" as subprocess
debug2: fd 5 setting TCP_NODELAY
debug3: fd 12 is O_NONBLOCK
debug3: fd 11 is O_NONBLOCK
debug3: fd 14 is O_NONBLOCK
debug3: send packet: type 99
```

If S3_user or S3_pass are incorrect, the command exits; when they are correct, the command never finishes.

Did restic help you today? Did it make you happy in any way?
------------------------------------------------------------
Not necessarily today but it is of a great help so far. I was using 7z and rsync to make backups then trying to cleanup old backups and so on. It was too complicated and with no deduplication, althouth 7z can make use incremental backups. restic is way more user friendly.

**Comment by MichaelEischer** [comment]
> * run `ssh -v S3_host -l S3_user -s sftp` on S2 to see whether there would be any error, the command finished at
>       `debug1: pledge: fork`
>       which seems to be okay

That looks fine at first glance. What happens if you type anything in that session? (For me on Linux, entering `test` results in a closed connection and an error)

> * run the restic command with DEBUG_LOG enabled which shows only the following in the log file on S2:

restic is apparently stuck somewhere between starting ssh and reading any files from sftp. It's most likely stuck somewhere in the sftp initialization. To find out the exact place where restic is stuck, please set the environment variable `RESTIC_DEBUG_STACKTRACE_SIGINT` to `true` and then stop restic using `ctrl+c` (see [docs](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) for more context). This should print a stacktrace that shows where exactly restic is stuck.

**Comment by kunago** [comment]
So this is what I got. I believe the first one is the same as yours, the STACKTRACE I have no clue about. If there is anything more needed, let me know please.

> That looks fine at first glance. What happens if you type anything in that session? (For me on Linux, entering `test` results in a closed connection and an error)

```
debug1: pledge: fork
test
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 3624, received 2860 bytes, in 2.9 seconds
Bytes per second: sent 1233.9, received 973.8
debug1: Exit status 11
```

> restic is apparently stuck somewhere between starting ssh and reading any files from sftp. It's most likely stuck somewhere in the sftp initialization. To find out the exact place where restic is stuck, please set the environment variable `RESTIC_DEBUG_STACKTRACE_SIGINT` to `true` and then stop restic using `ctrl+c` (see [docs](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) for more context). This should print a stacktrace that shows where exactly restic is stuck.

```
signal interrupt received, cleaning up

--- STACKTRACE START ---

goroutine 11 [running]:
github.com/restic/restic/internal/debug.DumpStacktrace()
	/restic/internal/debug/stacktrace.go:9 +0x65
main.cleanupHandler(0x0?, 0xc000112070)
	/restic/cmd/restic/cleanup.go:30 +0x13d
created by main.createGlobalContext in goroutine 1
	/restic/cmd/restic/cleanup.go:16 +0x98

goroutine 1 [syscall]:
syscall.Syscall6(0x462c38?, 0xc000124458?, 0x47f70a?, 0xc000124428?, 0x12b6936?, 0x9?, 0x22c?, 0xc00000a0c0?)
	/usr/local/go/src/runtime/syscall_windows.go:463 +0x38
syscall.readFile(0x230, {0xc00000a0b8?, 0x4, 0x460005?}, 0xc0001244e0?, 0x800000?)
	/usr/local/go/src/syscall/zsyscall_windows.go:1019 +0x8b
syscall.ReadFile(...)
	/usr/local/go/src/syscall/syscall_windows.go:443
syscall.Read(0xc00009fd48?, {0xc00000a0b8?, 0x483389?, 0xc0001244f8?})
	/usr/local/go/src/syscall/syscall_windows.go:422 +0x2d
internal/poll.(*FD).Read(0xc00009fd48, {0xc00000a0b8, 0x4, 0x4})
	/usr/local/go/src/internal/poll/fd_windows.go:424 +0x1b9
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:29
os.(*File).Read(0xc0000705b8, {0xc00000a0b8?, 0xc00009fb08?, 0x1d40c60?})
	/usr/local/go/src/os/file.go:124 +0x52
io.ReadAtLeast({0x149c060, 0xc0000e1200}, {0xc00000a0b8, 0x4, 0x4}, 0x4)
	/usr/local/go/src/io/io.go:335 +0x90
io.ReadFull(...)
	/usr/local/go/src/io/io.go:354
github.com/pkg/sftp.recvPacket({0x149c060, 0xc0000e1200}, 0x0, 0x149c040?)
	/home/build/go/pkg/mod/github.com/pkg/sftp@v1.13.6/packet.go:277 +0x99
github.com/pkg/sftp.(*conn).recvPacket(...)
	/home/build/go/pkg/mod/github.com/pkg/sftp@v1.13.6/conn.go:25
github.com/pkg/sftp.(*Client).recvVersion(0xc0000e1200)
	/home/build/go/pkg/mod/github.com/pkg/sftp@v1.13.6/client.go:276 +0x2f
github.com/pkg/sftp.NewClientPipe({0x1499120, 0xc0000705b8}, {0x14a16f0, 0xc0000705a0}, {0xc0001248f0, 0x2, 0xc00012a05a?})
	/home/build/go/pkg/mod/github.com/pkg/sftp@v1.13.6/client.go:233 +0x26b
github.com/restic/restic/internal/backend/sftp.startClient({{0xc00012a045, 0x7}, {0xc00012a04d, 0xc}, {0x0, 0x0}, {0xc00012a05a, 0x1e}, {0x0, 0x0}, ...})
	/restic/internal/backend/sftp/sftp.go:108 +0x4e9
github.com/restic/restic/internal/backend/sftp.Open({0x14a7e90, 0xc0000c6460}, {{0xc00012a045, 0x7}, {0xc00012a04d, 0xc}, {0x0, 0x0}, {0xc00012a05a, 0x1e}, ...})
	/restic/internal/backend/sftp/sftp.go:145 +0xb8
github.com/restic/restic/internal/backend/sftp.NewFactory.WrapBackendConstructor[...].func2({{0xc00012a045, 0x7}, {0xc00012a04d, 0xc}, {0x0, 0x0}, {0xc00012a05a, 0x1e}, {0x0, 0x0}, ...}, ...)
	/restic/internal/backend/limiter/limiter_backend.go:13 +0x7f
github.com/restic/restic/internal/backend/sftp.NewFactory.NewLimitedBackendFactory[...].func4({{0xc00012a045, 0x7}, {0xc00012a04d, 0xc}, {0x0, 0x0}, {0xc00012a05a, 0x1e}, {0x0, 0x0}, ...}, ...)
	/restic/internal/backend/location/registry.go:103 +0x79
github.com/restic/restic/internal/backend/location.(*genericBackendFactory[...]).Open(0x1?, {0x14a7e90?, 0xc0000c6460?}, {0x1006680?, 0xc0000e2e00?}, {0x1499d60?, 0xc0003046c0?}, {0x14aa460, 0xc000112190})
	/restic/internal/backend/location/registry.go:65 +0xf5
main.innerOpen({_, _}, {_, _}, {{0xc00012a040, 0x38}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/restic/cmd/restic/global.go:612 +0x2c2
main.open({_, _}, {_, _}, {{0xc00012a040, 0x38}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/restic/cmd/restic/global.go:639 +0x85
main.OpenRepository({_, _}, {{0xc00012a040, 0x38}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
	/restic/cmd/restic/global.go:438 +0xb1
main.internalOpenWithLocked({_, _}, {{0xc00012a040, 0x38}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/restic/cmd/restic/lock.go:10 +0x5f
main.openWithReadLock({_, _}, {{0xc00012a040, 0x38}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
	/restic/cmd/restic/lock.go:38 +0x5a
main.runSnapshots({_, _}, {{{}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...}, ...)
	/restic/cmd/restic/cmd_snapshots.go:67 +0x10e
main.init.func30(0x1d2d840?, {0x1d870a0?, 0x4?, 0x12aeb28?})
	/restic/cmd/restic/cmd_snapshots.go:35 +0xa7
github.com/spf13/cobra.(*Command).execute(0x1d2d840, {0x1d870a0, 0x0, 0x0})
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0x1d29be0)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
main.main()
	/restic/cmd/restic/main.go:142 +0x265

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000e3700)
	/home/build/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:292 +0x9f
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/home/build/go/pkg/mod/go.opencensus.io@v0.24.0/stats/view/worker.go:34 +0x8d

goroutine 18 [chan receive]:
github.com/restic/restic/internal/restic.init.0.func1.1()
	/restic/internal/restic/lock.go:429 +0x94
created by github.com/restic/restic/internal/restic.init.0.func1 in goroutine 1
	/restic/internal/restic/lock.go:426 +0x1a

goroutine 34 [syscall]:
os/signal.signal_recv()
	/usr/local/go/src/runtime/sigqueue.go:152 +0x29
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x13
created by os/signal.Notify.func1.1 in goroutine 18
	/usr/local/go/src/os/signal/signal.go:151 +0x1f

goroutine 12 [syscall]:
syscall.Syscall6(0x0?, 0x0?, 0x100000000?, 0x0?, 0x0?, 0x0?, 0x0?, 0x1f875811688?)
	/usr/local/go/src/runtime/syscall_windows.go:463 +0x38
syscall.readFile(0x220, {0xc000129000?, 0x1000, 0x4131bc?}, 0x1d88f40?, 0x800000?)
	/usr/local/go/src/syscall/zsyscall_windows.go:1019 +0x8b
syscall.ReadFile(...)
	/usr/local/go/src/syscall/syscall_windows.go:443
syscall.Read(0xc00009e908?, {0xc000129000?, 0xc00046bdc0?, 0x459f45?})
	/usr/local/go/src/syscall/syscall_windows.go:422 +0x2d
internal/poll.(*FD).Read(0xc00009e908, {0xc000129000, 0x1000, 0x1000})
	/usr/local/go/src/internal/poll/fd_windows.go:424 +0x1b9
os.(*File).read(...)
	/usr/local/go/src/os/file_posix.go:29
os.(*File).Read(0xc000070568, {0xc000129000?, 0x0?, 0x0?})
	/usr/local/go/src/os/file.go:124 +0x52
bufio.(*Scanner).Scan(0xc00046bf50)
	/usr/local/go/src/bufio/scan.go:219 +0x81e
github.com/restic/restic/internal/backend/sftp.startClient.func1()
	/restic/internal/backend/sftp/sftp.go:74 +0x152
created by github.com/restic/restic/internal/backend/sftp.startClient in goroutine 1
	/restic/internal/backend/sftp/sftp.go:72 +0x1dd

goroutine 20 [syscall]:
syscall.Syscall(0x1d0f120?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/syscall_windows.go:457 +0x29
syscall.WaitForSingleObject(0x254, 0xffffffff)
	/usr/local/go/src/syscall/zsyscall_windows.go:1140 +0x5d
os.(*Process).wait(0x0?)
	/usr/local/go/src/os/exec_windows.go:28 +0xe6
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:358
os/exec.(*Cmd).Wait(0xc0001ae780)
	/usr/local/go/src/os/exec/exec.go:906 +0x45
github.com/restic/restic/internal/backend/sftp.startClient.func2()
	/restic/internal/backend/sftp/sftp.go:100 +0x25
created by github.com/restic/restic/internal/backend/sftp.startClient in goroutine 1
	/restic/internal/backend/sftp/sftp.go:99 +0x2ba

--- STACKTRACE END ---
```

**Comment by kunago** [comment]
I tried debugging further and tried to compile a debug version of restic, however, don't know how to use it to debug this specific issue.

Anyways, running the previously failing command
```
ssh S2_user@S2_host "set \"RESTIC_REPOSITORY=sftp:S3_user@S3_host:S3_repo\" && set \"RESTIC_PASSWORD=S3_password\" && restic check"
```
opens the following tree of commands:
![tree](https://github.com/user-attachments/assets/d23eb8b2-8d44-4367-b692-9eda3c056c24)

From top to bottom, starting with the first sshd.exe, the command lines sound like this:

1. sshd.exe: `"C:\WINDOWS\System32\OpenSSH\sshd.exe" -ddd`
2. sshd.exe: `"C:\WINDOWS\System32\OpenSSH\sshd.exe" -ddd -z`
3. cmd.exe: `"c:\windows\system32\cmd.exe" /c "set "RESTIC_PASSWORD=S3_pass" && set "RESTIC_REPOSITORY=S3_repo" && restic check"`
4. conhost.exe: `\??\C:\WINDOWS\system32\conhost.exe 0x4`
5. restic.exe: `restic check`
6. restic.exe: `"C:\ProgramData\scoop\apps\restic\current\restic.exe"   check`
7. ssh.exe: `ssh S3_host -l S3_user -s sftp`

So it seems to be waiting, having a blank window open on S2, for something. In about 5 minutes or so, the connection closed with the following error message:

```
ubprocess ssh: Connection to S3_host closed by remote host.
Fatal: unable to open repository at sftp:S3_user@S3_host:S3_repo: unable to start the sftp session, error: error receiving version packet from server: server unexpectedly closed connection: unexpected EOF
```
I can also see this in the restic debug log:
```
sftp/sftp.go:147	sftp.Open	1	unable to start program: unable to start the sftp session, error: error receiving version packet from server: server unexpectedly closed connection: unexpected EOF
restic/cleanup.go:39	main.Exit	1	exiting with status code 1
```

**Comment by kunago** [comment]
I did not think of debugging directly on S3 (I can easily access Windows to basically see the very similar as on S2) and got the following process tree:

![tree](https://github.com/user-attachments/assets/92b40b0e-81c4-4103-bc4c-5913fd8afbd5)

Once again, the commands starting from the `sshd.exe` are:

1. sshd.exe: `"C:\WINDOWS\System32\OpenSSH\sshd.exe" -ddd`
2. sshd.exe: `"C:\WINDOWS\System32\OpenSSH\sshd.exe" -ddd -z`
3. cmd.exe: `"c:\windows\system32\cmd.exe" /c "sftp-server.exe "`
4. conhost.exe: `\??\C:\WINDOWS\system32\conhost.exe 0x4`
5. sftp-server.exe: `"sftp-server.exe "`

**Comment by kunago** [comment]
In addition to the previous test I additionally tested SSH connection on S3. As mentioned before, if the connection is initiated from S1, it sticks, if it is initiated from S2, it passes fine.

So the commands and their respective debug logs of SSH server from S3:

1. passed from S2: `set "RESTIC_REPOSITORY=sftp:S3_user@S3_host:S3_repo" && set "RESTIC_PASSWORD=S3_pass" && restic check` [restic-S2-passed.txt](https://github.com/user-attachments/files/18060560/restic-S2-passed.txt)
2. failed from S1: `ssh S2_user@S2_host "set \"RESTIC_REPOSITORY=sftp:S3_user@S3_host:S3_repo\" && set \"RESTIC_PASSWORD=S3_pass\" && restic check"` [restic-S1-failed.txt](https://github.com/user-attachments/files/18060553/restic-S1-failed.txt)

Both commands reach line 297 successfully but when connecting from S1, sftp/restic does really not seem to respond to a sent packet type 99 from the connecting server.

**Comment by kunago** [comment]
I believe the config is as standard as it can be in fact.

```
# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
#LogLevel INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

# PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
#PermitEmptyPasswords no

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
#PermitTTY yes
#PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
#PermitTunnel no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# override default of no subsystems
Subsystem	sftp	sftp-server.exe

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
#	ForceCommand cvs server

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys
```

And is it actually SSH or SFTP which is not working properly? Because it seems to be stuck at S2 not sending and S3 not receiving SFTP client version.

It there was any intereference, it should probably have the same symptoms when connection from S2 to S3, which works fine though; only S1 to S3 via S2 fails.

**Comment by MichaelEischer** [comment]
Then I'm out of ideas for now. It looks like either the windows openssh is buggy or there's some weird interaction between restic and the windows openssh. But I don't have to time to debug setup a test environment and try to debug that.

**Comment by Sartuki** [comment]
I'm facing the same issue, as initially described, on Windows Server 2022, trying to execute Restic SFTP commands from an SSH connection from an Ubuntu 20.04 LTS server. 

Restic version is 0.18.1.
OpenSSH is 9.5.

From the same Ubuntu server, I have no problem executing other SFTP commands connecting to the same third server. Executing the Restic commands from a script doesn't work either, it always freezes.

**Comment by deajan** [comment]
I do have the freezing problem too. Using Windows 11 22H2 x64 to connect to a RHEL9 server, using restic 0.18.1.

I can connect via "plain" ssh from windows:
```
C:\GIT\>ssh -p 22 -i ssh_key.txt restic@192.168.200.204
Last login: Mon Apr  6 22:30:08 2026 from 192.168.80.33
[restic@rhel9~]$ exit
logout
Connection to 192.168.81.204 closed.
```

if I happen to use restic, terminal freezes (CTRL+C will `signal interrupt received, cleaning up` message but terminal will still be frozen):
```
C:\GIT\>set RESTIC_PASSWORD=test
C:\GIT\>set RESTIC_REPOSITORY=sftp:restic@192.168.200.204:/repo
C:\GIT\>set DEBUG_LOG=restic.log
C:\GIT\>restic -o sftp.command="ssh -p 22 -i ssh_key.txt restic@192.168.200.204" ls latest
subprocess ssh: Pseudo-terminal will not be allocated because stdin is not a terminal.
```

The above command produced the following log file (last 3 lines appeared once I typed CTRL+C):
```
2026/04/06 22:36:30 restic/main.go:167	main.main	1	main []string{"restic", "-o", "sftp.command=ssh -p 22 -i ssh_key.txt restic@192.168.81.204", "ls", "latest"}
2026/04/06 22:36:30 restic/main.go:168	main.main	1	restic 0.18.1 compiled with go1.25.1 on windows/amd64
2026/04/06 22:36:30 restic/global.go:603	main.innerOpen	1	parsing location sftp:restic@192.168.81.204:/repo
2026/04/06 22:36:30 restic/global.go:598	main.parseConfig	1	opening sftp repository at &sftp.Config{User:"restic", Host:"192.168.81.204", Port:"", Path:"/repo", Command:"ssh -p 22 -i ssh_key.txt restic@192.168.200.204", Args:"", Connections:0x5}
2026/04/06 22:36:30 sftp/sftp.go:147	sftp.Open	1	open backend with config sftp.Config{User:"restic", Host:"192.168.81.204", Port:"", Path:"/repo", Command:"ssh -p 22 -i ssh_key.txt restic@192.168.200.204", Args:"", Connections:0x5}
2026/04/06 22:36:30 sftp/sftp.go:59	sftp.startClient	1	start client ssh [-p 22 -i ssh_key.txt restic@192.168.200.204]
2026/04/06 22:40:07 restic/cleanup.go:25	main.cleanupHandler	8	signal interrupt received, cleaning up
2026/04/06 22:40:07 restic/global.go:286	main.Warnf	8	                                                                                                                                                           
signal interrupt received, cleaning up
```

I also tried using the `plink` solution I've read on various issues / forum entries, but I think there's something wrong with the `sftp` call which expects arguments (I've tried this on a RHEL9 and a Debian 11, both return the same result):
```
C:\GIT\>restic -o sftp.command="./plink.exe -l restic -pw restic 192.168.200.204 sftp" ls snapshots
debug log file restic.log
debug enabled
subprocess ./plink.exe: usage: sftp [-46AaCfNpqrv] [-B buffer_size] [-b batchfile] [-c cipher]
subprocess ./plink.exe:           [-D sftp_server_path] [-F ssh_config] [-i identity_file]
subprocess ./plink.exe:           [-J destination] [-l limit] [-o ssh_option] [-P port]
subprocess ./plink.exe:           [-R num_requests] [-S program] [-s subsystem | sftp_server]
subprocess ./plink.exe:           destination
Fatal: unable to open repository at sftp:restic@192.168.200.204:/repo: unable to start the sftp session, error: error receiving version packet from server: server unexpectedly closed connection: unexpected EOF
```

I've also tried to "force" a sftp server for my restic user on the linux side by configuring sshd_config, without any more luck.

I'm quite puzzled on how to get SFTP working on Windows. Anyone has more experience here ?

**Comment by Xavron** [comment]
### _Lots of edits for clarifications, additional info, added WORKING examples, reworked, etc... Tried to have only most necessary info (not easy)._

> I'm quite puzzled on how to get SFTP working on Windows.

_Tested with both client and server as installed from Windows Settings. Thus, Windows, Windows OpenSSH client and server all work with SSH via Restic from two different computers over SFTP._

- "sftp:" built-in
    - Working example: `."path/restic_0.18.1_windows_amd64.exe" -r sftp:user@IP:C:/path/remoteResticRepo init` using manual typed password works for me so it would be some difference if it failed for you. (Restic backup also tested as working.)
    - Using Windows OpenSSH client/server... using Restic via built-in "sftp:" works fine. There's nothing wrong with SFTP on Windows there _that I could see_.
    - Code shows can have // too but I didn't test this.
    - Forgot to add, if you need some other port, can use [IP]:port//path (or whatever, I didn't test this as port 22 worked w/o it).
    - IPv6 is supposedly supported using [ ]'s but I didn't test it.

- "sftp.command=" external via ssh with -s sftp _indirect_
    - eg sftp.command=ssh ... -s sftp"
    - Working init example: `."path/restic_0.18.1_windows_amd64.exe" -r sftp::C:/path/remoteResticRepo -o sftp.command="ssh -P port user@IP -s sftp" init`
    - Working backup example: `."path/restic_0.18.1_windows_amd64.exe" backup "C:\path\backupOrigin" -r sftp::C:/path/remoteResticRepo -o sftp.command="ssh -P port user@IP -s sftp"`
    - Working check example: `."path/restic_0.18.1_windows_amd64.exe" check -r "C:\path\backupOrigin" -r sftp::C:/path/remoteResticRepo -o sftp.command="ssh -P port user@IP -s sftp"` (yes two -r uses)
    - Path example remoteResticRepo C:\ResticRepo (init location where Restic makes the backup repo)
    - Path example backupOrigin C:\Users\HelloMe (the root path where Restic looks for files to add)
    - sftp::path is used by removing the built-in use connection info but still providing remote path from it. This is odd. Required to use sftp. sftp.command does nothing without it and it works locally instead of remote.
    - Kind of weird: Needs to go through ssh and use -s sftp with it... see third main point below.
    - This is using cert copied from server to client (not password).
    - Thanks to https://github.com/restic/restic/issues/312 for showing this.

- "sftp.command=" external via sftp _direct_
  - eg sftp.command=sftp..."
  - https://github.com/restic/restic/blob/1807d269cdee698a287df6b5f780273218c40fa0/internal/backend/sftp/sftp.go#L60
  - From what I'm seeing, this literally cannot be done. The code comment here specifically says "request the sftp subsystem via the 'ssh' command".
  - This is what I'm seeing from OpenSSH side. It starts perfectly fine exact same as OpenSSH client to server where server waits for next command. Restic code doesn't continue to execute. FYI, nothing to do with packets getting through the network, number of slashes in a path, or any other theories like that (these things are not the problem here). _This is a code issue._
  - FYI, this can error/exit under certain wrong uses so not ALL uses result in it being stuck. Connection failures do error/exit, so if something is incorrect, it does do this.
  - Last Restic log line: `sftp/sftp.go:59	sftp.startClient	1	start client sftp.exe [...]`
  - Tested variety of stuff to see what the code with do all to failure. Without debugging code, it looks like it splits what's given to it (to put it simply), and tries to use it, but that results in getting stuck. _I'm_ expecting stuck in Go's pkg/sftp, but again not debugging this or anything.
  - One last thing from Go pgk/sftp
    - https://github.com/pkg/sftp/blob/ab3b1a348110878ba49035ce91904cc41743feb0/client.go#L225
    - https://github.com/restic/restic/blob/1807d269cdee698a287df6b5f780273218c40fa0/internal/backend/sftp/sftp.go#L63
    - So, _looks like_ Restic here is using exec.Command and that seems to want to go through SSH directly. So I'm expecting with the above, with this, that Restic's current use cannot do SFTP directly. It _sounds_ to me that Go's pkg/sftp can do SFTP direct but I'm not dealing with that here or finding out.

_The working examples can potentially change in the future._

BTW, to add a line I removed as its technically not a Restic problem, scripts are referenced as part of the original "problem" here: If doing this from a script, make sure the entire line in the script really works right, because scripts can do some odd things over direct command line. _Give the above lines what is necessary in a script and they will work._

There's probably also SFTP via the other thing (rclone). I'm not getting into that. :) So, for those that didn't see _that_ info before, still other ways may exist.

**Comment by deajan** [comment]
@Xavron thank you !
Both times I was missing the subsystem invocation, ie `-s sftp`.
