### ISSUE TITLE
Handle "disk is full" gracefully

### ISSUE THREAD

**Issue by fd0** [restic/restic#540]
At the moment, trying to backup to a local disk which is too small results in a panic:
```
panic: rename  /srv/data/Backup/fd0/restic-repo/data/20/20ac88d873792b49900d2f5f73e61259aae4663d2a8fa180ed9f21d58a24c12c: no such file or directory

goroutine 104 [running]:
panic(0x95aa60, 0xc82e18ae40)
	/usr/lib/go/src/runtime/panic.go:464 +0x3e6
restic.(*Archiver).saveChunk(0xc82e660aa0, 0x1c773b, 0x160df0, 0xa39be200000, 0xc82ee6a000, 0x160df0, 0x188000, 0xc8200e0180, 0x7f23c43ad678, 0xc82df64380, ...)
	/tmp/restic-build-575371866/src/restic/archiver.go:166 +0x1e1
created by restic.(*Archiver).SaveFile
	/tmp/restic-build-575371866/src/restic/archiver.go:238 +0x556
[1]    25449 exit 2     restic backup ~/shared
```

Restic should handle this special error gracefully and print an understandable error message.

**Comment by fd0** [comment]
The cause for this issue was discovered today: the local and sftp backend do not check errors returned by `Write()`, so the original error (`No space left on device`) is discarded. This will be fixed in #593.
