### ISSUE TITLE
Panic when trying to create backup

### ISSUE THREAD

**Issue by FooSoft** [restic/restic#574]
## Output of `restic version`

```
restic 0.2.0 (v0.2.0-23-ge934966)
compiled at 2016-08-20 10:23:07 with go1.7
```

## Expected behavior

Should be able to create backup without crashing.

## Actual behavior

Restic panics:

```
alex@flatline /m/storage> restic -r archive_restic backup archive
enter password for repository: 
scan [/mnt/storage/archive]
scanned 832 directories, 60606 files in 0:02
panic: rename  archive_restic/data/20/206ed912d3583bf59e2c8aa41866cac4b306d3296aefb18cc9c0a1bc812af99c: no such file or directory

goroutine 45654 [running]:
panic(0x807520, 0xc42b59a6c0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
restic.(*Archiver).saveChunk(0xc42029d220, 0x0, 0xa5bc2, 0x3877bdda00000, 0xc4239d8000, 0xa5bc2, 0x18a000, 0xc4200ee210, 0xa59c60, 0xc424c86390, ...)
	/tmp/restic-build-244874891/src/restic/archiver.go:165 +0x282
created by restic.(*Archiver).SaveFile
	/tmp/restic-build-244874891/src/restic/archiver.go:237 +0x2fa
panic: rename  archive_restic/data/7f/7f77ca79915790efff0f5ec5a64a3b5df7d23ddfe5e5fa7d6ebffe8194f7f6d2: no such file or directory

goroutine 45645 [running]:
panic(0x807520, 0xc42ba2f340)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
restic.(*Archiver).saveChunk(0xc42029d220, 0x0, 0x14ee68, 0x77d2ef8900000, 0xc4245a8000, 0x14ee68, 0x18a000, 0xc4200ee210, 0xa59c60, 0xc424c860a0, ...)
	/tmp/restic-build-244874891/src/restic/archiver.go:165 +0x282
created by restic.(*Archiver).SaveFile
	/tmp/restic-build-244874891/src/restic/archiver.go:237 +0x2fa
panic: rename  archive_restic/data/f3/f3296685e89481be01defe3116b3753c913060d8a4782df1e6a3b0cf8a2bed4d: no such file or directory

goroutine 45569 [running]:
panic(0x807520, 0xc425559ac0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
restic.(*Archiver).saveChunk(0xc42029d220, 0x0, 0x194257, 0x15d79502c00000, 0xc42be66000, 0x194257, 0x1ea000, 0xc4200ee210, 0xa59c60, 0xc42a910360, ...)
	/tmp/restic-build-244874891/src/restic/archiver.go:165 +0x282
created by restic.(*Archiver).SaveFile
```

One more attempt:

```
alex@flatline /m/storage> restic -r archive_restic backup archive
enter password for repository: 
scan [/mnt/storage/archive]
scanned 832 directories, 60606 files in 0:00
panic: rename  archive_restic/data/c9/c95214913dd2a905dbe0e66df6643673d637d384dbebee2f5c7e95542ede56a8: no such file or directory

goroutine 45590 [running]:
panic(0x807520, 0xc4264fc0c0)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
restic.(*Archiver).saveChunk(0xc420202c30, 0x0, 0xd13b5, 0x1c637615900000, 0xc420590000, 0xd13b5, 0x268000, 0xc4241a40b0, 0xa59c60, 0xc42420b990, ...)
	/tmp/restic-build-244874891/src/restic/archiver.go:165 +0x282
created by restic.(*Archiver).SaveFile
	/tmp/restic-build-244874891/src/restic/archiver.go:237 +0x2fa
```

## Steps to reproduce the behavior

Tried to create a backup for the first time after doing init. I have about 100GiB of files, and restic panics every time I try to create a backup (somewhere between 20 ~ 40% completion). Looks like a race. 

My system:

```
alex@flatline ~> uname -a
Linux flatline 4.7.0-1-ARCH #1 SMP PREEMPT Mon Aug 8 22:05:58 CEST 2016 x86_64 GNU/Linux
```

**Comment by fd0** [comment]
Hi, thanks for reporting this. I suspect it's cause by restic not being able to handle full harddisks gracefully (see #540). Could you check if there is enough space?

**Comment by FooSoft** [comment]
Ah, you are correct, my disk was indeed full. Backup completed without error after I made some room :+1:

**Comment by fd0** [comment]
Great, thanks for leaving a comment here (so other people can find it).
