### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by jpmens** [restic/restic#843]
## Output of `restic version`

```
restic 0.4.0 (v0.4.0-86-g90bc187)
compiled with go1.7.4 on darwin/amd64
```

## Expected behavior

A full backup.

## Actual behavior

```
scan [/Users/jpm]
scanned 122813 directories, 765561 files in 2:01
panic: runtime error: index out of range/ 118.215 GiB  453073 / 888374 items  0 errors  ETA 14:59

goroutine 32 [running]:
panic(0x46ce80, 0xc42000e120)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/pkg/xattr.Getxattr(0xc420dd7b30, 0x42, 0xc4225cc240, 0x19, 0xc4214fd0a8, 0x5e04b, 0x30, 0x48c500, 0x1)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/github.com/pkg/xattr/xattr_darwin.go:14 +0x462
restic.Getxattr(0xc420dd7b30, 0x42, 0xc4225cc240, 0x19, 0x0, 0x1, 0x0, 0xc4214fd178, 0x2ef2e)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/node_xattr.go:15 +0x5c
restic.(*Node).fillExtendedAttributes(0xc4291a0c60, 0xc420dd7b30, 0x42, 0x4, 0x1)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/node.go:616 +0x310
restic.(*Node).fillExtra(0xc4291a0c60, 0xc420dd7b30, 0x42, 0x6f3440, 0xc42007cc30, 0x2, 0x2)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/node.go:596 +0x29a
restic.NodeFromFileInfo(0xc420dd7b30, 0x42, 0x6f3440, 0xc42007cc30, 0x6f3440, 0xc42007cc30, 0x0)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/node.go:82 +0x1f4
restic/archiver.(*Archiver).fileWorker(0xc4201bfea0, 0xc4207e95b0, 0xc424c41a20, 0xc427276480, 0xc427276720)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/archiver/archiver.go:276 +0x77a
created by restic/archiver.(*Archiver).Snapshot
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-944832462/src/restic/archiver/archiver.go:711 +0x768
```

## Steps to reproduce the behavior

```
restic -r ${REPO} backup \
   --exclude="Dropbox" \
   ... (20 further excludes) \
   .
```

macOS: `uname -a: Darwin tiggr 16.4.0 Darwin Kernel Version 16.4.0`

**Comment by jpmens** [comment]
> @jpmens Huh, that's odd. Could you please report an issue at GitHub? Looks like a bug in the xattr library...

**Comment by fd0** [comment]
Thanks for the report. It indeed looks like a bug in the `xattr` library. First step is to narrow it down to the file or dir that caused this. Please [create a debug log](https://github.com/restic/restic/blob/master/CONTRIBUTING.md#reporting-bugs) and run a backup, then have a look at the last lines of the log file.

**Comment by jpmens** [comment]
Here are the last 80 lines from the log:

```
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 restic/node.go:609	restic.(*Node).fillExtendedAttributes	95	fillExtendedAttributes(/Users/jpm/Library/Preferences/com.macrabbit.Espresso.plist) [] <nil>
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 pipe/pipe.go:82	pipe.walk	16	start on "/Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist", basedir "/Users"
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 archiver/archiver.go:96	archiver.(*Archiver).Save	386209	Save(data, 8139d4bd)
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 archiver/archiver.go:302	archiver.(*Archiver).fileWorker	95	   jpm/Library/Preferences/com.macrabbit.Espresso.plist no old data
2017/03/04 13:46:46 pipe/pipe.go:107	pipe.walk	16	sending file job for /Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist, res 0xc422d9ba40
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 archiver/archiver.go:307	archiver.(*Archiver).fileWorker	95	   read and save jpm/Library/Preferences/com.macrabbit.Espresso.plist
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 archiver/archiver.go:96	archiver.(*Archiver).Save	386198	Save(data, 9261ecce)
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386185	id f05ef6bb not found
2017/03/04 13:46:46 repository/master_index.go:38	repository.(*MasterIndex).Lookup	386185	id f05ef6bb not found in any index
2017/03/04 13:46:46 repository/repository.go:169	repository.(*Repository).SaveAndEncrypt	386185	save id f05ef6bb (data, 1412 bytes)
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385863	<Blob (data) c04a4eca, offset 146679, length 125>
2017/03/04 13:46:46 archiver/archiver.go:99	archiver.(*Archiver).Save	386141	blob 9261ecce is known
2017/03/04 13:46:46 archiver/archiver.go:99	archiver.(*Archiver).Save	386172	blob 9261ecce is known
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385863	  updating blob deca1e47 to pack 7b146615
2017/03/04 13:46:46 archiver/archiver.go:186	archiver.updateNodeContent	91	checking size for file /Users/jpm/Library/Preferences/com.lobotomo.IPSecuritas.plist
2017/03/04 13:46:46 repository/packer_manager.go:68	repository.(*packerManager).findPacker	386185	searching packer for 1444 bytes
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385863	<Blob (tree) deca1e47, offset 146804, length 498>
2017/03/04 13:46:46 repository/packer_manager.go:71	repository.(*packerManager).findPacker	386185	found packer <Packer 93 blobs, 209079 bytes>
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385863	  updating blob cfb56d20 to pack 7b146615
2017/03/04 13:46:46 archiver/archiver.go:195	archiver.updateNodeContent	91	  adding blob 9261ecce, 42 bytes
2017/03/04 13:46:46 archiver/archiver.go:186	archiver.updateNodeContent	83	checking size for file /Users/jpm/Library/Preferences/com.lobotomo.IPSecuritasMenu.plist
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385863	<Blob (data) cfb56d20, offset 147302, length 122>
2017/03/04 13:46:46 repository/repository.go:196	repository.(*Repository).SaveAndEncrypt	386185	pack is not full enough (210523 bytes)
2017/03/04 13:46:46 archiver/archiver.go:202	archiver.updateNodeContent	91	SaveFile("/Users/jpm/Library/Preferences/com.lobotomo.IPSecuritas.plist"): 1 blobs
2017/03/04 13:46:46 archiver/archiver.go:195	archiver.updateNodeContent	83	  adding blob 9261ecce, 42 bytes
2017/03/04 13:46:46 repository/packer_manager.go:103	repository.(*packerManager).insertPacker	386185	2 packers
2017/03/04 13:46:46 archiver/archiver.go:322	archiver.(*Archiver).fileWorker	91	   processed jpm/Library/Preferences/com.lobotomo.IPSecuritas.plist, 1 blobs
2017/03/04 13:46:46 archiver/archiver.go:202	archiver.updateNodeContent	83	SaveFile("/Users/jpm/Library/Preferences/com.lobotomo.IPSecuritasMenu.plist"): 1 blobs
2017/03/04 13:46:46 archiver/archiver.go:263	archiver.(*Archiver).fileWorker	91	got job {/Users jpm/Library/Preferences/com.manytricks.Key Codes.plist 0xc42315ea90 <nil> 0xc4289f2360 <nil>}
2017/03/04 13:46:46 archiver/archiver.go:322	archiver.(*Archiver).fileWorker	83	   processed jpm/Library/Preferences/com.lobotomo.IPSecuritasMenu.plist, 1 blobs
2017/03/04 13:46:46 restic/node.go:609	restic.(*Node).fillExtendedAttributes	91	fillExtendedAttributes(/Users/jpm/Library/Preferences/com.manytricks.Key Codes.plist) [] <nil>
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385859	<Blob (tree) bcd95e6c, offset 848209, length 729>
2017/03/04 13:46:46 archiver/archiver.go:109	archiver.(*Archiver).Save	386185	Save(data, f05ef6bb): new blob
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385859	  updating blob d0b45f5f to pack c6e3af87
2017/03/04 13:46:46 archiver/archiver.go:263	archiver.(*Archiver).fileWorker	83	got job {/Users jpm/Library/Preferences/com.matryer.BitBar.plist 0xc428a42680 <nil> 0xc4297915c0 <nil>}
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385859	<Blob (data) d0b45f5f, offset 848938, length 495>
2017/03/04 13:46:46 archiver/archiver.go:186	archiver.updateNodeContent	93	checking size for file /Users/jpm/Library/Preferences/com.kiwifruitware.Burn.plist
2017/03/04 13:46:46 archiver/archiver.go:195	archiver.updateNodeContent	93	  adding blob f05ef6bb, 1412 bytes
2017/03/04 13:46:46 pipe/pipe.go:82	pipe.walk	16	start on "/Users/jpm/Library/Preferences/com.microsoft.autoupdate2.plist", basedir "/Users"
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385859	  updating blob aa5c0656 to pack c6e3af87
2017/03/04 13:46:46 repository/master_index.go:28	repository.(*MasterIndex).Lookup	386186	looking up id 3f07d1db, tpe data
2017/03/04 13:46:46 restic/node.go:609	restic.(*Node).fillExtendedAttributes	83	fillExtendedAttributes(/Users/jpm/Library/Preferences/com.matryer.BitBar.plist) [] <nil>
2017/03/04 13:46:46 archiver/archiver.go:302	archiver.(*Archiver).fileWorker	91	   jpm/Library/Preferences/com.manytricks.Key Codes.plist no old data
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 archiver/archiver.go:307	archiver.(*Archiver).fileWorker	91	   read and save jpm/Library/Preferences/com.manytricks.Key Codes.plist
2017/03/04 13:46:46 archiver/archiver.go:202	archiver.updateNodeContent	93	SaveFile("/Users/jpm/Library/Preferences/com.kiwifruitware.Burn.plist"): 1 blobs
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 archiver/archiver.go:322	archiver.(*Archiver).fileWorker	93	   processed jpm/Library/Preferences/com.kiwifruitware.Burn.plist, 1 blobs
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 archiver/archiver.go:263	archiver.(*Archiver).fileWorker	93	got job {/Users jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist 0xc422612c30 <nil> 0xc422d9ba40 <nil>}
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385862	<Blob (tree) 1d7e09e7, offset 223351, length 323>
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385862	  updating blob 3d6f2183 to pack 1fe02166
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 restic/node.go:609	restic.(*Node).fillExtendedAttributes	93	fillExtendedAttributes(/Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist) [com.apple.xcode.PlistType] <nil>
2017/03/04 13:46:46 repository/index.go:105	repository.(*Index).Store	385859	<Blob (data) aa5c0656, offset 849433, length 165>
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385863	  updating blob cf9dc586 to pack 7b146615
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 repository/packer_manager.go:142	repository.(*Repository).savePacker	385859	  updating blob 40bdbe94 to pack c6e3af87
2017/03/04 13:46:46 archiver/archiver.go:302	archiver.(*Archiver).fileWorker	83	   jpm/Library/Preferences/com.matryer.BitBar.plist no old data
2017/03/04 13:46:46 archiver/archiver.go:96	archiver.(*Archiver).Save	386210	Save(data, 286f9325)
2017/03/04 13:46:46 archiver/archiver.go:307	archiver.(*Archiver).fileWorker	83	   read and save jpm/Library/Preferences/com.matryer.BitBar.plist
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 pipe/pipe.go:107	pipe.walk	16	sending file job for /Users/jpm/Library/Preferences/com.microsoft.autoupdate2.plist, res 0xc42a3c1f20
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
2017/03/04 13:46:46 archiver/archiver.go:252	archiver.(*Archiver).fileWorker.func1	93	done
2017/03/04 13:46:46 repository/index.go:140	repository.(*Index).Lookup	386186	id 3f07d1db not found
```

The last file referenced therein doesn't look strange to me (other than the name "microsoft" in it ...

```
ls -l@ /Users/jpm/Library/Preferences/com.microsoft.autoupdate2.plist
-rw-------  1 jpm  staff  557 Apr  3  2014 /Users/jpm/Library/Preferences/com.microsoft.autoupdate2.plist
```

**Comment by fd0** [comment]
Ah, I need the goroutine number from the panic, do you still have that somewhere?

**Comment by jpmens** [comment]
This is the last panic (matching the debug log): 

```
debug log file /tmp/restic-debug.log
debug enabled
scan [/Users/jpm]
scanned 122813 directories, 765571 files in 2:03
panic: runtime error: index out of range / 118.216 GiB  453081 / 888384 items  0 errors  ETA 24:33

goroutine 93 [running]:
panic(0x4d10e0, 0xc42000e120)
	/usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/pkg/xattr.Getxattr(0xc4275274f0, 0x42, 0xc427dd4860, 0x19, 0xc4238171c0, 0x620fb, 0x30, 0x4f37e0, 0xc423d15501)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/github.com/pkg/xattr/xattr_darwin.go:14 +0x462
restic.Getxattr(0xc4275274f0, 0x42, 0xc427dd4860, 0x19, 0x0, 0x1, 0x0, 0xc4229b3d48, 0xc423d154d8)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/node_xattr.go:15 +0x5c
restic.(*Node).fillExtendedAttributes(0xc429f7d200, 0xc4275274f0, 0x42, 0x4, 0x1)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/node.go:616 +0x2cc
restic.(*Node).fillExtra(0xc429f7d200, 0xc4275274f0, 0x42, 0x7a0180, 0xc422612c30, 0x2, 0x2)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/node.go:596 +0x29a
restic.NodeFromFileInfo(0xc4275274f0, 0x42, 0x7a0180, 0xc422612c30, 0x7a0180, 0xc422612c30, 0x0)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/node.go:82 +0x1f4
restic/archiver.(*Archiver).fileWorker(0xc42903e2d0, 0xc4229b3950, 0xc4299fb6b0, 0xc429575200, 0xc4295754a0)
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/archiver/archiver.go:276 +0x708
created by restic/archiver.(*Archiver).Snapshot
	/var/folders/ql/0s97ymcd4n15lv5rtd3ptg680000gn/T/restic-build-763876134/src/restic/archiver/archiver.go:711 +0x76b

```

Does that have what you need?

**Comment by jpmens** [comment]
FWIW, the first and second panic logs differ:

```
goroutine 32 [running]:
goroutine 93 [running]:
```

**Comment by fd0** [comment]
Yes, this line from the debug log is it:
```
2017/03/04 13:46:46 restic/node.go:609	restic.(*Node).fillExtendedAttributes	93	fillExtendedAttributes(/Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist) [com.apple.xcode.PlistType] <nil>
```

There you can see that restic tries to read an extended attribute called `com.apple.xcode.PlistType` from the file `com.michaelvillar.FileShuttle.plist`, which failed. I'll draft up a quick program to debug this further.

**Comment by fd0** [comment]
The goroutine numbers are always different ;)

**Comment by jpmens** [comment]
```
$ ls -l@ /Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist
-rw-------@ 1 jpm  staff  508 Aug 20  2014 /Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist
	com.apple.xcode.PlistType	  0
```

**Comment by fd0** [comment]
Could you please do:
 * Set a temporary `GOPATH`, get the `xattr` library: `export GOPATH=/tmp/gopath; go get github.com/pkg/xattr`
 * Download https://gist.github.com/6bc11054fc3dcb241f9ed3871e809df9

Then run it on the file:
```
$ go run /Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist
```

**Comment by jpmens** [comment]
```
extended attributes for /Users/jpm/Library/Preferences/com.michaelvillar.FileShuttle.plist:
[com.apple.xcode.PlistType]
  com.apple.xcode.PlistType: ""
```

**Comment by fd0** [comment]
Huh. Ah! It's indeed a bug in the upstream library, and it has been fixed there: https://github.com/pkg/xattr/pull/4/commits/46d512b8799ac8533031573b5716efbc9e0634cd

**Comment by fd0** [comment]
Can you please try making a backup again with the code in the branch `update-pkg-xattr` and report back if this fixes the panic?

**Comment by jpmens** [comment]
`snapshot bcb7904f saved`

That fixes it. Thank you very much.

**Comment by fd0** [comment]
Cool, then I'll merge the PR.
